### ISSUE TITLE
[5-2. Result]画面実装（API組込）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#104]
- 対応内容
  - [ ] API組み込み
  - [ ] UI調整

- 対象API
  - `GET /run_result/{project_id}`

**Comment by Reactplus-Hao** [comment]
- Nội dung xử lý:
    - Tích hợp API
    - Điều chỉnh UI

**Comment by reactplus-thom** [comment]
デモ動画：https://drive.google.com/file/d/1yNzQnARNH7Do251F2Gq0IMAi981cvdNf/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@reactplus-thom 

対象のブランチ feature/integrate_api_results で動作確認したところ、Resutl画面遷移時、以下のエラーが発生しているようです。
ご確認ください。

--

> ### TypeError: Cannot read properties of undefined (reading 'status')
> 
> (anonymous function)
> D:/workspace/MRIAnalysisStudioforMouse/frontend/src/components/Experiment/ExperimentTable.tsx:60
> 
> ```
>   57 |   Status:
>   58 | </Typography>
>   59 | <Box>
> > 60 |   <ExperimentStatusIcon status={data['3a55fa37'].status}/>
>   61 | </Box>
>   62 | <Box>
>   63 |   <Typography>Start time: {dayjs(data['3a55fa37'].started_at).format('YYYY-MM-DD HH:mm')}</Typography>
> ```
> 
> View compiled
> -> 20 stack frames were collapsed.
> (anonymous function)
> D:/workspace/MRIAnalysisStudioforMouse/frontend/src/components/Experiment/Experiment.tsx:42
> 
> ```
>   39 | if(!id) return
>   40 | try {
>   41 |   const res = await getResultProject(id)
> > 42 |   setData(res)
>   43 | }
>   44 | catch {}
>   45 | finally {
> ```
> View compiled

**Comment by itutu-tienday** [comment]
1点、追加修正をお願いしたく思います。

APIレスポンスの "message" の内容を、下図のように、ステータスアイコンのクリックで表示させてください。

![Image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/27e06e32-f9ae-4a51-b2fe-15c304b179ec)

- 補足
  - ブランチ `feature/integrate_api_results` に、API の修正（message 項目を追加）を適用しています。
  - ステータス success/error

**Comment by reactplus-thom** [comment]
Click vào icon status thì cho hiển thị message lỗi.

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/dffe956c-f59f-4deb-8dcc-874994b30d34)

Thông tin bổ sung:
- Đã đẩy phần code sửa API vào branch `feature/integrate_api_results`
- Cứ có message là cho click được và hiển thị, bất kể status là success/error

**Comment by reactplus-thom** [comment]
@itutu-tienday 

1点確認させていただきますが、

> messageがある場合、クリック可能として下さい。

とありますので、messageがない場合は想定されていますか？
※APIからはいつもmessageを返却しますでしょうか？

また、messageがない場合、画面上はどのよう挙動を期待されますか？押下できないのでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 
APIがまだモック版なので、明確ではない部分はありますが、「messageがない場合がある（null or 空文字列）」を想定します。
またメッセージがない場合は、クリック不可としてください。
