### ISSUE TITLE
[5-3. Visualize]画面実装（API組込）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#105]
- 対応内容
  - [ ] API組み込み
  - [ ] UI調整

- 対象API
  - Generate Stats Images
    - `POST /visualize/generate/{project_id}`
  - Download Stats Report
    - `POST /visualize/download/{project_id}`

**Comment by Reactplus-Hao** [comment]
- Nội dung xử lý:
    - Tích hợp API
    - Điều chỉnh UI
         - Spec: https://docs.google.com/presentation/d/1_bAOIX3rxpTKIvWdnqwOXvl_O91-ZGt3/edit#slide=id.g224180341bc_0_2156

**Comment by reactplus-thom** [comment]
デモ動画：https://drive.google.com/file/d/1yNzQnARNH7Do251F2Gq0IMAi981cvdNf/view?usp=drive_link
