### ISSUE TITLE
[3-1. Image View] 画面実装（API組込）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#108]
- 対応内容
  - API実装
    - [ ] 画像表示
    - [ ] 画像付帯情報の保存（「Save Attributes」ボタンでの保存）

**Comment by Reactplus-Hao** [comment]
**Tích hợp API cho màn hình 3-1. Image View**

- Nội dung xử lý:
    - Tích hợp API
        - Hiển thị ảnh
        - Save thông tin phụ thuộc của ảnh（Save bằng button「Save Attributes」）
