### ISSUE TITLE
[4-2. Edit Project] 画面実装（API組込）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#111]

**Comment by itutu-tienday** [comment]
（メモ）
- 当画面で利用するAPI `PUT /workdb/project/{project_id}` の提供が遅れているため（6/14頃提供予定）、6/9では、以下の様な暫定対応を想定
  -  `PUT /workdb/project/{project_id}`  の呼び出しは、スキップとしておく。
  - ※上記APIで更新対象の情報は、"project_name" のみである想定のため、動作テストなどへの影響は少ないため。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
- PUT /workdb/project/{project_id}のAPIで更新対象の情報は、"project_name" だけではなく、image_countもある様なため、
動作テストなどへの影響は小さくないと思います。
- 下記の動作が確認できないと思います。
   - Edit Project (Edit Imageset)とWorkflowとAlignment Dialog関連の遷移の動作
      - Workflow画面 → Edit Imageset画面 → Imagesetを変更＆OK → Workflow画面へ復帰 の遷移を行うと、ImagesetがEdit Projectで登録した件数ではなくなります。
   - Edit Projectで編集したimage_countも更新されなくなります。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
- `PUT /workdb/project/{project_id}` の image_count は、更新対象外となります（バックエンド側での自動計算の値）。
- Workflow画面上の image_count は、`GET /workdb/dataset/{project_id}/search` のレスポンスより、FE側でカウントください。
  - もし課題があれば（カウントを行うことが難しいなど）、ご相談ください。

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/131
・動作確認のエビデンス：https://drive.google.com/drive/folders/1FB6SPutqG3hCu3bFzXH5wUouBEHwZPSJ
