### ISSUE TITLE
[5-1-1. Alignment] Alignmentダイアログ調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#114]
- 対応内容
  - [x] Alignmentダイアログのパラメーター初期値の調整
    - ※画面設計書 v12 の「5-1-1. Alignment ＞ パラメータ初期値」を参照

### 課題（不具合・指摘・要望）

- [x] 1. Aligment parameter は、過去のWF履歴データをインポート（API経由）したタイミングで、毎回初期値にクリアしてください。
  - WF履歴データのインポートAPIは `GET /experiments/fetch/{project_id}`
- [x] 2. Workflowを実行（RUN ALL / RUN）した直後、frontendで保持している Aligmnent parameter を、全て初期値にクリアしてください。
  - （目的）Workflowを続けて RUN ALL / RUN した際、同じAligmnent parameter を連続して送信しないようにするため。

**Comment by itutu-tienday** [comment]
>1. Aligmnet param は、過去のWF履歴データをインポート（API経由）したタイミングで、毎回初期値にクリアしてください。

上記は 画面設計書 v12 には明記がないですが、対応をお願いします。

**Comment by reactplus-thom** [comment]
Bug bổ sung:

1. Hãy set Aligmnet parameter về giá trị khởi tạo mỗi lần import  (thông qua API) dữ liệu lịch sử WF quá khứ.
API import dữ liệu lịch sử WF:  GET /experiments/fetch/{project_id}

**Comment by reactplus-thom** [comment]
@itutu-tienday 

修正要望について念のため確認です。

現状の実装として、WF履歴データのインポートを実行する際に`api: /experiments/fetch/project_id`　を呼び出して、
①Alignmentのパラメータが存在する場合はそのパラメータに設定しますが、
②Alignmentのパラメータが存在しない場合、添付画像のような初期値に設定します。
![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/00f556d9-e3af-4d79-9dfa-4205247e74ad)


という状態になり、それぞれのケースで処理方針を分けています。
では、上記①と②のどちらの場合も、②の処理方針※にしてほしいという認識であっていますでしょうか？
※Workflow画面に遷移するといつも添付画像のような初期値に設定します。

**Comment by itutu-tienday** [comment]
はい、上記で記載いただいている通りの仕様で想定しています。

なお、Alignment Nodeにこのような処理を入れる事由を、念のため以下記載します。
※ **Alignment Nodeのみの特殊仕様** になります。

#### Alignment Nodeの送信パラメーターをクリアする事由

1. 画面設計書（v12）にも記載ありますが、Alignment で設定したパラメーターは、バックエンド側で **NiFTI画像内に直接記録される形** で想定されています。
2. 上記の仕様に起因し、Alignment パラメーターは毎回初期値にもどす仕様とします。
    - もし前回のパラメーターを再送信する場合、Alignment処理済みの画像に何度もAlignment処理が適用されてしまう動作となるため。

**Comment by reactplus-thom** [comment]
Khách trả lời như sau nhé:
- **Cả 2 trường hợp có tồn tại Alignment param hay ko thì cũng sẽ set về giá trị mặc định ban đầu** (trong ảnh)

Ngoài ra, bổ sung thêm lý do tại sao lại có spec như vậy ở Alignment Node là như sau:
(!!**Lưu ý là spec này chỉ áp dụng riêng cho Alignment Node**)

**Lý do tại sao lại phải clear params khi gửi Alignment Node:**

- Như đã mô tả ở tài liệu thiết kế màn hình, params cài đặt ở Alignment sẽ được ghi trực tiếp vào trong ảnh NiFTI phía backend
- Chính vì spec như trên, nên params của Alignment mỗi lần đều sẽ phải back về giá trị ban đầu.
-> nếu truyền lên params của lần trước thì sẽ sinh ra vấn đề đối với ảnh đã xử lý Alignment xong rồi nhưng vẫn tiếp tục phát sinh xử lý Alignment lần này đến lần khác.

**Comment by itutu-tienday** [comment]
@reactplus-thom 
上記の動画の内容で、基本的に想定仕様と合っています。

なお以下補足します。

・動画では新規Projectの操作が行われていますが、「既存Project＋過去のWorkflow実行履歴がある」のパターンをご確認ください。
・#138 が解決前のため、当件は #138 の解決後のクローズとさせていただきます。

**Comment by reactplus-thom** [comment]
@itutu-tienday 
こちら対応が終わっております。

・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/143
・動作確認：
https://drive.google.com/file/d/1CY1OXtyQbsch6zWn_Kkg0iAmLnJjX77U/view?usp=drive_link
https://drive.google.com/file/d/1IF7X7JzVqBKD8jDD4hcF1VuGqjEfA2qi/view?usp=drive_link

**Comment by reactplus-thom** [comment]
Khi thực hiện các thao tác như dưới đây thì thấy rằng Alignment Parameter của lần trước đó không được đưa về giá trị khởi tạo.

1. Di chuyển màn hình từ 4.Project → 5-1.Workflow
2. Hiển thị Alignment Dialog => ở chỗ này thì Alignment Parameter vẫn được đưa về giá trị khởi tạo bình thường
3. Di chuyển màn hình từ 5-1.Workflow → 4.Project
4. Lại di chuyển màn hình từ 4.Project → 5-1.Workflow
5. Hiển thị Alignment Dialog => **ở đây thì Alignment Parameter đang ko được đưa về giá trị khởi tạo**

Remarks:
Do có rất nhiều pattern di chuyển đến màn hình Workflow nên tôi nghĩ nên quy hoạch tập trung xử lý điều kiện khởi tạo Alignment Parameter về 1 chỗ. (tôi chỉ nhắc thế thôi, còn nếu các bạn hiện đã xử lý như vậy rồi thì ko sao)

**Comment by reactplus-thom** [comment]
添付動画のような動作でよろしいでしょうか。

https://drive.google.com/file/d/1-r4V5mpG8Z3J_Ut33U8NcXkPIBmQLfr0/view?usp=drive_link

**Comment by itutu-tienday** [comment]
仕様調整となるのですが、以下について、対応をいただきたいと思います。

> -  2\. Workflowを実行（RUN ALL / RUN）した直後、frontendで保持している Aligmnent parameter を、全て初期値にクリアしてください。
>    - （目的）Workflowを続けて RUN ALL / RUN した際、同じAligmnent parameter を連続して送信しないようにするため。

**Comment by reactplus-thom** [comment]
Ngay sau khi chạy Workflow (RUN ALL / RUN), thì hãy clear toàn bộ Aligmnent parameter ở phía frontend về giá trị khởi tạo.
(mục đích: để khi tiếp tục RUN ALL / RUN trên Workflow đấy thì sẽ không gửi lại Aligmnent parameter trùng lặp nữa)

**Comment by reactplus-thom** [comment]
@itutu-tienday 
念のため確認ですが、
初期値にクリアするタイミングについて
RUN/RUN ALLボタンを押下した直後だという認識でよろしいでしょうか。
それとも、WF実行が完了したときでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 
> 初期値にクリアするタイミングについて

上記は、「RUN/RUN ALLボタンを押下した直後」でお願いします。

※厳密には、「Alignmentノードの実行完了」で判断する形が正確ですが、判定条件が複雑化するため、シンプルに「RUN/RUN ALLの実行直後」とします。

**Comment by reactplus-thom** [comment]
Thời điểm reset lại giá trị là ngay sau khi nhấn nút RUN/RUN
(Đúng ra phải là sau khi chạy xong Alignment node nhưng vì điều kiện phán đoán của nó khá phức tạp nên thôi cứ cho clear sau khi nhấn nút cũng được)

**Comment by reactplus-thom** [comment]
> 2. Workflowを実行（RUN ALL / RUN）した直後、frontendで保持している Aligmnent parameter を、全て初期値にクリアしてください。
> （目的）Workflowを続けて RUN ALL / RUN した際、同じAligmnent parameter を連続して送信しないようにするため。

・動作確認：https://drive.google.com/file/d/17Uhf9oYpVFd_TIyCzDmuC_8WFsjkj9fJ/view?usp=drive_link
