### ISSUE TITLE
6/5リリース版不具合事項

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#121]
## 不具合

- [x] 1. Workflowが実行できなくなっている（RUNボタンを押しても反応がない）
- [x] 2, .env で `USE_FIREBASE_TOKEN=False` とすると、認証エラー（401）が生じる
  - リクエストヘッダ内のExTokenのスペルミス？

**Comment by Reactplus-Hao** [comment]
1. Hiện tại Workflow đang không thể chạy được (Cho dù nhấn button RUN thì cũng k thấy phản hồi gì)
2. Khi set USE_FIREBASE_TOKEN=False trong file .env thì đang bị lỗi authen (401)
    Liệu đây có phải lỗi spell của ExToken trong request header?

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このIssueの２つ不具合を修正して、下記のPRを作成致しました。
お手数ですが、ご確認お願い致します。
・PRのリンク：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/123
・エビデンス：https://drive.google.com/file/d/14YP6OA9cAgiP5-jHTvk9RR24Xs5dsKqy/view?usp=sharing
