### ISSUE TITLE
[5-1-1. Alignment] Alignmentダイアログ不具合修正

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#125]
### 不具合・指摘

- 6/6版
  - [x] 1.「＜＞」キーで画僧を切り替えられるが、画像が2枚分しか切り替えられない？ 模様
- 6/9版
  - [x] 2. Aligmnet paramのImageのIDには、"ID"（数値）を指定してください。
  - [x] ~~3. 「EDIT IMAGESET」からの画面復帰時、Aligmnet paramのImageのIDには、WorkDBのImageのIDを指定してください。~~
    - ~~現在は、RawDBのID（EditProject画面の左ペインから取得できるID）が指定されている。 これをWorkDBのID（APIのレスポンスで取得できるID）の指定とする。~~
    - 関連: #142 
    - （6/13追記）バックエンド側の仕様では、「RawDBのIDとWorkDBのIDは一致させている」ということを確認。おそらく他の要因（API側の不具合 #146）の可能性がある。API側の修正後 再確認する

**Comment by Reactplus-Hao** [comment]
Nhờ bên mình chỉnh sửa bug trong dialog Alignment ạ.
Hiện tại, đang có thể switch ảnh bằng keyboard 「＜＞」, nhưng có vẻ đang chỉ có thể switch được giữa 2 ảnh thôi (KH check với source API cung cấp ngày 6/6）

**Comment by itutu-tienday** [comment]
>  2. Aligmnet paramのIDには、"ID"（数値）を指定してください。

上記の事項については、以前（5/19）にslackで以下の様に回答をいただいています。
IDを数値（実際のAPIからの戻り値を利用）するのに、何か問題があれば、お伝えくください。

> ReactPlus_BrSE_Hao（ハオ） 5/19
>> Alignmentの送信パラメータのうち、項目 "id" は、数値を設定ください。（Database APIから取得できる画像レコードのID値に対応）
> 現在、項目 "id" にURLを設定している目的は、どのURLの画像のパラメータか分かって、パラメータを取得できるためです。
> 今後、実際のAPIの統合の時にDatabase APIから取得できる画像レコードのID値を設定させて頂きますが、問題がございませんでしょうか。

**Comment by reactplus-thom** [comment]
Về nội dung sửa:
2. Hãy chỉ định "ID" (giá trị số) ở ID của Aligment param.

Trước đây chúng tôi đã nhận được câu trả lời như dưới đây từ các bạn. Vì vậy chúng tôi đang ko hiểu tại sao các bạn chưa xử lý chỗ này, hoặc là nếu mà set ID là giá trị số (sử dụng giá trị trả về từ API) có vấn đề gì thì vui lòng báo lại cho chúng tôi biết.

> Hiện nay, mục đích của việc set URL ở "id" là để biết được nó là param của ảnh từ url nào, và để lấy param.
> Sau này khi tích hợp API, chúng tôi định sẽ set giá trị ID của record ảnh lấy được từ Database API.

**Comment by reactplus-thom** [comment]
@itutu-tienday 

2の対応が終わりました。ご確認お願い致します。
・動作確認のエビデンス：https://drive.google.com/file/d/1q9jF0UE37-ovPfP1ZOfdPmI0V78jj1ft/view

**Comment by itutu-tienday** [comment]
こちらの確認で、事象が解消されていない様なのですが、確認をお願いしたいと思います。

- 確認条件
  - 対象の修正（6/9 12:30 のcommit）を取得
  - frontendを再起動
  - 初回Workflow実行、2回目以降のWorkflow実行、を確認

- Alignment pamraters log (image_id にpathが入っている) 

```json
{
  "input_0": {
    "id": "input_0",
    "type": "ImageFileNode",
    "data": {
      "label": "1 ... and 3 files",
      "type": "input",
      "path": [
        "/workdb/image/1/1",
        "/workdb/image/1/2",
        "/workdb/image/1/3",
        "/workdb/image/1/4"
      ],
      "param": {
        "alignments": {
          "path": "alignments",
          "type": "child",
          "value": [
            {
              "image_id": "/workdb/image/1/1",
              "x_pos": "80",
              "x_resize": 1,
              "x_rotate": 0,
              "y_pos": 0,
              "y_resize": 1,
              "y_rotate": 0,
              "z_pos": 0,
              "z_resize": 1,
              "z_rotate": 0
            },
            {
              "image_id": "/workdb/image/1/2",
              "x_pos": 0,
              "x_resize": 1,
              "x_rotate": 0,
              "y_pos": 0,
              "y_resize": 1,
              "y_rotate": 0,
              "z_pos": 0,
              "z_resize": 1,
              "z_rotate": 0
            },
            {
              "image_id": "/workdb/image/1/3",
              "x_pos": 0,
              "x_resize": 1,
              "x_rotate": 0,
              "y_pos": 0,
              "y_resize": 1,
              "y_rotate": 0,
              "z_pos": 0,
              "z_resize": 1,
              "z_rotate": 0
            },
            {
              "image_id": "/workdb/image/1/4",
              "x_pos": 0,
              "x_resize": 1,
              "x_rotate": 0,
              "y_pos": 0,
              "y_resize": 1,
              "y_rotate": 0,
              "z_pos": 0,
              "z_resize": 1,
              "z_rotate": 0
            }
          ]
        }
      },
      "fileType": "image"
    },
    "position": {
      "x": 49,
      "y": 149
    },
    "style": {
      "border": "1px solid #777",
      "height": 130,
      "padding": null,
      "width": null,
      "borderRadius": null
    }
  },
  "suite2p_file_convert_bv7jdbqfc8": {
      ...
  }
}
```

**Comment by itutu-tienday** [comment]
- 追加情報ですが、以下のケースは、image_id が適切に設定されていることを確認しました。（こちらの確認誤りでした）
  - 初回Workflow実行時

- ただし、2回目以降のWorkflow実行時、複数の挙動のパターンが存在するようです。
  - 以下では、image_id に "/workdb/image/" と "/rawdb/image/" のパスが混在し格納されています。


```json
{
  "path": "alignments",
  "type": "child",
  "value": [
    {
      "image_id": "/workdb/image/2/1",
      "x_pos": 0,
      "x_resize": 1,
      "x_rotate": 0,
      "y_pos": 0,
      "y_resize": 1,
      "y_rotate": 0,
      "z_pos": 0,
      "z_resize": 1,
      "z_rotate": 0
    },
    {
      "image_id": "/workdb/image/2/2",
      "x_pos": 0,
      "x_resize": 1,
      "x_rotate": 0,
      "y_pos": 0,
      "y_resize": 1,
      "y_rotate": 0,
      "z_pos": 0,
      "z_resize": 1,
      "z_rotate": 0
    },
    {
      "image_id": "/workdb/image/2/4",
      "x_pos": 0,
      "x_resize": 1,
      "x_rotate": 0,
      "y_pos": 0,
      "y_resize": 1,
      "y_rotate": 0,
      "z_pos": 0,
      "z_resize": 1,
      "z_rotate": 0
    },
    {
      "image_id": "/rawdb/image/3",
      "x_pos": 0,
      "x_resize": 1,
      "x_rotate": 0,
      "y_pos": 0,
      "y_resize": 1,
      "y_rotate": 0,
      "z_pos": 0,
      "z_resize": 1,
      "z_rotate": 0
    }
  ]
}
```

**Comment by reactplus-thom** [comment]
1) Khách báo là họ confirm theo trình tự dưới đây thì ko thấy đã được fix:
- Pull source (thời điểm commit 6/9 10:30 VNT)
- Restart lại FE
- Kiểm tra với lần chạy workflow đầu tiên, và với các lần chạy workflow từ thứ 2 trở đi 
=> kết quả: Alignment pamraters log như comment https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/125#issuecomment-1586575601
 (thấy rằng ở image_id đang là path)

2) Bổ sung thêm:
- Ở case chạy workflow đầu tiên thì đã confirm được rằng image_id đã được set OK (lúc nãy chúng tôi check NG là do chúng tôi thao tác nhầm)
- Tuy nhiên, ở các lần RUN từ thứ 2 trở đi (back về màn 4.Project rồi lại vào lại màn Workflow), hoặc khi đi đến màn EDIT IMAGESET rồi lại back về thì thấy behavior mỗi lúc lại khác nhau.
- Như ở log dươi đây thì thấy ở image_id tồn tại cả 2 path là "/workdb/image/" và "/rawdb/image/" 
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/125#issuecomment-1586595968
