### ISSUE TITLE
[5-1. Workflow]不具合修正

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#127]
### 不具合

- [x] AlignmentDialog のEdit ImagesetからOKでWorkflow画面へ戻ると、Workflowが実行できない。 (6/5版)
- [x] Project画面からWorkflow画面へ遷移すると、Imagesetの件数が、0や実際の件数に、ランダム？に切り替わっている。
- [x] Workflow画面 → Edit Imageset画面 → Imagesetを変更＆OK → Workflow画面へ復帰 の遷移を行うと、Imagesetが0件となっている。（6/6版）

**Comment by itutu-tienday** [comment]
以下は修正済み。

> - AlignmentDialog のEdit ImagesetからOKでWorkflow画面へ戻ると、Workflowが実行できない。

**Comment by Reactplus-Hao** [comment]
Nhờ bên mình fix các bug màn Workflow dưới đây giúp KH.
- Khi di chuyển từ màn hình Project đến màn Workflow, thì số lượng Imageset đang bị switch giữa 0 và số lượng thực tế
- Khi di chuyển màn hình theo flow: Màn Workflow → Màn Edit Imageset (Khi nhấn button edit imageset thì sang màn Edit Project)→ Thay đổi Imageset và nhấn button  → Sau đó quay trở lại màn Workflow, thì số lượng Imageset lại đang thành 0 （KH check với source API ngày 6/6）

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> Workflow画面 → Edit Imageset画面 → Imagesetを変更＆OK → Workflow画面へ復帰 の遷移を行うと、Imagesetが0件となっている。（6/6版）

上記のAPIについて、現時点では、PUT /workdb/project/{project_id}のAPIは未提供のため、上記の動作が対応できない状態です。
PUT /workdb/project/{project_id}のAPIの統合の後、対応させて頂きます。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> 上記のAPIについて、現時点では、PUT /workdb/project/{project_id}のAPIは未提供のため、上記の動作が対応できない状態です。

以下の関連issueで、対応方法をコメントしています。ご確認ください。

https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/111#issuecomment-1579833354
> - Workflow画面上の image_count は、`GET /workdb/dataset/{project_id}/search` のレスポンスより、FE側でカウントください。
>   - もし課題があれば（カウントを行うことが難しいなど）、ご相談ください。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
> つまり、ご指示していただいている対応方法では実現性に問題ありません。

了解しました、ありがとうございます。

> カウントできるまでは画面に何も表示しない（真っ白の画面にする）ことにするのが対応可能ですが、その方針ではいかがでしょうか。

指摘しました事象は、そもそも正しい件数が表示されていない様でしたので、正しい数字が表示されるのであれば、少し時間を要してもOKと考えます。
なお上記のような通信の遅延を考慮し、issue #61 で通信時のローディングアイコン表示の対応を、依頼しています。
簡易な対応が可能であれば、Workflow画面への画面遷移時（4. Projects、4-2. Edit Project、からの遷移）、通信ローディングアイコンを表示させる対応を、お願いします。

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/131
・動作確認のエビデンス：https://drive.google.com/drive/folders/1FB6SPutqG3hCu3bFzXH5wUouBEHwZPSJ
