### ISSUE TITLE
[4-2. Edit Project] 不具合修正

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#128]
### 不具合・指摘

- 6/5版
  - [x] 1. 以下の手順で画像登録を行った場合、重複するIDの画像が登録できてしまっている。
    - Edit Project（Edit Imageset）で画像登録 → OKで前画面へ戻る → 再度Edit Project（Edit Imageset）へ遷移し画像登録
- 6/6版
  - [x] 2. Projects画面のImagesetの件数表示
    - Projects → Edit Projects → OKでProjectsへ戻る の遷移を行うと、Projects 画面でImagesetの件数が更新されていない。

**Comment by Reactplus-Hao** [comment]
Nhờ bên mình fix bug màn hình Edit Project dưới đây ạ:
- Trường hợp tiến hành đăng ký ảnh theo như trình tự dưới đây, thì lại đang có thể đăng ký được ảnh có ID trùng nhau
    - Đăng ký ảnh trong màn Edit Project（Khi nhấn button Edit Imageset và chuyển sang màn） →  Sau đó nhấn button OK và back về màn hình trước đó (Màn Workflow) → Sau đó lại di chuyển lại đến màn Edit Project（bằng button Edit Imageset）và đăng ký ảnh

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> 1. 以下の手順で画像登録を行った場合、重複するIDの画像が登録できてしまっている。
> Edit Project（Edit Imageset）で画像登録 → OKで前画面へ戻る → 再度Edit Project（Edit Imageset）へ遷移し画像登録

こちら不具合の対応に関しますが、まずは現状の実装を説明させていただきたいと思います。
つきまして、ProjectのAdd/Editの際に、
選択している画像はrawdbのIDで管理しているのですが、
画像をサーバへ送信した後、サーバーからその画像に応じたworkdbのIDがレスポンスされますので、
FE側でworkdbのIDに更新して管理するようにしています。
例）
①画像Aをドラグ＆ドロップして選択する
↓
②フロントエンドでは画像AのrawdbのIDをチェックして、重複の判断を行う
↓
③Add/OKボタンを押下してサーバへ送信する
↓
④サーバから画像AのworkdbのIDがが返却される
↓
⑤フロントエンドで画像AのrawdbのIDからworkdbのIDに更新する

よって、画像Aがすでに登録されている場合でも、
次回に画像Aを選択すると、FEはrawdbのIDを重複をしてしまいますので、存在していることは判断できない状況です。

解決するために、上記のステップ④のところはAPIからworkdbのIDだけではなく、
rawdbのIDも返却する必要あると思いますので、一度バックエンド開発者ともご検討していいただけないでしょうか。

よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
@reactplus-thom
まず *RawDBのID* と *WorkDBのID* について、当方で認識誤りがありました。
以下のissueに、バックエンド担当者から返答のあった現状仕様を記載しています。

- https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/142
  > バックエンド側の仕様では、「RawDBのIDとWorkDBのIDは一致させている」ということを確認。そのことから、当issueの課題は発生しないことを確認。

- 上記より、RawDBのID WorkDBのID は一致するとのことなので、区別せずにチェック等には利用可能となります。現在のFEの実装でOKのはず）
  - ざっとFEから動作を再確認したところ、確かにそのようになっていることを確認しています。
  - また #125 No.3 で挙げた不具合は、おそらく #146 の影響があった可能性があります。

現状は上記の認識ですが、もし疑問点（RawDBのID と WorkDBのID が一致していないように見える、など）があれば、お伝えください。

**Comment by reactplus-thom** [comment]
@itutu-tienday 
確か仰った通り、6/5～6/9 の間でアップデートかと思いますが、
本issueでご報告された2事象のどちらも、こちらでも再現しない状態です。

以下の動作確認時の動画をご確認のうえ、チケットをクロースするかご検討いただけないでしょうか。

> 1. 以下の手順で画像登録を行った場合、重複するIDの画像が登録できてしまっている。
> Edit Project（Edit Imageset）で画像登録 → OKで前画面へ戻る → 再度Edit Project（Edit Imageset）へ遷移し画像登録

https://drive.google.com/file/d/1QG9_qohNrn5rpNeF5liHh_hNUOgFO0r0/view?usp=drive_link

> 2. Projects画面のImagesetの件数表示
> Projects → Edit Projects → OKでProjectsへ戻る の遷移を行うと、Projects 画面でImagesetの件数が更新されていない。

https://drive.google.com/file/d/1BGrYewOgSZFAP8afts1dnC4T3XdzW3mk/view?usp=drive_link
