### ISSUE TITLE
database API docker container update (6/8版)

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#133]
database API の docker container を、6/8提供版へアップデートする

- セットアップ関連ファイル
  - https://drive.google.com/drive/folders/1J29pi8FDTvBFh3wsnBdWlX0UHDzM6WjQ
    - vbm-230608.zip  … docker container関連モジュール
    - SetupReadme.md  … セットアップ手順メモ

- 6/8版の主な更新内容
  - APIの追加
    - `PUT /workdb/project/{project_id}`
    - `GET /workdb/project/{project_id}`  ※QA表No.77の要望対応
    - ※6/8時点で、6/16リリース版に必要なdatabase APIは、一通り揃った状態。
  - DBコンテナのtimezoneをJSTに設定

**Comment by reactplus-thom** [comment]
Update docker container của database API (bản ngày 6/8)

- Các file setup liên quan:

https://drive.google.com/drive/folders/1J29pi8FDTvBFh3wsnBdWlX0UHDzM6WjQ
vbm-230608.zip … module liên quan docker container
SetupReadme.md … notes về trình tự setup

- Nội dung update chính của bản ngày 6/8

+Thêm các API:
PUT /workdb/project/{project_id}
GET /workdb/project/{project_id} ※Đối ứng theo yêu cầu của QA No.77
※Tại thời điểm ngày 6/8, các API database cần cho mốc release 16/6 như vậy đã có đủ.

+ Cài đặt timezone của DB container về JST (giờ chuẩn nhật bản)
