### ISSUE TITLE
Database TreeViewソート機能不具合

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#136]
### 不具合・指摘

Database TreeViewのソート機能で、以下の不具合？ が見受けられる。

- 対象画面
  - Database TreeViewのある画面

- 不具合
  - [x] Subjectカラムでソートしても、右側（Subjectの配下）がソートに追従していない。
  - [x] Sessionカラムでソートすると、それより左側がソートされている。（Dataより左側は、配下のソートに影響されない想定）
  - [x] 「Voxel size」カラムのソートが、数値順となっていない模様。（文字列順？）
    - 類似の「Size」カラムは、数値順でソートされている模様。
  
- 補足
  - データに問題があり、その影響があるようであれば、API開発者へ展開しますので、お知らせください。
  - テストケースに、上記のケース（TreeViewの親子階層のソートの挙動）を追加ください。

**Comment by reactplus-thom** [comment]
Phát hiện ra 1 số điểm dưới đây đang nghi ngờ là bug ở chức năng sort ở Database TreeView

-Màn hình phát sinh:
Màn hình có Database TreeView

-Nội dung bug:
1) Khi sort theo cột Subject thì phía bên phải (cấp dưới Subject) đang ko ăn theo
2) Khi sort theo cột Session thì phía bên trái cũng đang được sort theo (đúng ra phía bên trái của Data phải ko bị ảnh hưởng bởi sort cấp dưới)

-Bổ sung:
Nếu là do vấn đề của dữ liệu thì vui lòng báo lại, chúng tôi sẽ liên hệ với cả bên API để xử lý.
Vui lòng bổ sung thêm case trên kia vào testcase (phần check behavior theo layer cha-con trên Treeview)

**Comment by reactplus-thom** [comment]
@itutu-tienday 

>  Subjectカラムでソートしても、右側（Subjectの配下）がソートに追従していない。

これはデータの問題だと判断しておりますが、見分けられるデータでご確認してみていただけないでしょうか。

> Sessionカラムでソートすると、それより左側がソートされている。（Dataより左側は、配下のソートに影響されない想定）

こちらの内容ですが、過去の以下相談の通りに実装しているそうですが、再度ご確認いただけますでしょうか。
もし弊社の認識が間違っているのであれば、申し訳ないですがご指摘をお願い致します。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/30#issuecomment-1519562764

よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
了解しました。

・Subject配下の件は、API修正後（ #146 ）確認します。
・Dataより左側の件は、再確認します。

**Comment by itutu-tienday** [comment]
> ・Subject配下の件は、API修正後（ #146 ）確認します。

→ 上記は、API修正後、適切に動作している様であることを確認しました。（クローズ）

> ・Dataより左側の件は、再確認します。

以下の情報を再確認しましたが、やはり Dataカラムの配下（第2階層以降）でソートした場合は、Dataカラムの階層（第1階層）はそのまま（配下のソートに影響されない）動作の想定になります。
- https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/30#issuecomment-1519562764
  - > 画面設計書では、Sessionカラムではなく、Dateカラムをソートのグループの区切りとしており、
- 画面設計書（v12）、ページ「3. Database（3a. Tree View 詳細）」にて解説

**Comment by itutu-tienday** [comment]
また別件で1件、ソートの指摘事項を記載しています。

> - 「Voxel size」カラムのソートが、数値順となっていない模様。（文字列順？）

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> また別件で1件、ソートの指摘事項を記載しています。
> ・「Voxel size」カラムのソートが、数値順となっていない模様。（文字列順？）

こちらは承知しました。確認して対応するようにいたします。

> 以下の情報を再確認しましたが、やはり Dataカラムの配下（第2階層以降）でソートした場合は、Dataカラムの階層（第1階層）はそのまま（配下のソートに影響されない）動作の想定になります。

こちらに関しても対応方針として承知しました。
詳細仕様についてですが、以下の点念のため確認させてください。

①　そういうことなら、Dataレコード単位内（列）のソートになる認識ですが、あっていますでしょうか？

②　第1階層は配下のソートに影響されないのですが、　第２階層以降も同じ動作でしょうか？
　※第２階層は配下の第3階層のソートに影響されないとか。

よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
念のため、現時点の実装仕様を確認させてください。
※動作から、以下のような実装状況でしょうか。

1. Subject, Sessionは、第1階層（Lab/User/Date）をグループとしてソート。
2. Session の配下（Datatype～）は、第3階層（Session）をグループとしてソート。

**Comment by reactplus-thom** [comment]
@itutu-tienday 
はい、上記1.と2.ともご認識あっています。

では、今回は仕様書記載のとおりに、
・Subject, Sessionは、第1階層（Lab/User/Date）ではなく、第3階層（Session）をグループとしてソートする

ようにしてほしいという認識でよろしいでしょうか。

悪い聞き方で申し訳ありませんでした。
上記は確認したかった内容ですが、よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
>> 1. Subject, Sessionは、第1階層（Lab/User/Date）をグループとしてソート。
>> 2. Session の配下（Datatype～）は、第3階層（Session）をグループとしてソート。
> はい、上記1.と2.ともご認識あっています。

現状は上記の仕様となっているということで、了解しました。
顧客へ、現在の実装にて、再度仕様レビュー依頼します。
一旦当件は、現在の仕様で In Review(Araya) とさせていただきます。

また以下の件は、修正ご対応ください。

> ・「Voxel size」カラムのソートが、数値順となっていない模様。（文字列順？）

**Comment by reactplus-thom** [comment]
Cần fix bug dưới đây:

Ở cột Voxel size đang không được sort theo giá trị số (numerical order) (mà hình như là đang sort theo String order?)

**Comment by reactplus-thom** [comment]
@itutu-tienday 
以下対応、終わりました。

> ・「Voxel size」カラムのソートが、数値順となっていない模様。（文字列順？）

・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/163
・動作確認：https://drive.google.com/file/d/1Gw1HLxE1uFDtLLNxaWmd4SWKTcehNgQ3/view?usp=drive_link
