### ISSUE TITLE
[3.Database] 画面の表示性能について

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#137]
6/9版にて、実際のAPIからの応答データを使用して画面表示が行われているが、60件ほどの画像データ表示時、全体的に画面表示が遅くなっていることが確認されている。 まずは状況を分析する。

- 動作
  - Database View（Tree, List）の表示箇所
  - Database ViewからImage Viewをボップアップ表示する箇所

- 調査事項
  - Database Viewの表示性能と、Image Viewの表示性能は、関連があるか
  - 以前の調査から性能に変化はないか
    - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/30#issuecomment-1507968516
  - 上記の動作性能は、改善可能であるか （技術面、工数面）

**Comment by reactplus-thom** [comment]
@itutu-tienday 

取り急ぎ、こちらの環境で確認した結果を報告いたします。
つきまして、ご報告された「60件ほどの画像データ表示時、全体的に画面表示が遅くなっていること」は確認できておりません。
→参照動画：https://drive.google.com/file/d/16L7-03DilMjs__IKhm6JfuzA-_A7GSjS/view

※確認環境の構成は以下です。
![348387796_1458645751573737_4311018835658832712_n](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/fb7763a3-5115-432f-980e-f47f4a9544f2)

しかし、以下の修正も行いましたが、これで少しでもパフォーマンスが改善されないかご確認をお願いいたします。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/144

**Comment by itutu-tienday** [comment]
ありがとうございます。

動画からは軽快であるようなので、こちらの確認環境依存とも見受けられます。

またPRの内容は問題ないと思われますので、マージを進めています。

当件は一旦クローズ（InReview）とします。
