### ISSUE TITLE
[3-1. Image View]不具合

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#138]
### 不具合・指摘

- 6/9版
  -  [x] 1. Image Viewの初期表示時、XYZの画像表示領域に、画像が表示されていないケースがある（6/9版でほぼ再現する）
      - マウスで画像領域をドラッグすると、画像表示領域がリフレッシュされ、画像が表示される模様。

- 6/16版
  - [x] 2. 6/16版で、以下イメージ（画面設計書v13）の赤枠の部分（Origin, Dir cos）の表示がないため、表示をお願いします。
    - https://user-images.githubusercontent.com/135786736/245710388-80bf1385-554d-4eb8-b802-972262ef9b31.png
    - 仕様補足
      - 情報の更新は以下のタイミングで実施する
        - 「イメージのcroshair操作時」「Set Originボタン押下時」（他の欄の情報更新タイミングに同じ）
  - [x] 3.「Set Origin」の横に「Reset」ボタンを配置してください。
    - Resetボタン押下時は、座標入力欄（right ～ resize {z}）を初期値に設定してください。

**Comment by reactplus-thom** [comment]
Khi hiển thị Image View lần đầu thì ở khu vực hiển thị ảnh XYZ đang có trường hợp ảnh ko hiển thị ra (ở bản 6/9 tỷ lệ phát sinh là hầu hết)
- Nếu kéo và drop ảnh bằng chuột thì vùng hiển thị ảnh sẽ bị refresh và ảnh lại hiển thị.

**Comment by reactplus-thom** [comment]
@itutu-tienday 

ご報告された事象ですが、添付の仕様の対応に起因したものです。
つきまして、Resize (x|y|z)以外のパラメータは初期値が0となっていますので、
現状のような表示になってしまいます。
またマウスでドラグすると、パラメータもそれに従って調整されるため、画像が表示されるのもわりました。

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/fd2d0661-d4a7-4d81-9d67-a17d9f88d486)

すみませんが、こちら仕様について、再度ご確認いただけますでしょうか。

**Comment by reactplus-thom** [comment]
補足ですが、上記の仕様はAlignment Dialogの仕様となっていますが、
ライブラリを使って実装するようにしておりますので、修正すると水平修正になってしまいます。

**Comment by itutu-tienday** [comment]
逆に質問となりますが、NiFTI画像の初期表示位置が、Alignmentの初期表示値（ALL 0（Resizeは1））として想定しています。
前提の仕様に、相違がありますでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 
補足ですが、もしバックエンド側でパラメータ補正などする形が適当そうであれば、バックエンド担当者との相談を行いますので、お知らせください。

**Comment by reactplus-thom** [comment]
@itutu-tienday 

すみません、ここ部分の仕様について認識齟齬がある気がしているため、もう一度確認させてください。
こちらチームの認識ですが、

> NiFTI画像の初期表示位置が、Alignmentの初期表示値（ALL 0（Resizeは1））として想定しています。

となりまして、初期表示時にAlignmentパラメータはいつもの初期表示値（ALL 0（Resizeは1））を表示します。
そして、NiFTI画像位置もそのAlignment初期表示値に従って反映されまます。

もしかすると、NiFTI画像位置はAlignmentのパラメータとは紐づいてなく表示する想定でしょうか？

このタイミングで仕様確認になってしまい申し訳ありませんが、
まず仕様についてちゃんと理解したいと思いますので、ご確認させて頂ければと思います。

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> 現在Alignment Dialogに表示されているパラメータは、何が表示されているのでしょうか。
> NiFTI画像内（ヘッダ内）に保有している座標情報が表示されているでしょうか。

Yes/Noで回答すれば、Noとなります。
NiFTI画像内（ヘッダ内）に保有している座標情報が表示されているのではありません。
パラメータの初期値（ALL 0（Resizeは1））を絶対的な値として表示しているのです。

> 1. がYESである場合、上記で記載していますように、Alignment Dialogの入力欄で入力している値は、「0や1を起点とした 相対値 」とすることは（簡易に）対応可能でしょうか。

申し訳ないですが、技術面を調査したところ、フロントエンドでは対応難しい問題という判断になりました。

現状は上記のとおりですが、よろしくお願いいたします。

**Comment by reactplus-thom** [comment]
@itutu-tienday 

以下2点よろしくご確認お願いいたします。

①　左の赤い枠の値はNiFTI画像内のどのキーを取得すればよいでしょうか？

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/35db83fa-d324-4611-9af4-392441fa95ab)


②　昨日の話でparams入力欄でparamsを選択した時に該当の座標（?)の詳細情報を表示したいということがありますが、
見せていただいたイメージとしての画像を送っていただけないでしょうか？

よろしくお願いいたします。

**Comment by emuemuJP** [comment]
@reactplus-thom 
①コードを実際に見ていただいてる方の方がご存知かと思うのですが
この変数に設定するところかとおもいます
https://github.com/aces/brainbrowser/blob/fe0ce114c6cd8e317a6bdd9b7ef97cbf1c38309d/src/brainbrowser/volume-viewer/volume-loaders/minc.js#LL211C9-L215C11
②  https://docs.google.com/presentation/d/16RWtPSJYuE1VQHZVscRfNBOkDuTSXq3P/edit#slide=id.p53
こちらで追記しました。このような形でよかったでしょうか？

**Comment by reactplus-thom** [comment]
1) Các giá trị origin lấy từ key nào trong ảnh NifTi?
=> Lấy theo các biến này:
https://github.com/aces/brainbrowser/blob/fe0ce114c6cd8e317a6bdd9b7ef97cbf1c38309d/src/brainbrowser/volume-viewer/volume-loaders/minc.js#LL211C9-L215C11

2) Về yêu cầu hiển thị thông tin origin khi bấm vào param tương ứng:
=> Muốn hiển thị kiểu như dưới đây:
![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/80bf1385-554d-4eb8-b802-972262ef9b31)

Link tài liệu: https://docs.google.com/presentation/d/1_bAOIX3rxpTKIvWdnqwOXvl_O91-ZGt3/edit#slide=id.g224180341bc_0_1393

**Comment by reactplus-thom** [comment]
添付動画のような動作でよろしいでしょうか。

https://drive.google.com/file/d/1-r4V5mpG8Z3J_Ut33U8NcXkPIBmQLfr0/view?usp=drive_link

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/156

**Comment by itutu-tienday** [comment]
6/16版について、以下数点 指摘・修正依頼を挙げます。
確認・対応をお願いいたします。
※詳細は当issueの説明欄にも記載しています。

> 2. 6/16版で、以下イメージ（画面設計書v13）の赤枠の部分（Origin, Dir cos）の表示がないため、表示をお願いします。
> 3.「Refresh View」の横に「Reset」ボタンを配置してください。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
「Set Origin」の誤記でした。 → 修正しています。

**Comment by reactplus-thom** [comment]
・動作確認：https://drive.google.com/file/d/1WQkNgxXIFL4zJ08dZbOZ7j3aNrYRhUGX/view?usp=drive_link
