### ISSUE TITLE
Database(RawDB) Viewフィルタ機能実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#145]
- 対象画面
  - 3\. Database
    - Tree View
    - List View
  - 4-1. Add Project
  - 4-2. Edit Project （右ペイン）

- 機能
  - 検索条件
    - テキスト部分一致
    - And条件
  - フィルタ後の状態維持
    - ソートとの連動
    - Image Viewの「＜＞」キーとの連動
    - フィルタのクリア機能

### 指摘

- 6/16版
  - [x] 「CLEAR FILTER」のボタンは、Filter条件が指定されている場合に、表示させてください
  - [x] 4-2. Edit Project画面で、Filterを有効にすると、画面が「4-1. Add Project」の内容に切り替わってしまう模様。（OKボタンがAddボタンに変化する、など）
- 6/20版
  - [x] 「Workflow → Edit Imageset → Filter → OK」の画面遷移を行うと、Workflow画面へ戻る想定のところ、Projects画面へ戻ってしまっている。

**Comment by reactplus-thom** [comment]
- Các màn hình cần triển khai

Database:
Tree View
List View
4-1. Add Project
4-2. Edit Project （Pane bên phải）

- Chức năng

Điều kiện tìm kiếm:
Match 1 phần (partial text match)
Điều kiện And

Duy trì trạng thái sau khi filter:
Link với sort
Link với key 「＜＞」trên Image View
Chức năng clear filter

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/154
・動作確認：https://drive.google.com/file/d/1A21S7TXNms98vTxK2042HdU6z_8a1_OY/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@reactplus-thom 
6/16版で基本的な動作はOKの想定ですが、以下 要望事項を記載します。
ご対応お願いします。（もし何か懸念があればお伝えください）

- 「CLEAR FILTER」のボタンは、Filter条件が指定されている場合に、表示させてください

**Comment by reactplus-thom** [comment]
Trường hợp đang có điều kiện filter được chọn thì hãy cho hiển thị button "CLEAR FILTER"

**Comment by reactplus-thom** [comment]
@itutu-tienday 

念のため確認ですが、

> 「CLEAR FILTER」のボタンは、Filter条件が指定されている場合に、表示させてください

現状、「CLEAR FILTER」のボタンは常に表示されているのですが、
Filter条件が指定されている場合にのみ表示させたいという認識であっていますでしょうか。
それとも、以下のFilter選択ポップアップにも表示させるのでしょうか？
![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/245c5ed5-e1f7-4d94-8f7a-3099cf1a3487)

**Comment by itutu-tienday** [comment]
@reactplus-thom 
1. > Filter条件が指定されている場合にのみ表示させたいという認識であっていますでしょうか。
2. > それとも、以下のFilter選択ポップアップにも表示させるのでしょうか？

上記の1の想定でしたが、いずれでも（実装が簡易な方で）問題ありません。

**Comment by reactplus-thom** [comment]
@itutu-tienday 
こちらの方針にいたしました。

> Filter条件が指定されている場合にのみ表示させたいという認識であっていますでしょうか。

・動作確認：https://drive.google.com/file/d/1_ETyk3zGMRbideii89tcOBCavF6PkPMB/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@reactplus-thom 
ありがとうございます。

CLEAR FILTERの動作はOKなのですが、別件で不具合を確認しているので、確認と対応をお願いします。

>  - 4-2. Edit Project画面で、Filterを有効にすると、画面が「4-1. Add Project」の内容に切り替わってしまう模様。（OKボタンがAddボタンに変化する、など）

**Comment by reactplus-thom** [comment]
Cái button CLEAR FILTER thì OK rồi nhưng lại phát hiện thêm bug mới dưới đây:

Ở màn hình 4-2. Edit Project, khi active Filter thì màn hình giống như là bị chuyển sang nội dung của màn 「4-1. Add Project」
(button OK bị đổi thành button Add, etc...)

**Comment by reactplus-thom** [comment]
> 4-2. Edit Project画面で、Filterを有効にすると、画面が「4-1. Add Project」の内容に切り替わってしまう模様。（OKボタンがAddボタンに変化する、など）

・動作確認：https://drive.google.com/file/d/1VclFLPaqwldAMIxoK7FqFfJVJOU1avzE/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@reactplus-thom 
以下一点、追加の指摘事項を確認していますので、ご確認お願いします。
>  - 「Workflow → Edit Imageset → Filter → OK」の画面遷移を行うと、Workflow画面へ戻る想定のところ、Projects画面へ戻ってしまっている。

**Comment by reactplus-thom** [comment]
Khi di chuyển màn hình theo luồng「Workflow → Edit Imageset → Filter → OK」, sau đó khi định back về màn Workflow thì lại bị back về màn hình Projects

**Comment by reactplus-thom** [comment]
> 「Workflow → Edit Imageset → Filter → OK」の画面遷移を行うと、Workflow画面へ戻る想定のところ、Projects画面へ戻ってしまっている。

・動作確認：https://drive.google.com/file/d/1J20LJnaSJIcykuXTKA1YqZSOG1bjcL36/view?usp=drive_link
