### ISSUE TITLE
OHIF Viewer組み込み

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#15]
**概要**
MRI画像Viewerについて、「OHIF Viewer」を利用する方向で仮決定。
仕様調査、組み込みを実施する。

**重要度**
高

**ブランチ名**
追加機能のbranchを書く。

**期限**
2023/3

**関連**
#6 

**想定タスク**

**※適宜追加更新**

- 基本要件への対応
  - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/6#issuecomment-1404746257

- 利用バージョンの選定
  - [x] 最新はv3系の様であるが、3系の利用で問題はないか？
    - 3系で動作可能。 (2023/2)

- 表示
  - [x] 複数画像の表示切替の検証
    - 以下を検証
      - [x] 1. Viewer標準の画面リスト（左サイド欄）による切り替え
      - [x] 2. 1画像ずつ、独自に配置したボタン（← →）による切り替え
      - → 1. での対応が行いやすいらしいことを確認。（dicom json内のjsonデータをUIに渡すことで一覧表示される）
      
  - [x] Viewerのモーダル表示 （OHIF標準のUIでポップアップ表示させる）
    - → 別アプリ（nodeアプリ）として立ち上げることで、標準UIのviewerを立ち上げ可能。

- 画像リソース
  - [ ] NiFTI形式データの表示
  - [x] dicom webを利用した画像表示
  - [x] ローカルファイルからの画像表示

- UI
  - [x] メニューボタンのカスタマイズ方法
    - → 一旦、簡易な対応は難しいらしいことを確認。（dicom web経由のUI構築が必要？）

- その他
  - [x] 3Dモデル表示
    - → 非対応を確認。

**Comment by itutu-tienday** [comment]
↓OHIF/Viewersライブラリ調査レポート

- UIとソースのデータを制御するには、個別のDICOMサーバーをセットアップする必要がある。
  - (https://docs.ohif.org/configuring/data-source.html)
- v3-stableブランチ用DICOMサーバの環境には、15以上のNodeバージョンが必要ですが、現在のプロジェクト４の環境にv14のNodeバージョンを強制している。
- FE側にOHIF/Viewersライブラリをインストールした後、実行にはかなりのRAMをかかる。
- 画像の読み込み速度が非常に遅い。
- UIのカスタマイズとDCOMのデータの追加には、DICOMサーバーのソースで行う必要があるため、カスタマイズの仕方の調査と対応に工数がかなりかかる
- ローカルでDICOMサーバーをセットアップした後、確認しましたが、.dcmのファイルのみアップロードできる。
  - （他のファイルをアップロードすると、エラーになっている）

**Comment by itutu-tienday** [comment]
- UIとソースのデータを制御するには、個別のDICOMサーバーをセットアップする必要がある。
  - (https://docs.ohif.org/configuring/data-source.html)

> - v3-stableブランチ用DICOMサーバの環境には、15以上のNodeバージョンが必要ですが、現在のプロジェクト４の環境にv14のNodeバージョンを強制している。

- Nodeバージョンを切り替えての検証は行っておくのがよいと想定するため、以下の検証をお願いします。
  - Nodeバージョンを切り替えて検証
    - 18 (LTS) → 16 (LTS)  の順で検証する。
  - 既存アプリケーションの正常動作確認

> - FE側にOHIF/Viewersライブラリをインストールした後、実行にはかなりのRAMをかかる。
> - 画像の読み込み速度が非常に遅い。

- 公式のデモ版と比較しても、同様な性能でしょうか。
  - もしデモ版と表示性能に何らか差異があるようであれば、要因の調査を行う必要がありそうです。

> - UIのカスタマイズとDCOMのデータの追加には、DICOMサーバーのソースで行う必要があるため、カスタマイズの仕方の調査と対応に工数がかなりかかる

- 了解しました、現時点では、UIのカスタマイズは極力対象外とする方向にて想定します。

> - ローカルでDICOMサーバーをセットアップした後、確認しましたが、.dcmのファイルのみアップロードできる。
>   - （他のファイルをアップロードすると、エラーになっている）

- 以下に、ローカル画像アップロード版のデモがあるようです。こちらがどのように動作しているか（DICOMサーバーを使用していない？）、確認いただけますでしょうか。
  - https://ohif.org/get-started
    - →「Use your own data」

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
OHIF/Viewerライブラリについて、さらに調査して、下記に結果を共有。

> - Nodeバージョンを切り替えての検証は行っておくのがよいと想定するため、以下の検証をお願いします。
> 　　　Nodeバージョンを切り替えて検証
> 　　　　　18 (LTS) → 16 (LTS) の順で検証する。
> 　　　既存アプリケーションの正常動作確認

Nodeバージョンを18へアップデートして、システムが正常に動作していることを確認できました。

> FE側にOHIF/Viewersライブラリをインストールした後、実行にはかなりのRAMをかかる。

OHIF/Viewersライブラリをインストールした後、追加で`export NODE_OPTIONS="--max-old-space-size=8192"`というコマンドを実行することで、RAMの上限を8GBへ拡張できました。
（弊社の端末で上記の問題があるが、他の端末で同様な問題がないかもしれません）

> 公式のデモ版と比較しても、同様な性能でしょうか。

はい、公式のデモ版と同様な機能があります。

> また、検証環境の情報など、追加提供をお願いします。
> 　　検証環境のスペック
> 　　遅い状況のログなど

- 検証環境のスペックは下記の通りです。
Mac mini (M1, 2020) ( macOS Monterey ) 8GB RAM
- 遅い状況のログなどがありませんが、画像のアップロードには、3~5分くらいかかります。

> 以下に、ローカル画像アップロード版のデモがあるようです。こちらがどのように動作しているか（DICOMサーバーを使用していない？）、確認いただけますでしょうか。
>       　https://ohif.org/get-started
> 　　　→「Use your own data」

上記のデモ版を確認しましたが、これもDICOMサーバーで動作しています。

また、現在下記の問題があります。
① 弊社の方のビルドでローカル画像アップロードを実行する時、[RangeError :Error when trying to load and process local files: Offset is outside the bounds of the DataView]のエラーになってしまいます。
(https://drive.google.com/file/d/1XoePpMAPbWA25bCIms3zF-ZDJOwmjB89/view?usp=sharing)
https://github.com/OHIF/Viewers/issues/1856

実行した時の情報は下記の通りです。
・作業ブランチ：v3-stable 
・使用しているDCOMデータはPapayaライブラリのサンプルデータとなる　(https://github.com/rii-mango/Papaya/tree/master/tests/data/dicom)

② DICOMサーバーのReactルーターと今回のプロジェクトのReactルーターが別個になっているため、ルーターの競合になってしまいます。

**Comment by itutu-tienday** [comment]
以下、現在の検証状況を記載。

- OHIF Viewerの課題
  - dicomサーバーが必須（おそらく現在のversionでは）
    - 開発・保守面、また性能面より、dicomサーバーの導入は、課題がある。

- 上記を踏まえた、以降の対応方針
  - OHIF Viewerの検証継続 → すでに一定の調査は実施しているため、現時点では継続調査はペンディングとする想定。
  - 要件はすべて満たしていないが、現在調査済み他製品（BrainBrowser,Papaya,等）を、2023/3版では暫定で組み込む。（※要顧客調査）
  - また、OHIF Viewerの代替となるViewerの再選定を実施する。 （他のタスク優先度と調整し、着手）

**Comment by itutu-tienday** [comment]
以下を追加調査する。

- dicom server を設置せずにOHIF viewerを利用することは可能かの詳細調査
- 構成案
  - https://docs.google.com/presentation/d/1LJnGeIGOY4FwT-s2ol7XmrHW5_ZQidzQ/
    - 2-1, 2-2 の構成の実現可否について、調査

**Comment by Reactplus-Hao** [comment]
Cần điều tra phần dưới đây:

- Điều tra chi tiết xem có thể sử dụng OHIF mà ko cần cài dicom server?
- Có thể thực hiện theo sollution họ gửi 2.1 và 2.2 ko ?)
https://docs.google.com/presentation/d/1LJnGeIGOY4FwT-s2ol7XmrHW5_ZQidzQ/edit

※Note: Estimate báo cho họ xem cần khoảng bao nhiêu thời gian để điều tra, tùy vào số thời gian đấy mà họ sẽ điều chỉnh thứ tự ưu tiên cho mình
--> Bên mình est mất khoảng 2 ngày để điều tra.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
OHIF Viewersの調査結果を下記にて報告させて頂きます。
- [github](https://github.com/OHIF/Viewers/tree/v3-stable)のソースコードをクーロンすることで、 [Viewers](https://github.com/OHIF/Viewers/tree/v3-stable) のソースの上に１つのNode React Appを起動する必要がある。
- Githubのソースコードをクーロンするには、下記のコマンドを実行する。
     - yarn install
     - yarn run dev
- JSONファイルのリンクを使用して、画面上に表示できる。このリンクは、dcom serverを介せず、Optinistサーバーの方で直接に管理することを確認できた。　
- JSONファイルで読み込みの速度が早い。
（ローカル環境でAWSからJSONのURLを呼び出すことができる
https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json)
- 現在、iframeを使用して、Webを埋め込むのは、制限があって、CSSを編集したり、OHIFに何かを埋め込んだりすることはできない。
- デモ動画は下記の通りになる。

https://user-images.githubusercontent.com/87292605/231637661-14cf5af5-b0cc-4584-8640-3e87f3a52458.mov
