### ISSUE TITLE
環境固有ファイルについて

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#150]
MRIAnalysisStudioの、ディレクトリ配下の環境固有ファイルは、以下の認識であっていますでしょうか。

- BackEnd
  - /.env
  - /firebase_config.json
  - /firebase_private.json
  
- FrontEnd
  - /frontend/.env.*
    - ※deploy前にbuildされるため、動作環境ではこのファイルは存在しない。

**Comment by reactplus-thom** [comment]
File cài đặt môi trường của MRIAnalysisStudio có phải nằm dưới directory dưới đây không?

- BackEnd

/.env
/firebase_config.json
/firebase_private.json

- FrontEnd

/frontend/.env.*
(=> file này ko tồn tại trên môi trường thao tác vì nó được build trước khi deploy)

**Comment by itutu-tienday** [comment]
了解しました、ありがとうございます。
