### ISSUE TITLE
Database ViewへのImage IDの表示追加

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#151]
各画面のDatabase Viewに、Image IDの表示欄を追加する （操作性、ソート等 動作確認のしやすさ、の面から）

- 共通仕様
  - IDカラムでのソートは不要（あってもOK）

- 対象画面
  - 3-a. TreeView,  3-b. ListView
    - "Datatype" カラムと "Type" カラムの間にIDを配置
  - 4-1. Add Project,  4-2. Edit Project
    - 左ペイン
      - ![Image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/c2562f5c-a8d8-4503-883e-3feea326f245)
    - 右ペイン … "Datatype" カラムと "Type" カラムの間にIDを配置 （3-a. TreeView と同様）
  - 3-1. Image View
    - ![Image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/7c248df5-3a9b-44fe-adf2-fb2824789639)
      - 3-a. TreeView の Image View
      - 3-b. ListView の Image View
      - 4-1. Add Project の Image View
      - 4-2. Edit Project の Image View

**Comment by reactplus-thom** [comment]
Thêm cột hiển thị Image ID ở Database View của các màn hình (nhằm mục đích tăng usability, dễ thao tác...)

- Spec chung:

Không cần sort ở cột ID (nhưng có cũng không sao)

- Các màn cần xử lý

1) 3-a. TreeView, 3-b. ListView
+ Bố trí cột ID ở giữa 2 cột "Datatype" và "Type"

2) 4-1. Add Project, 4-2. Edit Project
+ Pane bên trái:

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/a3892cae-6971-4f84-8dee-024d893d55d3)


Pane bên phải: Bố trí cột ID ở giữa 2 cột "Datatype" và "Type" (giống màn 3-a. TreeView)
3) 3-1. Image View

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/9384cc13-3436-4d42-aa6b-98ab0d00ba31)

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/157
・動作確認：https://drive.google.com/file/d/1uoTBSIxJUZ-EinoQqa1jauyR3AUJ9LU3/view

**Comment by itutu-tienday** [comment]
対応ありがとうございます。
ほぼ想定通り実装が行われていますが、一部適用漏れの箇所がありましたので、対応をお願いします。

- 4-1. Add Project の Image View
- 4-2. Edit Project の Image View

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/7d9c5fe3-dbcb-4751-8dba-fca576ae922b)

**Comment by reactplus-thom** [comment]
@itutu-tienday 
こちら指摘内容の対応は終わりました。
以下でご確認お願い致します。

> ほぼ想定通り実装が行われていますが、一部適用漏れの箇所がありましたので、対応をお願いします。
> 
> 4-1. Add Project の Image View
> 4-2. Edit Project の Image View

・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/157
・動作確認：https://drive.google.com/file/d/1lXduFCn71YYE38faXWrFacoIcO07lMEZ/view?usp=drive_link

**Comment by itutu-tienday** [comment]
> ・PR：#157

こちらの動作確認では、まだ事象が解消されていない模様。
※対象のPRは上記であっているでしょうか。

**Comment by reactplus-thom** [comment]
@itutu-tienday 
申し訳ございません。ブランチを間違えました。
以下でもう一度コードをプッシュいたしましたので、ご確認いただけないでしょうか。

https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/157/files#diff-493ecd0fa99c80453e13c21346333fe015bd1ee070e2fac1cf9328a5b07ebc36R581

**Comment by itutu-tienday** [comment]
修正を確認しました。
マージ・クローズします。
