### ISSUE TITLE
Docker環境構築設定準備

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#152]
Docker環境の構築設定準備を行う。

- 準備設定ファイル
  - Dockerfile, docker-compose.yaml

- 仕様補足
  - optinistのdocker設定からのアップデートでよいが、不要なライブラリ等は削除しておく。
  - 環境固有ファイルも考慮する ( #150 )

- 希望納期
  - 6/14 - 15

**Comment by reactplus-thom** [comment]
@itutu-tienday 
こちら対応が終わりました。
以下PRにてご確認をお願い致します。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/161

**Comment by itutu-tienday** [comment]
@reactplus-thom 
以下のファイルなどが更新されていないですが、どのような状況でしょうか。

- docker-compose.yml
- Dockerfile

**Comment by reactplus-thom** [comment]
@itutu-tienday 

以下のファイルに直接更新していません。
・docker-compose.yml
・Dockerfile

その代わりに、以下のファイルを上記ファイルから以下のファイルを作成して
こちらのファイルを更新して実行する方針で対応しております。
・docker-compose.dev.yml
・Dockerfile.dev

こちら、
・docker-compose.yml
・Dockerfile
は御社の方でも使って、直接更新すると影響が与えられる恐れですが、
もし上記ファイルを使われていない場合、devのファイルから置き換えようと考えておりますが、
ご確認いただけまないでしょうか？

**Comment by ReiHashimoto** [comment]
目標

1. `docker-compose up -d`だけで起動ができる状態にする
  - `docker-compose.yaml`が必要
  - 今の`docker-compose.dev.yaml`の内容になるはず
2. 既存の`docker-compose.yaml`はtest用のサービスしかないので、`docker-compose.test.yaml`にrename
3. 開発用のコンテナ(優先度 低い→1, 2とはPRを分ける)
  - `docker-compose.dev.yaml`
    - OK: source(frontend, optinist)をvolumeにmountして、開発中のコードがコンテナに反映されるもの
    - NG: COPY optinsit /app/optinist

**Comment by ReiHashimoto** [comment]
- minicondaは従来通りインストールすること

**Comment by reactplus-thom** [comment]
Mục đích:

1. Đưa về trạng có thể khởi động chỉ bằng `docker-compose up -d`
- Cần `docker-compose.yaml`, `Dockerfile`
- Nội dung sẽ giống như `docker-compose.dev.yaml` hiện nay
2. Do file `docker-compose.yaml` hiện nay chỉ phục vụ cho test, nên sẽ đổi tên nó thành `docker-compose.test.yaml`
- Cần đối ứng là `Dockerfile-test`
3. Container dùng cho phát triển (Độ ưu tiên thấp → tách ra PR riêng với mục 1, 2)
docker-compose.dev.yaml, Dockerfile.dev
OK: mount source(frontend, optinist) thành volume, code trong quá trình phát triển sẽ được phản ánh vào container
NG: COPY optinsit /app/optinist


Process:

1. Rename docker-compose.yaml -> docker-compose.test.yaml
2. Rename docker-compose.dev.yaml -> docker-compose.yaml
3. make docker-compose.yaml available
4. PR
5. make docker-compose.test.yaml and test commands available
6. Create docker-compose.dev.yaml
7. PR

Ở từng bước, hãy check xem có bị ảnh hưởng tới các path tham chiếu hay không và sửa lại.

- Install lại miniconda về như trước.

**Comment by itutu-tienday** [comment]
@reactplus-thom

対応ありがとうございます。
`docker compose up` で、Dockerコンテナ上の MRI STUDIO が、正常に起動することを確認しました。

また以下、依頼・指摘事項を記載します。

- 依頼
  - コンテナ名（サービス名）を、"studio" としてください。
- 指摘
  - WorkflowをRUN（suite2p_file_convert）を実行したところ、以下の実行エラーが発生します。
    ```
    File "/app/.snakemake/conda/4a709c7c3335a8b7655ed2e0ab04df01_/lib/python3.9/site-packages/tifffile/tifffile.py", line 10522,
    in open self._fh = open(self._file, self._mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/app/sample_data/mouse2p_2_donotouse.tiff'  
    ```
    - サンプルデータが存在しないエラーのため、サンプルデータもdockerへ展開してください。

 @ReiHashimoto 
ざっとの確認では動作OKそうですが、Docker関連ファイルの構成などについて、レビューいただければと思います。

**Comment by reactplus-thom** [comment]
Đã confirm thấy MRI STUDIO chạy bình thường bằng `docker compose up` trên Docker container.

Tuy nhiên, vui lòng sửa thêm các phần sau:
1) Tên của container (tên service) hãy để là "studio" (cái này là yêu cầu bổ sung thêm so với hôm qua)
2) Khi chạy RUN（suite2p_file_convert）Workflow, đang bị lỗi như dưới:

File "/app/.snakemake/conda/4a709c7c3335a8b7655ed2e0ab04df01_/lib/python3.9/site-packages/tifffile/tifffile.py", line 10522,
in open self._fh = open(self._file, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/app/sample_data/mouse2p_2_donotouse.tiff'  

Đây là lỗi do không tồn tại dữ liệu sample, vì thế cần deploy cả sample data lên docker nữa nhé.

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
私からは追加の指摘なしです！
川田さんからの指摘事項も修正されましたので、approveしています

**Comment by itutu-tienday** [comment]
@reactplus-thom @ReiHashimoto 
確認・対応ありがとうございます。

現在時点版で、一旦 devleop-main へマージしました。
引き続き、残りの対応（開発版の設定準備）を、よろしくお願いします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
何点かPRへレビューコメントを入れていますので、ご確認お願いします。

またこちらの環境で、docker-compose.dev.yml を動作確認したところ、以下のエラー（optinistの起動時のエラー）が確認されています。
こちらの環境依存の問題の可能性もありますが、一度ご確認お願いします。

- コマンド
  `docker compose -f docker-compose.dev.yml up`

- ログ
  ```
  Container mrianalysisstudioformouse_docker-studio_dev-1  Created                                                0.0s
  Attaching to mrianalysisstudioformouse_docker-studio_dev-1
  mrianalysisstudioformouse_docker-studio_dev-1  | /usr/local/bin/python: can't find '__main__' module in 'main.py'
  mrianalysisstudioformouse_docker-studio_dev-1 exited with code 1
  ```

**Comment by reactplus-thom** [comment]
Khi khách hàng check trên môi trường của họ với docker-compose.dev.yml
thì bị lỗi như dưới đây (lỗi khi khởi động optinist):
- Command:
`docker compose -f docker-compose.dev.yml up`

- Log
```
Container mrianalysisstudioformouse_docker-studio_dev-1  Created                                                0.0s
Attaching to mrianalysisstudioformouse_docker-studio_dev-1
mrianalysisstudioformouse_docker-studio_dev-1  | /usr/local/bin/python: can't find '__main__' module in 'main.py'
mrianalysisstudioformouse_docker-studio_dev-1 exited with code 1
```
