### ISSUE TITLE
[3. Database] 不具合修正

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#158]
### 不具合・指摘

- [x] 1. TreeViewで、「Datatype」のカラムのツリーを開閉した場合、同階層のすべてのフォルダ（anat, dwi）が連動して開閉してしまっている。

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/162
・動作確認：https://drive.google.com/file/d/14rdhNGgAx-rOkW_lPaPT0KKsjf4WcggN/view

**Comment by itutu-tienday** [comment]
> ・PR：#162

上記PRが develop-main に向いていないようなので、確認お願いします。
