### ISSUE TITLE
Database TreeViewソート機能調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#169]
- 対応事項
  - 1. [x] TreeViewのソートのパターンが「Datatype」カラムを区切りとして切り替わることから（Sessionでのグルーピング）、以下の表示調整を行う。
        - Datatype より左側のテーブルヘッダに、以下のスタイルを設定する。
          - `font-weight: normal`
        - ※TreeView, ListView の双方への設定でOK
    
- 関連
  - #136

**Comment by reactplus-thom** [comment]
@itutu-tienday 
念のため、修正内容は以下の認識でよろしいでしょうか。

> Datatype より**右側**のテーブルヘッダに、以下のスタイルを設定する。
> font-weight: normal

![image](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/135786736/66760477-e915-4155-9da6-f0d47bfc0817)

**Comment by itutu-tienday** [comment]
@reactplus-thom 
はい、上記になります。
※Database Viewを利用している各箇所へ同じ設定を適用

**Comment by reactplus-thom** [comment]
・動作確認：https://drive.google.com/file/d/1hb80_JVWWx7iURYTVHL798ywegCLpFy9/view?usp=drive_link
