### ISSUE TITLE
ファイル整理

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#180]
- 対応内容
  - 6/16版
    - [x] 1.  ソースフォルダ直下にあるファイルの整理
      - `user_role.json`
        1. backend(optinist) frontend の両方で使用されている場合 … /resources/ へ移動（フォルダ新規作成）
        2. frontend でのみ使用されている場合 … /frontend/src/ へ移動
        3. backend(optinist) でのみ使用されている場合 … /optinist/resources/ へ移動（フォルダ新規作成）

**Comment by reactplus-thom** [comment]
Sắp xếp lại các file nằm dưới source folder
user_role.json
a. Trường hợp sử dụng cả ở 2 phía backend(optinist) frontend … Move sang /resources/ (tạo mới folder)
b. Trường hợp chỉ sử dụng ở phía frontend … Move sang /frontend/src/
c. Trường hợp chỉ sử dụng ở phía backend(optinist) … Move sang /optinist/resources/ (tạo mới folder)
