### ISSUE TITLE
[3.Database] ソート項目の実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#30]
データテーブルのソート機能が未実装。実装する。

■タスク
- [x] FrontEndでのソート・フィルタ実装の検討
  - 前提条件
    - ページングは不要（無限のスクロールでOK）
- [x] FrontEndでソート・フィルタを実装した場合の、性能検証
  - テスト条件
    - データテーブルのある各画面で、表示やソートの処理時間に、1秒/5秒 を要するデータ件数を確認する

**Comment by itutu-tienday** [comment]
3/18版で、ソートのUIが組み込まれていることを確認しました。

ただし、実際のデータのソートは動作していないようです。
→ ソートの動作も、実装済みでしょうか？

**Comment by Reactplus-Hao** [comment]
Trong source code ngày 18/03, KH đã check thấy UI của phần sort được tích hợp rồi

Tuy nhiên, có vẻ đang không thao tác sort data thực tế được
→ Bên mình cũng đã implement xong function sort chưa nhỉ?

**Comment by Reactplus-Hao** [comment]
> ただし、実際のデータのソートは動作していないようです。
→ ソートの動作も、実装済みでしょうか？

現在、ソートのUIのみ実施済みです。
ソートの動作について、APIを呼び出すことで、ソートされたデータを取得して、画面上に表示させるという認識をしていますので、
ソートの動作を実施していない状態です。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
すみません、一覧系画面のソート仕様について、初期バージョンでは、「ソートはFrontEndにて行う」という想定でおります。

画面設計書（画面設計_vx.pptx）の、画面「3. Database」の備考欄に、以下の説明を記載があります。
> 基本的に、一覧系データは「APIからは全件取得（limit/offset不要）」「FrontEndでフィルタやソートを制御」の動作とする

上記について、もし技術面で課題などある場合、お知らせください。

**Comment by Reactplus-Hao** [comment]
Cần implement fucntion sort trong table data

■Task

- [ ] Xem xét để implement function sort・filter ở phía FrontEnd

     - Điều kiện tiền đề:

            Không cần paging (Chỉ cần scroll không giới hạn là xử lý được)

- [ ] Test fucntion trong trường hợp đã implement xong function sort・filter ở phía FrontEnd

    - Điều kiện tiền đề:
            Trong các màn hình có table data, cần check xem số lượng data cần 1 giây/ 5 giây để xử lý sort và hiển thị.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
#[30](https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/30)についての対応が完了したのですが、添付のフォルダにある3つデモ動画をご確認していただけないでしょうか
https://drive.google.com/drive/folders/1vycRQCPVGSiJFICFDFiPmObYo657clvW
参考ですが、ローカル環境で1秒で400ぐらいのレコードを取得でき、5秒では1500ぐらいのレコードを取得できますが、少し不安定状態になります

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ありがとうございます。
上記の情報を参考に、顧客と仕様相談の予定です。

**Comment by emuemuJP** [comment]
@Reactplus-Hao 
> ローカル環境で1秒で400ぐらいのレコードを取得でき、5秒では1500ぐらいのレコードを取得できますが、少し不安定状態になります

このレコードの単位はどの単位でしょうか？
またListViewとTreeViewで変わりますよね？

もし可能であれば

- 200レコードの際の描画
- 400レコードの際の描画

を動画にしてもらえるとたすかります。

**Comment by Reactplus-Hao** [comment]
Lúc trước bên mình có check trên môi trường local và report cho KH là 400 bản record thì 1s vẫn ngon, dưới 1500 bản record thì 5s sẽ ngon nhưng client có vẻ hơi giật (đây là môi trường local)

---> Đơn vị record bên mình đang nói đến ở trên là gì nhỉ (ảnh, hay record của phần nào?)
Ngoài ra, ở List View và Tree View thì số lượng record load được như trên sẽ khác nhau đúng k ạ? 

Nếu được, thì nhờ bên mình quay lại video của các màn hình sau giúp họ:
- Màn hình khi load 200 record
- Màn hình khi load 400 record

**Comment by Reactplus-Hao** [comment]
@emuemuJP 

> ローカル環境で1秒で400ぐらいのレコードを取得でき、5秒では1500ぐらいのレコードを取得できますが、少し不安定状態になります

> このレコードの単位はどの単位でしょうか？

この１つのレコードは、Databaseページの１つ行に応じます。

> またListViewとTreeViewで変わりますよね？

はい、ListViewとTreeViewで変わります。
上記の報告した結果はTreeViewの結果となります。
ListViewのレコードの表示やソートの処理時間は、TreeViewの処理時間より早いです。

> もし可能であれば
> ・200レコードの際の描画
> ・400レコードの際の描画
> を動画にしてもらえるとたすかります。

・200レコードの際の描画は下記の通りです。

https://user-images.githubusercontent.com/87292605/231944828-b7131fb8-174f-42aa-a3aa-7840aeb4e9e1.mov


・405レコードの際の描画は下記の通りです。

https://user-images.githubusercontent.com/87292605/231944877-b2ecd195-9c0b-4bab-8e4b-955dd0342d17.mov


・**懸念点**：
下記の動画は、TreeViewの200レコードに対して、画像の選択・ドラッグ＆ドロップの操作がかなり遅くなります。
原因としては、ページングしていないためです。
ページングせず、全てのレコードを読み込む場合、ドラッグする時、連続的にデータをレンダリングする必要があります。

https://user-images.githubusercontent.com/87292605/231945696-92c860a2-ecdc-4372-a039-fc41587edf77.mp4

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ソートの実装について、まずざっと挙動を確認した段階ですが、以下質問を記載します。

- Sessionの右側のカラム（Dataset, Type,  ..）でソートした場合、Subject や Session のカラムも並び変わっている様ですが、これはどのようなロジックとなっていますでしょうか？
  - 想定仕様は、Sessionの右側のカラムでソートした場合は、各Session内でのソートとなるため、Session から左側のカラムは、ソートされない（デフォルトの並び）の想定のため、質問します。

**Comment by Reactplus-Hao** [comment]
Về phần xử lý sort, KH mới chỉ check qua video demo của bên mình thì họ có confirm phần sau:

- Trường hợp khi sort các column phía bên phải của cột Session（Dataset, Type, ..）, thì trình tự của cả column Subject, Session cũng bị thay đổi theo. Như này là đang theo logic như thế nào vậy ạ?
    - Spec KH mong muốn đó là: Trong trường hợp sort ở các column phía bên phải của cột Session, thì sẽ là sort trong các session với nhau thôi. Vì vậy sẽ không sort các column phía bên trái của cột Session (Sẽ để trình tự default)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> Sessionの右側のカラム（Dataset, Type, ..）でソートした場合、Subject や Session のカラムも並び変わっている様ですが、これはどのようなロジックとなっていますでしょうか？

上記の件について、現在Sessionの右側のカラム（Dataset, Type, ..）でソートした場合、そのDatasetやTypeが配属しているSubjectとSessionカラムの並びも変わっています。
例えば、Session_1の中にDataset1があり、Session_2の中にDataset2があり、Dataset1＜Dataset2の状態で、Datasetカラムを降順でソートした場合、Session_2がSession_1の上に変わっています。

> 想定仕様は、Sessionの右側のカラムでソートした場合は、各Session内でのソートとなるため、Session から左側のカラムは、ソートされない（デフォルトの並び）の想定のため、質問します。

上記のような想定であれば、修正させて頂きますが、念のため、下記の事項を確認したいです。
例えば、下記のようなレコードがあれば、
① Datasetカラムをソートしましたら、
New sessionというSession（Sessionから左側のカラム（Sessionカラムも含む）がソートされない（デフォルトの並び））がデフォルトの並びのまま表示され、anatとfuncをソートして、anatとfuncに付属しているTypeも並びも変わるという認識で合っていますでしょうか。
② Typeカラムをソートしましたら、
New sessionというSession（Sessionから左側のカラム（Sessionカラムも含む）がソートされない（デフォルトの並び））がデフォルトの並びのまま表示され、Datasetのカラムも並びも変わるという認識で合っていますでしょうか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
すみません、上の指摘について、当方の方に認識誤りがあったようです。
画面設計書では、Sessionカラムではなく、Dateカラムをソートのグループの区切りとしており、現在の実装の動作はそのようになっているようなので、仕様通りであるようです。 ※確認にお手数をおかけしました。

なお別件で、以下の修正ポイントを確認しましたので、確認と修正をお願いします。

- 各カラムのヘッダをクリックすると、「昇順>降順>デフォルト」の順でソート条件が切り替わりますが、全カラムで直前のソート条件を共有されているらしく、別カラムをクリックした際、意図しないソート順になるようです。（降順から始まるなど） 
  - こちらは、別カラムを選択した場合は、直前のソート条件はリセットするように（昇順から始める）、お願いします。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> こちらは、別カラムを選択した場合は、直前のソート条件はリセットするように（昇順から始める）、お願いします。

最新版コードで、上記が修正されていることを確認しました。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ご確認ありがとうございます。

> こちらは、別カラムを選択した場合は、直前のソート条件はリセットするように（昇順から始める）、お願いします。

念のため、上記の対応のテストエビデンスを下記にて共有させて頂きます。
・Database画面：https://drive.google.com/file/d/1IS8pwbfEYX8UR1iTOxcjWUeENwyhqV4T/view?usp=sharing
・Add/ Edit Project：https://drive.google.com/file/d/1iLLb77vW4injQ8_I-M-aq4BULTIgK5-z/view?usp=sharing
