### ISSUE TITLE
[3.Database] 行選択時の画像表示仕様の確認と調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#31]
- [x] 選択された行の画像が、表示されていない？（必ず同じ画像から表示される？）
- [x] 画像の ←→ キーでの表示ループ条件の確認 （想定仕様は「同一フォルダ内でのループ」）

**Comment by itutu-tienday** [comment]
#40 の事象のため、Viewerの表示が確認できない模様。

**Comment by Reactplus-Hao** [comment]
- Ảnh của dòng đã được chọn đang không được hiển thị（Có phải là luôn hiển thị từ cùng một ảnh giống nhau？）
- Check điều kiện loop hiển thị bằng key  ←→ trong ảnh

**Comment by itutu-tienday** [comment]
以下、issue説明欄に記載のタスクについて、状況の再確認をお願いします。

```
- 選択された行の画像が、表示されていない？（必ず同じ画像から表示される？）
- 画像の ←→ キーでの表示ループ条件の確認
```

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 

> - 画像の ←→ キーでの表示ループ条件の確認 （想定仕様は「同一フォルダ内でのループ」）

上記は、「同一sessionフォルダ内での表示ループ」の想定となります。（画面設計_vx.pptx より）
※実装に際して、技術面の課題があるなどあれば、お知らせください。

**Comment by Reactplus-Hao** [comment]
> Check điều kiện loop hiển thị bằng key ←→ trong ảnh

Về phần xử lý trên, KH mong muốn 「Có thể loop hiển thị trong cùng 1 folder session]
※ Nếu thực tế, có khó khăn gì về mặt kĩ thuật thì hãy chỉ cho họ biết

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
> 上記は、「同一sessionフォルダ内での表示ループ」の想定となります。（画面設計_vx.pptx より）

上記の対応について、対応とテスト実施が完了しました。
デモ動画を下記にて共有させて頂きますので、ご確認お願い致します。
https://drive.google.com/file/d/1yAwus91MeSPSN9XnAzIKn9lAnn51t-jV/view?usp=sharing

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ありがとうございます。 動画内の挙動で、基本的に問題ないものと思います。

なお、仕様の詳細確認のため、以下の様なテストパターンを、1件追加いただきたいと思います。

- 同一sessionフォルダ内に、複数のデータタイプ（anat の他に、func 等）のフォルダを配置し、問題なくsessionフォルダで表示ループできるかを確認する。
- フォルダ構造例 (session1フォルダ内で、image1-4 をループ表示できる) 
```
- session1
  - anat
    - image1
    - image2
  - func
    - image3
    - image4
```

**Comment by Reactplus-Hao** [comment]
KH cảm ơn bên mình đã xử lý giúp. Họ check video demo thì thấy cơ bản không có vấn đề gì.

Ngoài ra, họ muốn check chi tiết hơn về spec, nên muốn nhờ bên mình test thêm 1 pattern như dưới đây:

- Trường hợp trong cùng 1 folder session, có nhiều folder type data (ngoài anat, thì còn có func, v.v..) 
---> KH muốn mình test trong trường hợp này cũng có thể hiển thị loop trong folder session
Ví dụ cấu trúc folder sẽ như dưới đây, thì họ muốn check có thể hiển thị loop từ image1-4 trong cùng 1 folder session
```
- session1
  - anat
    - image1
    - image2
  - func
    - image3
    - image4
```

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 同一sessionフォルダ内に、複数のデータタイプ（anat の他に、func 等）のフォルダを配置し、問題なくsessionフォルダで表示ループできるかを確認する。

上記のテストパターンのテスト実施が完了して、デモ動画を下記に添付致しました。
お手数ですが、ご確認お願い致します。
・https://drive.google.com/file/d/1XXGQrj2rgiQNI8uWrdJLW5dKRrV5qmEh/view?usp=share_link
・https://drive.google.com/file/d/1Tu9-1T2hASwivd3GaUPP7dLYA2wJAoY8/view?usp=share_link
問題がなければ、ソースコードをPushさせていただきます。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
上記のデモ動画内の動作で、問題ないものと思います。
