### ISSUE TITLE
[3a. TreeView] 修正事項

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#33]
- [x] ツリーが3階層だが、現時点最新版では、4階層の想定。
- [x] ダミーの画像レコードは、同一のフォルダ内に、複数件（2件以上）登録しておいていただきたい。

**Comment by itutu-tienday** [comment]
> ダミーの画像レコードは、同一のフォルダ内に、複数件（2件以上）登録しておいていただきたい。

上記への対応を、お願いいたします。（現状は、1フォルダ内に、1件のみ（合計は2件）画像レコードが登録されている）

**Comment by Reactplus-Hao** [comment]
KH muốn nhờ bên mình đăng ký sẵn nhiều record ảnh dummy (từ 2 record trở lên) vào trong cũng folder
Hiện tại trong 1 folder, thì chỉ đang đăng ký 1 record (Tổng cộng đang có 2 record) thôi
