### ISSUE TITLE
[3-1. Image View] 修正事項

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#35]
- [x] 何度かイメージを選択すると、ダイアログが表示されない（空のダイアログがオーバーレイされる）事象が発生するケースがある。   ※この事象が発生した場合は、ESCキーを押さないと、元の画面に復帰できない。

**Comment by Reactplus-Hao** [comment]
Khi chọn ảnh nhiều lần, thì cũng có trường hợp đang không hiển thị dialog (dialog trống đang được overlay lên)
Lúc xảy ra trình trạng này, họ phải nhấn key ESC thì mới có thể quay lại màn hình ban đầu.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 何度かイメージを選択すると、ダイアログが表示されない（空のダイアログがオーバーレイされる）事象

すみませんが、上記の事象の再現をもう少し記入して頂けますでしょうか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 

イメージを補足添付します。
- ただし現在（3/28）は、事象は再現していません。
  -  関連issue ( #40 ) にて、合わせて対処されていますでしょうか？



![Image](https://user-images.githubusercontent.com/122338895/228119294-c3459ebc-55fe-4b09-a208-c673678b386f.png)

**Comment by Reactplus-Hao** [comment]
KH gửi thêm hình dung về bug của ticket này theo như ảnh dưới đây:

Tuy nhiên, hôm nay (28/3) họ check lại thì không tái hiện được bug nữa.
Liệu có phải bên mình đã fix cùng với issue  ( https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/40 ) rồi có phải không?

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> ただし現在（3/28）は、事象は再現していません。

「何度かイメージを選択すると、ダイアログが表示されない」という不具合を修正して、昨日ソースコードをPush致しましたので、
現在（3/28）は、事象が発生していないことです。
