### ISSUE TITLE
[4-1. Add Project] [4-2. Edit Project] 実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#37]
- [x] 画面仕様の、全体チェック
  - [x] 画面がポップアップ形式でない
  - [x] 画像のドラッグ＆ドロップの正しい仕様
  - [x] OK/Cancelボタンがない

**Comment by Reactplus-Hao** [comment]
Add ProjectとEdit Project画面がポップアップ形式ではなく、画面の形式で対応していますが、
ポップアップのような機能を確保できます。

**Comment by itutu-tienday** [comment]
基本的な実装の完了を確認。
細かな修正事項は、別issueにて対応。

**Comment by itutu-tienday** [comment]
以下、追加修正事項を追加。

- [  ] "ADD WITHIN FACTOR" ボタンを、"Between factor"毎に配置してください。
![Image](https://user-images.githubusercontent.com/122338895/226284108-77aec859-e87e-42f6-a830-0515d5339544.png)

**Comment by Reactplus-Hao** [comment]
Nhờ bên mình sửa thêm phần dưới đây:
Hãy thêm button "ADD WITHIN FACTOR" vào trong mỗi phần "Between factor"
