### ISSUE TITLE
[共通]各ページでブラウザリロードすると404となる

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#38]
各ページ（ログイン画面以降、全ページ？）でブラウザリロードすると、404エラーが発生する模様。

404エラーの際、以下のJSONの応答が返る。

```
{
  detail: "Not Found"
}

```
※FastAPI配下にFrontEndのコンテンツを格納していることが原因か。
　技術的対応方法を提案をいただきたい。

**Comment by Reactplus-Hao** [comment]
Khi reload các page (Tất cả các màn hình sau khi đã login) thì đang bị lỗi 404
Khi bị lỗi 404, thì trả về response JSON như dưới đây:

{
  detail: "Not Found"
}

※ Họ nghĩ nguyên nhân có thể do content FrontEnd đang được lưu trữ trong FastAPI
　Nhờ bên mình suggest họ cách xử lý

**Comment by itutu-tienday** [comment]
以下、対応方法の案を記載。

- FrontEndのURLは、「http://xxxx/front/yyyy」の様に、URLに特定のキーワード（左記の例では front）を含めることで、今後URLの追加や変更があっても、BackEnd側の設定メンテナンスを不要とできるのではないか。

上記の検証をお願いいたします。
また他にベターな手法があれば、提案いただければと思います。

**Comment by Reactplus-Hao** [comment]
KH đề xuất xử lý theo như dưới đây:

URL ở phía FrontEnd thì sẽ để kiểu 「[http://xxxx/front/yyyy」 , đó là bao gồm keyword đặc biệt vào trong URL (Chẳng hạn như từ front) 
---> Như vậy, về sau họ có thay đổi hay add URL, thì cũng sẽ không cần maintenance setting bên phía BackEnd
Bên mình có thể xem xét cách xử lý trên được không?

Ngoài ra, nếu bên mình có cách xử lý khác tốt hơn thì hãy đề xuất cho họ biết.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 各ページでブラウザリロードすると404となる

- **上記のエラーの原因：** 
ページをリロードする時、デフォルトではブラウザが事前にサーバーへリクエストを送信しています。
そのため、ページをリロードした時に、リロードしたページと該当するURLを見つけませんので、404エラーになってしまいます。

- **対応方法：**
BE側の未定義のエンドポイントへの全てのリクエストを処理するためのIndex関数を作成して、FE側のindex.htmlページを返します。
その時、FE側で任意（BE側のURLに重複しない）のURLでも設定することができます。

```
@app.get("/{path}")
async def index(request: Request):
    return await root(request)
```

上記の対応方法を踏んで、下記のご提案方法の対応が不要になるかと思います。

> FrontEndのURLは、「[http://xxxx/front/yyyy」の様に、URLに特定のキーワード（左記の例では](http://xxxx/front/yyyy%E3%80%8D%E3%81%AE%E6%A7%98%E3%81%AB%E3%80%81URL%E3%81%AB%E7%89%B9%E5%AE%9A%E3%81%AE%E3%82%AD%E3%83%BC%E3%83%AF%E3%83%BC%E3%83%89%EF%BC%88%E5%B7%A6%E8%A8%98%E3%81%AE%E4%BE%8B%E3%81%A7%E3%81%AF) front）を含めることで、今後URLの追加や変更があっても、BackEnd側の設定メンテナンスを不要とできるのではないか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
上記、了解しました。

なお、以下の様なURLをリロードすると、やはり404が発生するようです。
今少し、確認をお願いいたします。

http://localhost:8000/project/new-project  (Add Project)
http://localhost:8000/project/new-project?id=1 (Edit Project)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> http://localhost:8000/project/new-project (Add Project)
http://localhost:8000/project/new-project?id=1 (Edit Project)

上記の２つのURLが違っているようです。
Add ProjectとEdit Projectページは、Projectsページから遷移しているので、
下記のようなURLでご確認お願い出来ますでしょうか。

http://localhost:8000/projects/new-project (Add Project)
http://localhost:8000/projects/new-project?id=1 (Edit Project)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> なお、以下の様なURLをリロードすると、やはり404が発生するようです。
> http://localhost:8000/project/new-project (Add Project)
> http://localhost:8000/project/new-project?id=1 (Edit Project)

上記の件について、修正とテスト実施が完了しました。
お手数ですが、下記のようなURLでご確認お願い出来ますでしょうか。
http://localhost:8000/projects/new-project (Add Project)
http://localhost:8000/projects/new-project?id=1 (Edit Project)

**Comment by itutu-tienday** [comment]
修正済みを確認しました。
当件クローズします。
