### ISSUE TITLE
[3b. ListView] 修正事項

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#39]
- [x] TreeとListの切り替えはのリンクは、「Tree / List」としてください。（「Tree / Image」となっている）
- [x] Subject, Session, へテストデータを設定してください。

**Comment by Reactplus-Hao** [comment]
- Hãy để text link switch giữa Tree View và List View là 「Tree / List」（Hiện tại bên mình đang để là「Tree / Image」）
-  Hãy set test data vào phần Subject, Session
