### ISSUE TITLE
[3-1. Image View] Viewerが表示されない

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#40]
3/18版で、TreeView と ListView の画面で、画像レコードを選択しても、Viewerが表示されない事象が発生している。

■備考
- 事象は、#35 に記載の内容に同様（何もない画面が表示される）
- ブラウザキャッシュをクリアしても、事象は発生する。

**Comment by Reactplus-Hao** [comment]
Trong bản source code ngày 18/3, KH check thì thấy có issue: Trong màn hình TreeView và ListView cho dùng chọn record ảnh thì Viewer vẫn đang không được hiển thị lên.

■Note

Issue này cũng giống với nội dung issue trong https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/35 
(Màn Image View đang hiển thị trống trơn)
Cho dù họ clear cache browser thì cũng vẫn xảy ra issue này

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 

Viewerについて、3/21版で、以下の問題点を確認しています。 状況確認をお願いいたします。

1. 画像が白紙
![Image](https://user-images.githubusercontent.com/122338895/226564883-f69106fe-bf93-43ab-bce3-268145a78f2f.png)


2. 2つの画像が1つのViewer内に表示されている
![Image](https://user-images.githubusercontent.com/122338895/226564893-ffd1de93-0c3e-4edb-81cc-c5198258054c.png)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
> 画像が白紙

上記のエラーの原因としては、画像ファイルのサイズが大きいため、読み込み時間がかかって、画像が白紙になっています。

> 2つの画像が1つのViewer内に表示されている

上記のエラーの原因としては、Next「＞」やBack「＜」のボタンのクリックスピードが速すぎましたら、ライブラリの方で同時に２つの画像を実行して、1つのViewer内に表示されてしまいます。

→ **解決方法**：画像の読み込み中であれば、読み込み中のアイコンを表示させるように対応しました。

下記の動画は、弊社の環境で確認したエビデンスです。
最新のソースコードを作業ブランチへPushしましたので、ご確認お願い致します。


https://user-images.githubusercontent.com/87292605/226786618-d71a1d57-b9d6-4012-93f3-f6b12fcf981f.mp4

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ありがとうございます。
上記の修正内容にて、問題ないものと思います。
