### ISSUE TITLE
[4-1. Add Project] [4-2. Edit Project] 修正事項

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#41]
- [x] 左側ペインへの画像ドラッグ＆ドロップ時、ドロップ可能な領域を、ハイライトしていただきたい。
- [x] ADD ボタンを、OKボタンとする（ADDだと、EDIT時の画面で、文言が適切でないため）

**Comment by Reactplus-Hao** [comment]
- Khi drag&drop ảnh vào mục bên trái, thì họ muốn sẽ để highlight vùng có thể drop 
- Button ADD sẽ đổi thành button OK（Vì nếu để là ADD, thì trong màn hình EDIT sẽ không phù hợp cho lắm)
