### ISSUE TITLE
Firebase処理周り動作確認

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#45]
Firebase処理周りの実装の動作確認を行う。

- 準備
  - Firebase処理周りが実際に動作するアプリケーションのバージョン（ブランチ）を用意する。
  - Firebase環境でのデータ確認手順を用意（テキスト）する。

※この対応は、レビュアー（Araya）側での動作確認を想定しており、詳細なテストは、別途テスターによる実施を想定。

**Comment by Reactplus-Hao** [comment]
Tiến hành check hoạt động của phần implement liên quan đến xử lý Firebase

- Chuẩn bị
      ・Chuẩn bị version (branch) của app để hoạt động thực tế phần xử lý Firebase
　　・Chuẩn bị trình tự check data trong môi trường Firebase (Trình tự bằng text)

※ Dự định phần này để người Viewer (bên Araya) check hoạt động, còn test chi tiết sẽ do tester khác thực hiện.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> Firebase処理周りが実際に動作するアプリケーションのバージョン（ブランチ）を用意する。

Firebase処理について、実際に動作するアプリケーションのバージョン（ブランチ）を作成して、設定手順書をGitに添付しておきました。
・ブランチ：https://github.com/arayabrain/MRIAnalysisStudioforMouse/tree/feature/firebase
（このブランチはfeature/dashboardブランチからチェックアウトして、作成されています）
・設定手順書：https://github.com/arayabrain/MRIAnalysisStudioforMouse/tree/feature/firebase#installation

> Firebase環境でのデータ確認手順を用意（テキスト）する。

Firebase環境でのデータ確認手順も作成致しましたので、下記にて添付させて頂きます。
・[Firebase環境でのデータ確認手順.docx](https://github.com/arayabrain/MRIAnalysisStudioforMouse/files/11217944/Firebase.docx)


feature/dashboardをチェックアウトして、Gitの設定手順書のように再度設定して実行することで、実際の動作を確認できます。
お手数ですが、ご確認お願い致します。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ありがとうございます、いただいた設定手順書で、最新版（feature/dashboard）で、ログインを行えることを確認しました。

なお以下、仕様について質問です。
- ユーザー情報（メールアドレス以外（権限、等）の情報）は、Firebase上、どの場所に格納されていますでしょうか。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
現在、ユーザー情報（メールアドレス以外（権限、等）の情報）は、ユーザーのCustom claimsに格納されています。
Custom claimsとは、Firebase Authenticationの機能であり、ユーザー情報（メールアドレス以外（権限、等）の情報）を格納するように使用されます。
しかし、ユーザー情報（メールアドレス以外の情報）はFirebaseのconsoleで直接に確認できませんが、FirebaseはSDKを介して、Custom claimsへアクセスすることをサポートできます。
ユーザー情報（メールアドレス以外の情報）の格納位置を確認する要望があれば、確認するためのツールを作成致しますので、
ご連絡お願いいたします。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
ありがとうございます。
ひとまず仕様について、了解いたしました。

Custom claims へのアクセスツールを用意するかは、要望が挙がった際、改めてご相談ます
