### ISSUE TITLE
WORKFLOW内のAlgorithmブロックが ドラッグに追従してしまう

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#49]
以下と同内容の修正を適用する。

- https://github.com/oist/optinist/issues/438

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 以下と同内容の修正を適用する。
> https://github.com/oist/optinist/issues/438

上記の対応が完了して、下記のPRを作成致していますので、ご確認お願い致します。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/53

また、テスト実施について、現在Workflowページがまだ完了していないため、テストできません。
Workflowページが完了した後、このタスクをテスト実施させて頂きます。

**Comment by reactplus-thom** [comment]
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/53
・テストパータン：https://docs.google.com/spreadsheets/d/1PEqNtSBl2zzejDMqZ7PDw0Cz6OqZD8HYOkJ9nZqW318/edit?usp=drive_link
・動作確認：https://drive.google.com/file/d/1bDq5pSaX84VUaORHYW6fKNiLwo2ovGTy/view?usp=drive_link
