### ISSUE TITLE
BackEnd API向けFirebase認証サンプル＆独自簡易Tokenの実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#51]
BackEnd API向けの、Firebaseユーザー認証情報の受け渡しのサンプルコードを作成する。
※BackEnd API の開発者（外部）へ、サンプルコードを提供する目的。

- 想定作成物
  - [x] サンプルコード
    - FrontEndからBackEndへのユーザー認証情報のデータ送信のサンプル
      - ※HTTPヘッダに認証情報を載せることを想定しますが（JWT等）、実装方式についてご提案をお願いしたく思います。
    - BackEnd でのユーザー認証情報の取得（パース）処理のサンプル
      - 受け渡すユーザー情報は、以下を想定。
        - ユーザーID、所属(Lab)、ユーザー名(Name)、権限(Role)
        - ※ユーザーIDの書式について、情報提供をお願いします。
  - [x] 独自簡易Tokenの実装

### 課題

- [x] 1. Firebase Token処理の復元
    - 5/23の修正で、認証モジュール（deps.pyなど）から、それまで組み込まれていた Firebase Token処理が、削除されている様です。
    - 独自tokenは、以下で記載しているように暫定機能のため、Firebase Token処理のコードは残しておいていただきたいと思います。
      - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1545134432
    - deps.py 内の token検査処理は、フラグ変数の切り替えで、Firebase token OR 独自token を切り替えられるようにしておいていただければと思います。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
BackEnd API向けFB認証サンプルを作成して、下記にて共有させて頂きます。

- **FrontEndからBackEndへのユーザー認証情報のデータ送信のサンプル**
JWTでHTTPヘッダに認証情報を載せていますので、実装方式は下記の通りとなります。
    - JWT取得：
         - ユーザーがログインに成功した時、Firebaseの方が１つのJWTを生成して、クライアント側へ送信する。
         - クライアント側では、次の各リクエストで使用するために、JWTがlocalStorage又はクッキーに保存される。

   - JWTの使用方法:
      - サーバーへリクエストを送信するたびに、クライアント側はAuthorizationヘッダーに含まれるJWTを送信する必要がある。
      - サーバー側では、リクエストを処理する前に、JWTをチェックして、ユーザーを認証する。

  - JWTを使用しているリクエストの例:
```
GET /auth/me HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
この例で、JWTは"Bearer {token}"という値として、Authorizationヘッダーに送信されている。
サーバー側は、リクエストを処理する前に、Firebase Admin SDKを使用して、そのJWTをチェックして、ユーザーを認証する。

- BackEnd でのユーザー認証情報の取得（パース）処理のサンプル：
     - ユーザーIDの書式について:
        - 基本的は、Firebase側は新しいユーザーに対して自動的に任意なユーザーIDを作成している。
        そのユーザーIDのデフォルト書式は、長さが28桁であり、a-z, A-Z, 0-9という文字と`-_`の記号のみ含む。
        - しかし、設定したいユーザーIDをFirebase Admin SDKのCreate user関数に渡すことで、新しいユーザーに対してユーザーIDを指定できる。
        指定するユーザーIDの書式は、1〜128桁の文字列であり、a-z, A-Z, 0-9という文字と`-_`の記号のみ含む。
   -  Firebase とやり取りするサンプル コードを.ipynb (Jupyter Notebooks)形式で作成して、Githubの下記PRにPushしました。
  お手数ですが、ご確認お願い致します。
        - PRリンク: https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/57
             - ブランチ名: `add-firebase-sample-code`

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
サンプルの ipynb ファイルを確認しまして、以下質問事項を記載します。

- ipynb ファイル中の、どの部分が、「BackEnd でのユーザー認証情報の取得（パース）処理のサンプル」に相当しているでしょうか？
  - ipynb ファイル内には、firebase の User data を操作するサンプルコードが記載されているようですが、今回backendで組み込む必要がある、frontendから受信したJWTのチェック処理がない様に思われます。
- また上記のJWTチェック処理は、どのようなタイミングで実施すべきか（通信の都度 or 一定間隔 or etc）の参考情報を、共有いただければと思います。
- 現在のfrontendの実装では、ユーザーIDは、fireabaseのデフォルト（28桁）でしょうか。
- また前提情報が不足していましたが、今回backendは、frontendとは別ドメイン（クロスドメイン）となると想定されます。
  - 上記クロスドメイン間を考慮した、JWT受け渡しのサンプルについて、共有いただきたいと思います。

**Comment by Reactplus-Hao** [comment]
KH đã check file `ipynb` trong sample, thì có 1 số confirm dưới đây:

- Phần nào trong file `ipynb` thì tương ứng với sample xử lý nhận thông tin authen user (Parse) ở BackEnd vậy ạ?
   - Có vẻ như trong file ipynb có mô tả sample code để thao tác User data trong firebase. Vậy thì lần này chỉ cần tích hợp ở phía Backend, và không cần xử lý Parse・Check JWT đã nhận từ frontend có phải không nhỉ?
- Ngoài ra, phần xử lý check JWT thì nên thực hiện ở thời điểm nào (Ở mỗi lần truyền tin hay trong 1 khoảng thời gian cố định nào đó, v.v..)
- Hiện tại trong phần xử lý của frontend, thì User ID đang để default trong firebase (28 kí tự) có phải không?
- Ngoài ra, KH bổ sung thêm thông tin tiền đề đó là: Họ dự định lần này Backend sẽ có domain khác  (Cross domain) so với frontend 
   - Bên mình có thể share cho họ sample truyền và nhận JWT giữa các cross domain ở trên được không?

**Comment by itutu-tienday** [comment]
当件について、以下追加の質問事項を記載します。

#### トークンのパースのサンプルコードについて

> 現在、IDトークンを認証するサンプルは下記の通りです。
> Frontendから送信したJWTを受け取った時、Backend側でauth.verify_id_token()の関数でJWTをパース・チェックしています。

上記のコメントをいただいていますが、上記のサンプルコードは Frontendから送信したJWT のパースではなく、FirebaseへのSingIn のレスポンスのトークンのパースではないでしょうか？
上記について、Frontendから送信されたJWT（HTTPリクエストヘッダのAuthorization）をパースするサンプルコードも、追加していただけますでしょうか。

#### ユーザーIDを直接リクエストヘッダに乗せる方式について

現在実装いただいているコード（Authorization ヘッダにJWTを乗せる）で、基本的に仕様はOKと想定していますが、
ここで初期リリース時に、外部API側の実装をさらに簡素化することを想定し、以下の様な仕様を検討しています。
技術的に問題がないかなど、コメントをお願いします。

- 方式
  - ログイン成功以降、バックエンドへのリクエストヘッダに、JWTトークン（Authorization）と合わせて、ユーザーID（UIDなど）を乗せる。
- 目的
  - バックエンドのIDチェック処理を簡素化する目的。（IDを直接バックエンドへ渡し、firebaseへの問い合わせを省略する）
- 注意点
  - セキュリティの低下
- リクエストヘッダ例
  ```
  GET /auth/me HTTP/1.1
  Host: localhost:8000
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  UID: HAnY63BeqyQqjvun4BuYcjdl80A3
  ```

**Comment by Reactplus-Hao** [comment]
KH có thêm 1 vài confirm nhờ bên mình check giúp.
**Về phần sample code của Parse token**

> Khi đã nhận được JWT từ FE gửi, BE sẽ xử lý parse, check JWT bằng hàm auth.verify_id_token()
> ```
> # Sign in with email and password to retrive ID tokens
> res = pb.auth().sign_in_with_email_and_password(**user_data)
> 
> decoded_token = auth.verify_id_token(res['idToken'])
> ```

Phần sample code ở trên không phải là Parse của JWT đã nhận từ Frontend, mà là Parse của token response của SignIn đến Firebase có phải không ạ?
Nhờ bên mình gửi cho KH sample code mà thực hiện Parse JWT đã nhận từ Frontend (Authorization trong HTTP request header) được không?

**Về cách đặt User ID vào trực tiếp vào request header**

Hiện tại, với code bên mình đang làm (Đó là đặt JWT vào trong Authorization header) thì về spec không có vấn đề gì.
Tuy nhiên, KH đang xem xét khi release lần đầu tiên thì họ định sẽ đơn giản hoá phần implement của phía API bên ngoài, nên đang suy nghĩ cách dưới đây.
Nhờ bên mình check giúp xem về mặt kĩ thuật thì có vấn đề gì không?

- Cách đặt 
    - Sau khi login thành công, thì sẽ đặt cả JWT token (Authorization) và User ID (UID, v.v..) vào trong Request header tới Backend
- Mục đích
   - Để làm cho phần xử lý check ID của Backend đơn giản hơn（Truyền trực tiếp ID đến Backend, và bỏ qua truy vấn đến Firebase）
- Điểm chú ý
   - Làm giảm security
- Ví dụ về Request header
```
GET /auth/me HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
UID: HAnY63BeqyQqjvun4BuYcjdl80A3
```

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ご質問を下記にて回答させていただきます。

**トークンのパースのサンプルコードについて**

> 上記について、Frontendから送信されたJWT（HTTPリクエストヘッダのAuthorization）をパースするサンプルコードも、追加していただけますでしょうか。

Frontendから送信されたJWT（HTTPリクエストヘッダのAuthorization）をパースするサンプルコードは、[deps.py](https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/9ff6b383f60e70f4c710017e27c6ebbc53d1c758/backend/deps.py#L9)ファイルに配置しています。
サンプルコードは下記の通りです。
```
async def get_current_user(
    res: Response,
    credential: HTTPAuthorizationCredentials = Depends(HTTPBearer(auto_error=False)),
):
    if credential is None:
        raise HTTPException(…)
    try:
        user = auth.verify_id_token(credential.credentials) # JWT from FE is credential.credentials
    except Exception as err:
        raise HTTPException(…)
    user =  await read_user(user_id=user['uid'])
    return user.dict()
```

上記の件数は、Frontendがユーザー認証を必要とするBackend APIへリクエストを送信するたびに呼び出されています。
Frontendから送信されたJWT（HTTPリクエストヘッダのAuthorization）は、credential.credentialsの値を介して、Backend側で取得されています。

**ユーザーIDを直接リクエストヘッダに乗せる方式について**

> - 方式
>     - ログイン成功以降、バックエンドへのリクエストヘッダに、JWTトークン（Authorization）と合わせて、ユーザーID（UIDなど）を乗せる。

上記の方式について、技術的に対応できると思います。
なお、目的は、ユーザーを認証するたびにfirebaseへの問い合わせを省略することであれば、下記の方式を提案させていただきます。
- セキュリティを確保しながら、JWT を手動でエンコードおよびデコードする
- ユーザーがログインする時に、Backend側がUIDを暗号化して、FrontendへJWTを返す
- バックエンドへのリクエストヘッダに、ユーザーID（UIDなど)を乗せることは不要で、Frontend側がそのJWTのみ使用して、検証する
ご検討よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
**トークンのパースのサンプルコードについて**

ご回答内容について、了解しました。

**ユーザーIDを直接リクエストヘッダに乗せる方式について**

バックエンドへは、毎回ユーザー識別情報を通知する必要があるのですが（ユーザー毎に、アクセス対象となるDBデータが切り替わるため）、ご提案内容では、対応可能でしょうか？

> セキュリティを確保しながら、JWT を手動でエンコードおよびデコードする

上記の方式で、対応可能そうでしょうか？
もし対応可能である場合、サンプルコード（BackEndでのJWTのデコード処理？）を、提供いただければと思います。

**Comment by Reactplus-Hao** [comment]
**Về phần sample code của Parse token**

> Như đã đề cập bên trên, code thực hiện parse JWT từ frontend được thực hiện ở file deps.py:
> Hàm trên được gọi mỗi khi frontend gửi requests tới các API Backend mà yêu cầu xác thực người dùng.
> JWT (Authorization trong HTTP request header) do frontend gửi được Backend nhận qua giá trị credential.credentials

KH đã hiểu nội dung bên mình giải thích rồi.

**Về cách đặt User ID vào trực tiếp vào request header**

> Nếu mục đích KH bỏ qua truy vấn đến Firebase mỗi lần xác thực người dùng, bên mình có suggest là encode và decode JWT thủ công mà vẫn đảm bảo được security. Khi đó, BE sẽ mã hóa UID khi user đăng nhập và trả về JWT cho FE, FE sẽ chỉ cần dùng JWT đó để xác thực mà không cần gửi kèm UID trong requests header.

Bên KH vẫn cần thông báo thông tin định danh user mỗi lần đến BE (Vì data DB để access sẽ được chuyển đổi theo mỗi user). Vậy thì có thể thực hiện theo hướng bên mình đã suggest ở trên không?

>Thực hiện encode và decode JWT thủ công mà vẫn đảm bảo được security

Có thể xử lý theo cách trên được không?
Nếu có thể thực hiện được, thì bên mình có thể cung cấp sample code (Chẳng hạn như xử lý decode JWT ở phía BE) có được không?

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> 「バックエンドへは、毎回ユーザー識別情報を通知する」とは、バックエンドの方がJWTからユーザーIDを取得できるという認識で合っていますでしょうか。

はい、上記の内容となります。
※「フロントエンドから、バックエンドへは、毎回ユーザー識別情報を通知する」となります。

いただいたサンプルで、こちらでも動作を確認してみます。

**Comment by itutu-tienday** [comment]
なお JWTのparseにいて、以下の様な情報もありましたが、この処理はあまり適切ではないでしょうか？
※外部URLへアクセスしているので、firebaseへアクセスする（auth.verify_id_token）のと、大差はないのかもしれません。

https://stackoverflow.com/questions/69319437/decode-firebase-jwt-in-python-using-pyjwt

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> なお JWTのparseについて、以下の様な情報もありましたが、この処理はあまり適切ではないでしょうか？
> ※外部URLへアクセスしているので、firebaseへアクセスする（auth.verify_id_token）のと、大差はないのかもしれません。

上記の処理もfirebase_adminライブラリのauth.verify_id_token関数にパッケージ化されているので、Firebaseへ問い合わせる必要があります。

> 目的：バックエンドのIDチェック処理を簡素化する目的。（IDを直接バックエンドへ渡し、firebaseへの問い合わせを省略する）

上記の目的であれば、上記の処理は適切ではないかと思います。

**Comment by itutu-tienday** [comment]
回答ありがとうございます。了解しました。

ここまでの情報を踏まえて、以下ご提案内容の実装を、依頼したいと思います。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1524675830

※firebaseのauth.verify_id_token と重複した機能とも思われますが、初期リリース時点ではtokenチェックを簡素化する目的で、組み込む想定です。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> ここまでの情報を踏まえて、以下ご提案内容の実装を、依頼したいと思います。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1524675830

上記の提案内容の実装は、firebaseへの問い合わせを省略する実装でしょうかね。
この方法で実装すれば、[#73](https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/73#issuecomment-1541587836)の実装が実現できません。
（[#73](https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/73#issuecomment-1541587836) の実装は、firebaseへ問い合わせる実装となるためです。）
それでは、どのIssueを優先に対応する必要でしょうか。

**Comment by itutu-tienday** [comment]
ご指摘について、了解しました。

> 上記の提案内容の実装は、firebaseへの問い合わせを省略する実装でしょうかね。

- まず、この #51 の対応は、暫定的な対応として想定しています。
  - 外部のAPI開発会社に、firebaseを利用せずに簡易に user_id を取得する Interface を、提供する目的です。
- 当システムの標準機能としては、 #73 の機能を想定しています。
- 以下で記載しているように、ヘッダにfirebaseのtokenと#51 のtokenを 並べて設定すると想定しています。
  - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1521032559
- 2023/5-6 月の、API開発会社 のシステムとの結合の時点では、開発会社には #51 の機能を利用してもらい、初回リリースのあと、#73 の機能を取り込む段取りで、考えています。

> また、上記の提案内容で実装すれば、下記の処理が必要でしょうか。

- 上記のように、#51 は簡易的な機能として想定しているため、有効期限チェックなどの細かな機能は、不要でOKです。

--

上記の想定となりますが、他 不明点があれば、お伝え下さい。
また対応予定工数を、お知らせいただければと思います。（対応工数が大きそうであれば、対応方針を調整します）

**Comment by Reactplus-Hao** [comment]
- Trước hết, phần xử lý của task 51 này chỉ là xử lý tạm thời thôi
     - Mục đích là để cung cấp Interface cho cty API để họ có thể get user_id đơn giản mà không cần dùng đến Firebase
- Còn function tiêu chuẩn của hệ thống này thì chính là function của task 73 
- Họ dự định là sẽ đặt token của Firebase và token của task 51 vào trong header
     - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1521032559
- Trong thời điểm tích hợp với hệ thống của bên API (Khoảng từ tháng 5-6) thì sẽ thực hiện function của task 51 này, và sau khi release lần đầu xong thì sẽ tích hợp function của task 73

> KH có yêu cầu về thời gian hết hạn của access token, refresh token, và refresh token có bị hết hạn khi user thay đổi email, password không?

- Vì task 51 này là function đơn giản, nên không cần các function cụ thể check thời hạn hiệu lực
--

Họ dự định sẽ xử lý như trên, nếu như bên mình có chỗ nào chưa rõ thì hãy báo họ biết
Ngoài ra, nhờ bên mình báo cho họ biết effort xử lý của 1 task này. (Để nếu mất nhiều thời gian xử lý thì họ sẽ điều chỉnh sau)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
独自簡易Tokenの実装の工数は1日かかる見込みです。
今日から対応させて頂きます。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 方式2-2. ログイン時に取得されたユーザー情報をToken化し、リクエストヘッダに乗せる方式

上記の方式で対応して、テスト実施が完了しました。
リクエストヘッダーのエビデンスは下記の通りです。
<img width="1216" alt="Screen Shot 2023-05-23 at 16 32 05" src="https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/87292605/9c4627a2-1c36-4093-8bbb-c7113b28ddee">

> FEからBEへ独自Tokenを毎回送り、BE側でtokenからuser_idを抽出できれば、OKです。

BE側でtokenからuser_idを抽出する方法について、[以前共有したサンプルコード](https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51#issuecomment-1535888842)のように対応することでuser_idを抽出できますので、ご確認お願い致します。

> - サンプルコード（BackEndでのJWTのデコード処理)は下記のとおりです。
>     - この方式で、ユーザーがログインに成功するたびに、バックエンド側がjwt.encode関数を利用して、JWTを作成してから、そのJWTをフロントエンドへ返します。
>     - フロントエンド側がそのJWTをリクエストヘッダに乗せた時、バックエンド側がjwt.decode関数でJWTをデコードして、データ（ユーザーIDなど）を受けます。
> ```
> >>> from jose import jwt
> >>> SECRET_KEY = 'J1$GpU6mExS^&v0mJl#ZoP!+2N5%9Yq*'
> >>> token_data = {
> ...     'uid': 'fab0ea37ee084db48bcdcdced114',
> ...     # other data
> ... }
> >>> encoded_jwt = jwt.encode(token_data, SECRET_KEY, algorithm='HS256') # encode data
> >>> encoded_jwt
> 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJmYWIwZWEzN2VlMDg0ZGI0OGJjZGNkY2VkMTE0In0.rMhTYk0uueA1zp_wOXhRpTUkE4EpNdcQ1uEZ4Xf4NYQ'
> >>> jwt.decode(encoded_jwt, SECRET_KEY, algorithms=['HS256']) # decode data
> {'uid': 'fab0ea37ee084db48bcdcdced114'}
> 
> ```

**Comment by itutu-tienday** [comment]
ありがとうございます。

なおこちらで動作確認したところ、ヘッダ情報の追加（ExToken）は確認できたのですが、添付画像の様に、undefinedとなっているようです。

- 動作確認手順
  1. 最新版コードを取得（feature/dashboard） 
  2. SingIn画面から、通常のログイン
  3. Dashboard画面を表示、ブラウザのdevtoolで通信データを確認

上記について、ご確認をお願いします。

![スクリーンショット 2023-05-23 190548](https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/24b56f58-5fcb-4fd7-a60d-9c645f44ab2a)

**Comment by itutu-tienday** [comment]
当件について、プログラムの動作は問題ないと思われますが、コードの構成について、調整をいただきたいと思います。
当issue に記載の以下の項目への対応を、お願いします。

-  1. Firebase Token処理の復元

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> Firebase Token処理の復元
> deps.py 内の token検査処理は、フラグ変数の切り替えで、Firebase token OR 独自token を切り替えられるようにしておいていただければと思います。

- 上記の件について、対応完了して、下記のPRを作成致しました。ご確認お願い致します。
     - https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/102  
- Firebase token OR 独自token を切り替えられるように、.envファイルのUSE_FIREBASE_TOKEN環境変数で設定する必要があります。
     - USE_FIREBASE_TOKENをTrueに設定した場合、Firebase tokenの使用になります。
     - USE_FIREBASE_TOKENをFalseに設定した場合、 独自tokenの使用になります。

**Comment by itutu-tienday** [comment]
ありがとうございます。
以下、確認結果を記載します。

- コード修正内容は、想定する対応が行われていると思います。
- 動作について、
  1. USE_FIREBASE_TOKENをTrueとした場合、正常に動作している（ログインできる）ようです。
  2.USE_FIREBASE_TOKENをFalseとした場合、 正常に動作していない（ログインできない）ようです。
      - http://localhost:8000/auth/me で、401 が返されている。
      - 通信ログからは、FEから ExToken の情報が送信されていない？ ようにも見える

そちらの環境では、上記は正常に動作している（）

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> USE_FIREBASE_TOKENをFalseとした場合、 正常に動作していない（ログインできない）ようです。

弊社の環境で確認したところ、正常に動作しています。
上記の件について、作業ブランチにFEのソースコードが含まれていないためと思います。
FEのソースコードをマージしましたので、最新のソースコードで確認していただけますでしょうか。
