### ISSUE TITLE
[5-1-1. Alignment] Alignmentダイアログ実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#56]
5-1-1. Alignmentダイアログ を実装する。

■設計資料
- 画面設計_v9_under-editing.pptx
  - https://drive.google.com/drive/folders/1ysYtYnQrYTyFBNAAbDcyQ8MalBwZdLi4
    - 画面設計_v9_under-editing.pptx
      - P.21 5-1. Workflow
      - P.22 5-1-1. Alignment 

■関連
- #63 
- #79 

■不具合

- [x] 1. 「＜＞」キーで画像を切り替えると、前の画像で入力した設定値が、クリアされている模様。
- [x] 2. OK ボタンで確定→再度Alignment Dialogを表示すると、入力した設定値が、クリアされている模様。
- [x] 3. 「Edit Imageset」で Edit Project画面へ遷移した後、OKで確定すると、Workflow画面へ戻っていない。

**Comment by Reactplus-Hao** [comment]
@sanglevinh 
Implement dialog 5-1-1. Alignment

■Tài liệu design:
- https://drive.google.com/drive/u/0/folders/19q0VTCJlKIBDTpXwBCJOaoLnLFHrLNDe
    -  File [LATEST_Screen design_v9_under-editing (18/4).pptx ](https://docs.google.com/presentation/d/14y0sTfny3pE6Rqsy4JtgrQq5Z8Aow9Nm/edit#slide=id.p50)
               - Slide 21: 5-1. Workflow
                   - Slide 22:  5-1-1. Alignment

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> Image Viewerで、傾きの操作、または傾き入力値の反映が行えるか、要検証。

上記の件について、BrainbrowserとOHIF Viewerライブラリを調査しました。
- Brainbrowserでは、
   - 傾きの操作、または傾き入力値の反映ができない
   - パラメータが取得できて、更新したパラメータを画像イメージに反映されることができる
- OHIF Viewerでは、
   - 傾きの操作ができる
   - OHIF Viewerの下記の画面に表示されているパラメータのみ取得できるが、表示できるのみ
   - パラメータの入力・変更などができない

>   傾きの操作、または傾き入力値の反映ができない

また、上記の課題について、Brainbrowserの外に画像傾きの対応を追加することができないと思います。
理由としては、
- 現在、Brainbrowserライブラリでは、canvasで対応していますので、Image ViewerのUIを更新することができない
- その他、ライブラリのImage Viewerのデータ構造とx、y、x軸の計算方法が調査できないため、座標を判断できない。
- また、座標の計算は、Image Viewerのデータ構造とcanvasでの拡大率に基づいて対応する必要があるが、
これらの情報が全てライブラリの処理に含まれているため、計算できない

上記の調査結果を踏んで、AlignmentダイアログがどのライブラリのImage Viewerで実装するか、ご検討お願い致します。
AlignmentダイアログのUIの実装期限が5/9となりますので、早めに検討して頂ければ幸いです。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
上記調査結果について、了解しました。

Viewerの画像回転への対応について、以下issueへ情報を記載しています。
- #63 

上記issueにも記載していますが、以下の対応方針としています。
- Alignment画面のViewerは、BrainBrowserですすめる。（～5/9）
- BrainBrowserへの画像回転の組み込みは、5/9～5/23 ですすめる。

**Comment by Reactplus-Hao** [comment]
@sanglevinh @linhb273 
Việc xử lý để xoay nghiêng mặt cắt ảnh Viewer, KH đã tạo riêng task dưới đây cho mình
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/63

Độ ưu tiên các task sẽ như dưới đây:
- Phần Viewer trong dialog Alignment thì sẽ chốt thư viện BrainBrowser（**Deadline: ～5/9**）
- Phần tích hợp xoay nghiêng mặt cắt ảnh vào BrainBrowser thì sẽ tiến hành trong thời gian: **5/9～5/23**

**Comment by itutu-tienday** [comment]
- 5/8実装バージョンへのコメント
  - 細かな点ですが、画像の切り替え（ ←→ ）欄の付近に、現在の画像番号（*/N）を表示してください。 （※画面設計書v10にも反映しました）

**Comment by Reactplus-Hao** [comment]
- Gần cột switch ảnh （ ←→ ）, nhờ bên mình cho hiển thị mã số ảnh hiện tại (số lượng ảnh trong list đã chọn)（*/N）giúp họ

**Comment by itutu-tienday** [comment]
Alignment Dialogの設定値を、Workflow Run API へ渡す際のパラメータ（paramの設定値）について、以下の案へのレビューをお願いします。（対応可否、仕様への指摘、など）


```yaml
# Repeat the following for the number of images.
- 
  image_id: 0
  x_pos: 0
  y_pos: 0
  z_pos: 0
  x_rotate: 0.0
  y_rotate: 0.0
  z_rotate: 0.0
  x_resize: 0.0
  y_resize: 0.0
  z_resize: 0.0
```

- メモ
  - 現行システムでは、パラメータの数が動的に変化するノードはないと思われるが、上記フォーマットで問題はないか？

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
- paramフォーマット案について、問題がないと思います。

> 現行システムでは、上記の様にパラメータの数が動的に変化するノードはないと思われるが、問題はないか？

- Alignment Dialogの設定値を、Workflow Run API へ渡す仕様であれば、パラメータの数が動的に変化するノードが必要かと思いますので、ご検証よろしくお願い致します。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday  @emuemuJP 
AlignmentダイアログのUIの実装について、対応とテスト実施が完了しましたので、ご確認お願い致します。
- テストエビデンス：
    - https://drive.google.com/file/d/1z4pflmF396kFB3AkBrNn_xSdYjm2loDs/view?usp=sharing
    - https://drive.google.com/file/d/1t_nGuTW8QOBQk8Kd9kiybBehokimCjdu/view?usp=sharing
    - https://drive.google.com/file/d/1bhnRBaPBj7dJjYnOhdMKaFAFOIUqU3jb/view?usp=sharing
- テストケース：
    - https://docs.google.com/spreadsheets/d/1fVFSiZMky76HGC9D7nvWCsm6ecWMFjd0kMnJ9qexw90/edit#gid=909937738

**Comment by itutu-tienday** [comment]
APIパラメータの確認について、ありがとうございます。
なお以下のコメントをいただいていますが、

> パラメータの数が動的に変化するノードが必要かと思いますので、ご検証よろしくお願い致します。

上記の検証とは、Run API側で動的なパラメータを受け取り可能であるか？ の検証かと思われますが、その部分（BackEnd）の確認も、依頼したいと思います。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
- 要件としては、下記の認識で合っていますでしょうか。
   - Alignment Dialogの設定値を、Workflow Run API へ渡す時に、各のノードにパラメータ値が動的に追加・変化されます。
   - ProjectsをReproduceする時に、これらのパラメータ値を取得・再利用できるために、これらのパラメータ値がサーバーの方で保存されます。
   
上記の仕様であれば、対応できると思います。

**Comment by itutu-tienday** [comment]
> 要件としては、下記の認識で合っていますでしょうか。
合っているものと思います。
※現行のoptinistのRun APIを基本変えずに、そのまま利用する想定です。

また以下、質問を追記します。

- 質問
  - APIのparamパラメーターは、おそらくdict型で指定する必要があるようなので、後述のフォーマットで想定します。 （もし問題があれば、お伝えください）
  - 先日、FEの方から以下のコメントをいただいていますが、ここまでの情報整理状況で、FEの方は問題なく対応可能そうでしょうか？
    > パラメータの数が動的に変化するノードが必要かと思いますので、ご検証よろしくお願い致します。

- paramフォーマット案
  ```yaml
  # images_alignment.yaml
  
  alignments:
    # Repeat the following for the number of images.
    - 
      image_id: 0
      x_pos: 0
      y_pos: 0
      z_pos: 0
      x_rotate: 0.0
      y_rotate: 0.0
      z_rotate: 0.0
      x_resize: 0.0
      y_resize: 0.0
      z_resize: 0.0
  ```

APIパラメータについて、ここまでの内容で特に問題がなければ、FEの方で、

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 1. 「＜＞」キーで画像を切り替えると、前の画像で入力した設定値が、クリアされている模様。
 2. OK ボタンで確定→再度Alignment Dialogを表示すると、入力した設定値が、クリアされている模様。
 3. 「Edit Imageset」で Edit Project画面へ遷移した後、OKで確定すると、Workflow画面へ戻っていない。

上記の３つの不具合を修正して、ソースコードをPushしましたので、ご確認お願い致します。
エビデンスは下記の動画となります。
https://drive.google.com/file/d/1qS4eFOw8nfB16P4vQqlBZKBeB2Wzxqww/view

**Comment by itutu-tienday** [comment]
不具合（No.1-3）の修正を確認。

あとは、関連issue #79 の完了をもって、クローズとする。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 

ご記載の想定仕様と、現在の実装内容（5/18版）に、若干差異があるようです。 （不具合 No.1 の修正の影響？）
以下、ご確認ください。

--

> - Alignmentダイアログの「OK」ボタンを押さないと、設定したパラメータが保存できない
> - Alignmentダイアログの「Cancel」と「X」ボタンを押すと、設定したパラメータが保存できない

上記でOKです。

> - テキストボックスに数字を入力した場合、「Set Origin」ボタンと「OK」ボタンを押さないと、保存できない。

→ 上記は、Set Originを押さなくても、OKクリックで、パラメータは保存されているようです。 （※この動作でよいものと思います）

→ また、「＜＞」をクリックした場合には、どのような挙動で実装とされているでしょうか？
　→ 現在は、Set Origin は押していないが、Set Originを押した場合と同じ挙動である様です。
　→ 暗黙的に Set Origin されている点は、少し分かりづらいかもしれませんが、現状の挙動でOKと思います。

> - テキストボックスに数字を入力した場合、「Set Origin」ボタンを押せずに、「OK」ボタンのみ押すと、パラメータデータが保存されていますが、そのパラメータが画像に反映されない

→ 上記は、OKクリック後、再度ダイアログを開くと「パラメータは画像に反映されている」ようです。 （※この動作でよいものと思います）

**Comment by Reactplus-Hao** [comment]
Spec thao tác bên mình dự định có trên Alignment Dialog và nội dung thao tác bên mình đang làm có vẻ đang khác nhau. (Liệu có phải do chỉnh sủa bug No.1 nên bị ảnh hưởng không?)
Nhờ bên mình check giúp.

> Cần phải nhấn vào button OK thì mới save parameter đã setting.
> Nếu nhấn vào button X hoặc Cancel thì sẽ không save parameter đã setting

Spec trên thì OK rồi, và thao tác hiện tại thì cũng đang như vậy.

> Sau khi đã nhập số vào trong text box, cần phải nhấn button Set Origin và button OK thì mới save parameter đã setting.

Họ check thao tác hiện tại, thì thấy có vẻ như không cần nhấn button Set Origin mà chỉ nhấn OK thì vẫn lưu parameter được (Họ nghĩ thao tác như này OK rồi)

- Ngoài ra, trường hợp đã click vào button Next/ Back thì bên mình đang làm với thao tác như nào?
    - Họ check thì thấy có vẻ như hiện tại hoạt động khi không nhấn button Set Origin và hoạt động khi nhấn Set Origin đang giống nhau.
    - Sẽ hơi khó hiểu ở phần Set Origin, nhưng với hoạt động như hiện tại thì OK rồi.

> Trường hợp ko set origin mà chỉ nhấn OK thì vẫn lưu client nhưng ko apply vào ảnh

Họ check thao tác hiện tại, thì thấy sau khi click vào button OK và mở lại dialog thì parameter đã được phản ánh lên ảnh luôn (Thao tác như này OK)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
確かに現在の動作はご記載のようになっていますね。
なお、「＜＞」をクリックした場合には、Set Originを押した場合とSet Originを押さない場合は同じ挙動でパラメータを保存しましが、
Set Originを押した場合、そのパラメータを画像に反映されています。
現在の動作でよいものであれば、このまま対応させて頂きます。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
現時点では、現状の動作でOKです。

※なお Set Originボタンの挙動は、画像断面回転の件と関連しているため、回転機能の組み込み完了後、調整はあるかもしれません。
