### ISSUE TITLE
Workflowセッションの管理方式の改修

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#58]
### 対応内容

- 現状の課題
  - 現在のoptinistでは、複数のworkflowを同時実行することが想定されていない。
  - これに対し、MRI STUDIO版では、「Project」に紐づくworkflowを、複数 同時実行可能とすることが求められる。

- 対応内容
  - 複数のworkflowを同時実行できるようにする。
  - また同時実行の他、同時実行の状態確認も可能とする。
  - 停止操作などのworkflow個別の管理操作も可能とする。

- 想定される課題
  - frontend
    - 修正箇所の洗い出し結果によっては、修正の影響範囲が小さくない可能性もある。
    - ※現在のoptinistでは、workflow のステート管理が明文化されていないため、このタイミングで整理しておきたい。
  - backend
    - 複数のworkflowプロセスを同時実行しても問題がないか、仕様確認が必要。

- 関連
  - #64

**Comment by ReiHashimoto** [comment]
## 複数workflowの同時実行について

- 基本的には同時実行可能
  - 現状snakemakeの実行呼び出しはFastAPIのbackground_tasksへの追加で行っており、background_taskのsnakemake_executeが並列で実行される
  https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/0f298490123d04f5bb23fbb9ea9a1a3377e26024/optinist/api/workflow/workflow_runner.py#L47-L51
    参考：https://qiita.com/uezo/items/8225e33dfe0e342d0271

- ただし、Snakemakeで参照するconfig.yamlのパスが共通のため、
  https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/0f298490123d04f5bb23fbb9ea9a1a3377e26024/optinist/Snakefile#L6
  
  - 1つ目のworkflowのsnakemake実行
  - 2つ目のworkflowのconfig.yamlへの書き出し
    https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/0f298490123d04f5bb23fbb9ea9a1a3377e26024/optinist/api/workflow/workflow_runner.py#L32  
  
  が重複すると、不整合が起きる可能性がある。

  - Snakemakeの実行タイミングが重複した時に以下のようなエラーが発生
    - ただし、複数回試行したものの一度しか発生しなかった
    ```
    CreateRuleException in file /Users/rei_hashimoto/GitHub/optinist/optinist/Snakefile, line 9:
    The name all is already used by another rule
      File "/Users/rei_hashimoto/GitHub/optinist/optinist/Snakefile", line 9, in <module>
    ```


### 対策案
- snakemakeのconfigファイルとしてユニークなものを使用する
  - `output/{uid}/config.yaml`の生成自体は現状もしているので、Snakefileのconfigfile、snakemake_executeの実行パラメータなどの修正で対応
    https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/0f298490123d04f5bb23fbb9ea9a1a3377e26024/optinist/api/snakemake/snakemake_writer.py#L15-L19

**Comment by ReiHashimoto** [comment]
## 同時実行の状態確認について

- 現状のpipeline(workflow)のステータスに関するstate（単体しか管理できない）
  https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/76273a17e7e507ce1f1f56fa8261ea3825181683/frontend/src/store/slice/Pipeline/PipelineSlice.ts#L18-L23

- プロジェクトごとに、そのプロジェクトが保有するpipeline(workflow)ごとのステータスを管理するように、プロジェクトのstate設定をする必要がある
  - 現状仮置きされているdataprojectのstate
    https://github.com/arayabrain/MRIAnalysisStudioforMouse/blob/76273a17e7e507ce1f1f56fa8261ea3825181683/frontend/src/pages/Projects/index.tsx#L20-L37
  - 複数パターンの実装が考えられるが、いずれも工数は大きめ。後者の方が比較的それぞれのstateを疎にできてベターかもしれない
    - 上記stateに、以下のように保有しているworkflowを持たせる→pipelineのreducerもproject側に寄せる必要あり
        ```
        {
          workflows: {
            [WORKFLOW_ID_1]: {
              run: {
                status: STATUS,
              },
              runBtn: RUN_BTN_OPTION,
            }
          }
        }
        ```
    - pipelineのstateを複数にして、それぞれに紐づいているproject idを持たせる → pipelineのreducerのstate更新方法自体を変える必要あり

**Comment by ReiHashimoto** [comment]
- project id → DB側でシリアル発行予定のため、Workflow idと異なる
- 今回は1project1workflowだが、1対多を想定してつくる

**Comment by Reactplus-Hao** [comment]
@sanglevinh 
Chỉnh sửa cách quản lý session Workflow
Nội dung xử lý
- Tình trạng hiện tại
    - Trong Optinist hiện tại, dự định sẽ không chạy đồng thời nhiều Workflow
    - Tuy nhiên, đối với bản trên MRI STUDIO, thì họ mong muốn sẽ có thể chạy đồng thời nhiều Wokflow mà đang liên kết với page [Project]
- Nội dung xử lý
    - Xử lý để có thể chạy đồng thời nhiều Workflow
    - Ngoài việc chạy đồng thời, thì xử lý để có thể check được trạng thái chạy đồng thời của các Workflow đó.
    - Xử lý để có thể thao tác quản lý từng Workflow, chẳng hạn như thao tác cho dừng Workflow nào đó.
- Vấn đề có thể gặp phải
    - frontend
        - Tuỳ thuộc vào kết quả list up ra các chỗ cần chỉnh sửa, thì họ nghĩ có khả năng phạm vi ảnh hưởng khi chỉnh sửa sẽ khá lớn
        - ※Trong Optinist hiện tại, đang không được xác định rõ ràng phần quản lý State của Workflow, nên trong lần này họ muốn điều chỉnh rõ ràng lại
    - backend (Bên phía Araya)
        - Cần check spec xem chạy đồng thời nhiều process workflow thì có vấn đề gì không.

**Comment by itutu-tienday** [comment]
画面設計書（v10）へ、説明情報を追記。（5-1. Workflow）
まず技術者の方で、以下を確認いただきたい。

- 技術的な対応方針
- 対応の工数見込み

**Comment by Reactplus-Hao** [comment]
@sanglevinh 
KH đã thông tin giải thích của task này vào trong spec mới nhất rồi （[Trong Slide 22](https://docs.google.com/presentation/d/1-iBngGOBH9Pv7sD3NE5_R1Yot_tG1aHU/edit#slide=id.p51)）

- Trước hết nhờ bên mình check các phần dưới đây giúp họ.
   - Hướng xử lý về mặt kĩ thuật
   - Est effort xử lý
- Deadline check hướng xử lý + est effort: ~9/5

**Comment by ReiHashimoto** [comment]
https://github.com/oist/optinist/pull/478
上記のような実行履歴保持を利用して、以下の方針も考えられるかもしれない


- workflow.yaml
  - workflowごとの実行状態を保持
    - ただし、RUN, RUN_ALL実行前にリロード・ページ遷移した場合の保持は想定しない
  ```
  [project_id]:
    authenticated_users: # ユーザー権限などもこちらでハンドリング
    - foo # firebase uids
    - bar
    workflows:
    [workflow_id]:
	    # name: hoge # 現状は割愛
	    status: running # error, success
	    created_at: '2023-05-01 20:40:18'
	    last_ran_at: '2023-05-01 20:40:18'
	    # runの度にlast_ran_atを更新すると、ページを開いた時のポーリングでも更新される
	    # NodeのパラメータをいじったときはforceRunListで判断できるが、
	    # nwbParamとかsnakemakeParamは差分検知ができない
	    authenticated_users: # あるいはここで権限？
		    - foo # firebase uids
		    - bar
	    nodes:
		    [node_id]:
			    
    [workflow_id]:
	    ...
  [project_id]:
  ...

**Comment by itutu-tienday** [comment]
対応完了、develop-main マージ済み。
