### ISSUE TITLE
OHIF Viewer NiFTI形式データの表示可否調査

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#59]
OHIF Viewer で、NiFTI 形式画像を表示させる方法を調査する。

- 参考情報
  - 標準では、OHIF Viewer は NiFTI 形式には非対応である模様。
    - （参考情報）
      - https://github.com/OHIF/Viewers/issues/1629
      - https://github.com/OHIF/Viewers/issues/2869
      - https://github.com/OHIF/Viewers/issues/1629
      - https://groups.google.com/g/xnat_discussion/c/8U2mLHCnWuI/m/Q5EvT23-AAAJ
 
  - 上記の状況ではあるが、何らか対応方法があるか、調査・検証を行う。

- 関連
  - #15

**Comment by Reactplus-Hao** [comment]
Điều tra cách để cho hiển thị ảnh format NiFTI trong thư viện OHIF Viewer

- Thông tin tham khảo
     - Theo mặc định (tiêu chuẩn) thì OHIF Viewer không hỗ trợ format NiFTI

       - Thông tin tham khảo
           - https://github.com/OHIF/Viewers/issues/1629
           - https://github.com/OHIF/Viewers/issues/2869
           - https://github.com/OHIF/Viewers/issues/1629
           - https://groups.google.com/g/xnat_discussion/c/8U2mLHCnWuI/m/Q5EvT23-AAAJ
    
    - Mặc dù tình trạng hiện tại đang như trên, nhưng KH muốn nhờ bên mình điều tra xem có cách xử lý không?

- Ticket liên quan:
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/15

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> OHIF Viewer NiFTI形式データの表示可否調査
> 上記の状況ではあるが、何らか対応方法があるか、調査・検証を行う。

上記の調査について、ご提供頂いた参考情報を確認して、調査結果を下記にて共有させていただきます。
- 確かにOHIF ViewerでNiFTI形式データを対応できないです。
- NiFTI形式のファイルをDCOM形式にファイルに変換しても、OHIF Viewerに表示できません。
- OHIF Viewerはパックされたライブラリであり、明確なドキュメントがないため、OHIF Viewerの開発者ではないと、機能の編集や追加などができないかと思います。
- また、OHIF Viewerライブラリの開発者により「近い将来にNiFTI形式データの表示をサポートする計画 (または資金提供) はありません。」と「様々なデータソースをサポートできるように幾つかの変更が予算されています」と言われましたので、
OHIF Viewerの開発者ではないと、ライブラリの機能の以外に他の機能を編集・追加できないと思います。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
調査ありがとうございました。内容の方了解しました。
当件は一旦クローズします。
