### ISSUE TITLE
アカウントのデータ項目（Role）の仕様調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#60]
アカウントのデータ項目（Role）について、以下の仕様調整の反映をお願いしたいと思います。

- DBのカラムのタイプをNumberとする。 また、Role名称を変更する。
  - 以下 設定内容
    1. "Admin" (Code:1)  ※管理者
    2. "Data Manager" (Code:10)  ※データ取得者（データ管理者）
    3. "User" (Code:20)  ※解析実行者

- 補足
  - DB上はNumberで保有する。名称はプログラム or DB のどちらで保有する形でもOK。

**Comment by Reactplus-Hao** [comment]
Phần mục data Role của account, nhờ bên mình phản ánh spec dưới đây 

- Sẽ để type của column trong DB là Number. Ngoài ra, cần thay đổi tên của Role

    - Nội dung setting như dưới đây:
         - "Admin" (Code:1) ※Người quản lý
         - "Data Manager" (Code:10) ※Người lấy data (Người quản lý data)
         - "User" (Code:20) ※Người thực hiện phân tích
- Bổ sung
    - Sẽ lưu dưới dạng Number trên DB. Tên của Role thì có thể lưu trên program or trên DB cũng được.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このIssueの対応とテスト実施が完了しました。
お手数ですが、ご確認お願い致します。
https://drive.google.com/file/d/1V2WdBIc0FqO4W-ZuMaYsxeOYIuPes5rU/view?usp=sharing
