### ISSUE TITLE
通信時のローディングアイコン表示

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#61]
BackEndとのAPI通信時に、ローディングアイコンを表示する対応をお願いします。

- 補足
  - 基本的には、一通りの通信処理で、ローディングアイコン表示を実施する。
  - 現行のoptinist（workflow画面等）では、ローディングアイコン表示がもともと入っていないため、一旦対応保留。（今後の組み込みを想定）
    - ただし、現行のoptinistで処理時間のかかる通信は、ローディングアイコン表示対象。
      - https://github.com/oist/optinist/issues/427

### 不具合・指摘

- 6/9版
  - 1. [x] 以下の画面にローディングアイコン表示が入っていない。
       - [x] 4.Projects
       - [x] 4-1.Add Project
  - 2. [x] 3. Databae viewで、tree/list を切り替えると、loading icon が表示されなくなっている（背景はグレーにはなる）
  - 3. [x] 4-2. Edit Project で、loading icon が表示されたりされなかったりする模様（右ペインにloading icon が入っていない？）

### 対応残

- [ ] 5-2. Result
- [ ] 5-3. Visualize

**Comment by reactplus-thom** [comment]
@itutu-tienday 
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/149
・上記のPRで以下の箇所で対応終わっています。
【対応済み画面】
1. Login
2. account profile (Edit, Change password)
3. Database (Tree View, List View, Filter, Image View (next/previous))
4. Projects (Add project, Edit project, delete project, Image View (next/previous), Filter)
5. Workflow
6. Visualize (load params, save params)
7. Account Manager (list, add account, edit account, delete account)

・残りは以下の画面を想定していますが、API提供次第、対応する予定です。
8. Result

なお、上記画面以外、他に対応する必要な個所があればご連絡をお願いいたします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
ありがとうございます。
ほぼ記載する修正が適用されていますが、説明欄に記載の以下の指摘が、未修正の様でした。
ご確認ください。（※優先度は低め）

> - 3. Databae viewで、tree/list を切り替えると、loading icon が表示されなくなっている（背景はグレーにはなる）
> - 4-2. Edit Project で、loading icon が表示されたりされなかったりする模様（右ペインにloading icon が入っていない？）

**Comment by reactplus-thom** [comment]
Có 2 phần sau check vẫn thấy chưa được:
1) Màn Databae view: khi switch giữa tree/list ko có loading icon (mặc dù background hiển thị xám)
2) Màn Edit Project: loading icon lúc có lúc không (và có phải ở pane bên phải cũng ko có loading icon?)

**Comment by reactplus-thom** [comment]
@itutu-tienday 

以下の通り、確認・対応結果を報告いたします。

> 3. Databae viewで、tree/list を切り替えると、loading icon が表示されなくなっている（背景はグレーにはなる）
> 4-2. Edit Project で、loading icon が表示されたりされなかったりする模様

確認させて頂いた上、こちら画面はすでにloading iconの実装がされています。
ご確認された時に、loading icon が表示されないや、loading icon が表示されたりされなかったりすることは、
networkのスピードに起因した事象だと判断しております。
すみませんが、networkのスピードを下げたりして再確認していただけないでしょうか。
※こちらの確認結果もご参照に添付しますが、ご確認ください。
https://drive.google.com/file/d/168LBiDEybZhlzrpbQGGUah-3MaCNRO-K/view

> 右ペインにloading icon が入っていない？

Edit/Add Project画面の右ペインはそんなに処理時間のかかる箇所ではないと想定しておりましたので、
loading iconを入れませんでした。
入れておいた方がよいかと思いますので、以下のPRで対応いたしました。
上記の件と併せてご確認いただければ助かります。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/149

よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
最新版で確認しましたが、やはり当方の環境では、ローディングアイコンが表示されたりされなかったりする事象を確認しています。

- 確認環境
  - Windows, Mac
    - ※複数の環境で確認されるため、環境依存やネットワークではなさそう
  - frontend はbuild して確認

- 再現手順
  - Database画面 … TreeとListを何度も切り替える
  - Edit Project画面 … Projects画面とEdit Project画面 を何度も切り替える

----
上記の再現手順を確認いただき、再現しない様であれば、優先度は高くない内容のため、クローズを想定します。

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
試しにですが、
frontend/src/api/dataset, project, rawdb　のそれぞれの処理(const response = の前など)に
`await new Promise((r) => setTimeout(r, 2000))`などを挿入いただくと確認しやすいかと思います。

一部修正も上がっていますが、こちらで試してみたところは問題なさそうです。
上記の手法でお試しいただけますか

**Comment by itutu-tienday** [comment]
@reactplus-thom  @ReiHashimoto 
一応、こちらの確認動画を添付します。
https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/122338895/871d4d2c-6a52-4bbd-ab57-ccf4b7318675
※API通信時のsleep（2,000msec）は入れて確認しています。

ただ上でも記載していますが、優先度は低い内容のため、念のため動作確認いただき問題ない（再現しない）ようであれば、クローズとします。

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
一応私の環境での確認結果です。
おそらく問題ないかと！一旦クローズで良いと思います。

https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/42664619/caab1a67-21f1-4d66-a282-6f1018f81992

**Comment by reactplus-thom** [comment]
・Visualize、Results画面の対応
・動作確認：https://drive.google.com/file/d/1yNzQnARNH7Do251F2Gq0IMAi981cvdNf/view?usp=drive_link
※Visualize、Results画面の組込みの対応PRと一緒です。
