### ISSUE TITLE
システムディレクトリ構成の整理

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#62]
MRIAnalysisStudioforMouse のシステムのディレクトリ構成を仕様整理する。

**Comment by itutu-tienday** [comment]
一旦、現在のディレクトリ構成についての解説と、想定する課題があれば、共有をお願いします。

- optinistからの主な変更点
  - 直下に backend, studio のディレクトリが追加されている

**Comment by Reactplus-Hao** [comment]
Hiện tại, nếu bên mình có bất kỳ nội dung note hay thấy có vấn đề cần giải quyết liên quan đến cấu trúc directory hiện tại, thì hãy share cho KH biết.

   - Điểm thay đổi lớn so với optinist
      -  Đã thêm directory backend, studio trực tiếp ở trong system

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
> optinistからの主な変更点
直下に backend, studio のディレクトリが追加されている

現在、studioとoptinistディレクトリの構造が同じであるのでしょうか。
しかし、現在のバックエンドサーバーを実行するmainファイルは、studioディレクトリではなく、optinistディレクトリからのルーターのみインポートされているようです。
studioとoptinistの両方も使用しているのは必要でしょうか。
可能であれば、使用意図を教えて頂けますでしょうか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
- studio ディレクトリは、RP様で追加されたものと思いましたが、Araya側で追加しているのですね？  → Araya内で確認します。
- RP様で変更を加えられているディレクトリ構成は、backend のみでしょうか。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> studio ディレクトリは、RP様で追加されたものと思いましたが、Araya側で追加しているのですね？ 
RP様で変更を加えられているディレクトリ構成は、backend のみでしょうか？

そうですね。弊社側で追加したディレクトリ構成はbackend のみですので、 studio ディレクトリはAraya側で追加されたかと思います。
ご確認お願い致します。

- また、backendディレクトリの構成は下記の通りになっています。
現時点では、このディレクトリについて、他の備考がありませんので、ご確認お願い致します
```
backend
├── models  #  アプリケーション向けのデータモデルを定義する
│   ├── error  # 例外、エラーコード、エラーメッセージを定義する 
│   │   ├── app_exception.py
│   │   ├── code.py
│   │   └── msg.py
│   ├── token.py # トークンモデルのデータ 
│   └── user.py # ユーザーをCRUDするためのデータモデル（各フィルードのバリデーションも含む）
├── routers # ルーターを定義する
│       ├── auth.py # 現在のユーザー情報の取得、ユーザー登録、ユーザーのログインのルーター
│       └── user_manage.py # 管理者向けのユーザー管理のルーター
├── service # アプリケーションに利用するサービス・機能
│   └── firebase
│ 	├── __init__.py #  Firebase Admin SDKを初期化する
│       ├── auth.py # ログインと登録の関連の機能
│       └── crud_user.py # ユーザー管理の関連の機能
├── tests # 各のテストを定義する
│   └── routers
│       └── test_auth.py
└── deps.py # ユーザーの認証・認可の依存関係
```
