### ISSUE TITLE
画面表示情報の仕様修正

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#65]
以下、画面表示情報の仕様修正を行う。

- 資料
  - 画面設計_v10.pptx

- 修正内容
  - [ ] DatabaseのViewのカラムの名称変更
    - Dataset → Datatype
  - [x] 日付時刻のフォーマット調整（秒の表示 不要）
    - 4.Projects, etc
  - [x] Image Viewerの操作アイコン（←→×）が見えづらい。
    - アイコンの背景（サークル）を少し明るくするなど。

**Comment by Reactplus-Hao** [comment]
Tiến hành chỉnh sửa spec của các phần hiển thị trên màn hình dưới đây:

- Tài liệu
     - [Screen design_v10 (26/04)](https://docs.google.com/presentation/d/1-iBngGOBH9Pv7sD3NE5_R1Yot_tG1aHU/edit#slide=id.p1)
- Nội dung chỉnh sửa
    - Thay đổi tên column View trong màn hình Database
       - Dataset → Datatype
   - Chỉnh sửa format của ngày giờ （Không cần hiển thị giây nữa）
       - Chẳng hạn như ở page 4.Projects, v.v..
   - Hiện tại các icon thao tác trên Image Viewer như （←→×) đang hơi bị khó nhìn
       - Hãy sửa background (circle) của icon sáng lên một chút chẳng hạn

**Comment by itutu-tienday** [comment]
- DatabaseのViewのカラムの名称変更
  - ADD/EDIT PROJECT 画面への修正が未適用。

**Comment by Reactplus-Hao** [comment]
- Thay đổi tên của cột các cột View trong màn Database (Dataset → Datatype)
    - Phần này nhờ bên mình apply sang cả màn Add/ Edit Project nữa.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> DatabaseのViewのカラムの名称変更
ADD/EDIT PROJECT 画面への修正が未適用。

上記の内容の対応とテスト実施が完了しました。
エビデンスは、下記の通りとなりますので、ご確認お願い致します。
https://drive.google.com/file/d/1Q2V5LqttxSulv6hc4DkWBRTHqKv9kwH-/view?usp=sharing

**Comment by itutu-tienday** [comment]
ありがとうございます、修正を確認しました。
