### ISSUE TITLE
Account Manager画面の表示項目調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#66]
6. Account Manager で、表示カラムに UID を追加する。

- 資料
  - 画面設計_v10.pptx

**Comment by Reactplus-Hao** [comment]
Chỉnh sửa mục hiển thị trên màn hình Account Manager

- Add thêm cột UID vào trong màn hình Account Manager
    - Tài liệu:
       - [Slide 27](https://docs.google.com/presentation/d/1-iBngGOBH9Pv7sD3NE5_R1Yot_tG1aHU/edit#slide=id.p24)
