### ISSUE TITLE
ProjectのImagesetの重複登録不可処理

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#67]
4-1. Add Project (4-2. Edit Project) で、同一Project Imageset内に、同一の画像登録は不可とする。

- 資料
  - 画面設計_v10.pptx

**Comment by Reactplus-Hao** [comment]
Xử lý để không thể đăng ký trùng lặp Imageset trong màn hình Project 

- Trong màn hình 4-1. Add Project (4-2. Edit Project) , xử lý để không thể đăng ký cùng 1 ảnh vào trong cùng 1 Project Imageset
    - Tài liệu 
        - [Slide 18-20](https://docs.google.com/presentation/d/1-iBngGOBH9Pv7sD3NE5_R1Yot_tG1aHU/edit#slide=id.p17)

**Comment by itutu-tienday** [comment]
以下の様な不具合らしい事象を確認しています。

1. ドラッグの際、まだクリックを離していないのに、「Image existed」のアラートが出る。
2. ドラッグの際、まだクリックを離していないのに、画像が登録されてしまう。
3. 1.の後、クリックを離しても、ドラッグの状態が継続している。
4. 左ペインに画像登録→削除した後、再度画像をドラッグすると、「Image existed」のアラートが出る。
など

ドラッグ周りで不具合が多いようなので、もし仕様の方を変更した方がよさそうであれば、ご相談ください。

**Comment by Reactplus-Hao** [comment]
KH check thì thấy có vẻ như một số phần dưới đây là bug

1. Khi drag và chưa bỏ chuột mà đã hiển thị alert 「Image existed」
2. Khi drag và chưa bỏ chuột mà đã đăng ký ảnh rồi.
3. Sau thao tác 1. ở trên, cho dù bỏ chuột thì vẫn đang bị giữ nguyên trạng thái drag
4.Sau khi đăng ký 1 ảnh nào đó vào khung bên trái và lại xóa bỏ ảnh đó, thì khi drag lại ảnh đó 1 lần nữa thì đang bị hiển thị alert  「Image existed」

KH thấy có vẻ như có nhiều bug liên quan đến thao tác drag, nếu như bên mình thấy nên thay đổi spec drag hiện tại cho phù hợp thì hãy báo họ.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 1. ドラッグの際、まだクリックを離していないのに、「Image existed」のアラートが出る。
> 2. ドラッグの際、まだクリックを離していないのに、画像が登録されてしまう。
> 3. 1.の後、クリックを離しても、ドラッグの状態が継続している。
> 4. 左ペインに画像登録→削除した後、再度画像をドラッグすると、「Image existed」のアラートが出る。

上記の不具合を修正して、テスト実施しました。
お手数ですが、ご確認お願い致します。
- エビデンス：
    - Edit Project画面：https://drive.google.com/file/d/1l85KPuss45g8r-BkcH1AAVKiRHu6D8JB/view?usp=sharing
    - Add Project画面：https://drive.google.com/file/d/1VRheExlyUdYtoIv-Y9fqzyI2dmlTlVEj/view?usp=sharing
