### ISSUE TITLE
Database APIサンプルデータの検証

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#72]
API開発担当（知能情報システム社）より、Database APIのサンプルデータを受領、以下へ格納している。

- https://drive.google.com/drive/folders/1Pnt1bT1kkbkSuswaWHCycIKcVq9Ctt9p
  - rawdb-search.json
  - rawdb-search-list.json

内容について確認を行う。（問題点、要望、等）

**Comment by itutu-tienday** [comment]
一旦、以下の点を確認。


- 共通
  - imageA.attributes に、配列形式のデータが含まれている。
  - iamges.attributes に、 type (type_rate) がない。
  - image_url は、実際は https: からのURLを想定。

- rawdb-search
  - 以下のID項目が、number から string へ変更されている。
      - subject.id
      - session.id
      - datatype.id

- rawdb-search-list
  - 以下の項目が削除されている。
    - subject_id
    - session_id
    - datatype_id

**Comment by Reactplus-Hao** [comment]
@sanglevinh 
**- Bên BE (Phát triển API) đã cung cấp sample data của Database API dưới đây:**
   - https://drive.google.com/drive/folders/1-mbYB66zwIpw5gDTx-CrwJxoIs6-SeXl
    - rawdb-search.json
    - rawdb-search-list.json

**- Bên Araya đã check và có note lại 1 vài chỗ để ý + mong muốn dưới đây:**
   - Common 
       - Trong images.attributes đã bao gồm data format array
       - Trong iamges.attributes đang không có  type (type_rate)  → Sẽ check lại với bên BE API
       - Họ dự định phần image_url thực tế sẽ là URL từ https:  （Liệu có thể để theo format chấp nhận https://xxxx/  ở phía frontend được không?）
  - rawdb-search
      - Các item ID dưới đây đã được đổi từ number sang string 
         - subject.id
         - session.id
         - datatype.id
         - rawdb-search-list
     - Các item dưới đây đã bị xoá
        - subject_id
        - session_id
        - datatype_id

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> https://drive.google.com/drive/folders/1Pnt1bT1kkbkSuswaWHCycIKcVq9Ctt9p
> rawdb-search.json
> rawdb-search-list.json

ご共有いただいた気づいた点を確認できました。
これらの箇所の以外、他の問題点や要望点などが特にありませんので、このバージョンで問題がありません。
