### ISSUE TITLE
Firebase認証セッションの維持

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#73]
Firebase認証セッション（Token）は、有効期限が1時間であるようだが、
ワークフローの実行は1時間以上要するケースがあるため、ユーザーが画面を無操作であっても、認証セッションを維持させておきたい。

- 要件
  - ユーザー操作中は、ログインセッションは維持する
  - ワークフロー画面での処理実行中は、ユーザー操作がない状態でも、ログインセッションは維持する
  - ログインセッションの有効期限は、以下を想定 （1 or 2 のいずれかは、実装の複雑さ、対応工数、も参考に選定する） 
    - 1\. ユーザーの最終画面操作から、X時間維持する（Xは当初24時間、変更可能とする）
    - 2\. 初回ログイン成功から、X時間維持する（Xは当初24時間、変更可能とする）
        - ユーザー操作中であっても、上記の期限超過時は、ログアウトとなる
  - 上記の処理フローの説明ドキュメントを作成する

- 情報
  - https://firebase.google.com/docs/auth/admin/manage-sessions

- 技術仕様確認
  - [x] 認証セッションの有効期限を、「ユーザーの最終操作時間から、XX時間後」という方式にすることは、（比較的簡易に）実現可能であるかどうか。

**Comment by itutu-tienday** [comment]
当件について、まず、実現案の提案をいただきたい。

**Comment by Reactplus-Hao** [comment]
**Duy trì session authentication Firebase**
Hiện tại, có vẻ như Session authen Firebase（Token）đang có thời gian hiệu lực là 1 tiếng
Tuy nhiên, cũng có lúc thời gian chạy workflow nhiều hơn 1 tiếng, nên user không thể thao tác trên màn hình. 
Vì vậy, họ muốn xử lý để duy trì session authen

- Cách thực hiện
    -  Trong khi đang hiển thị màn hình Workflow, thì sẽ thực hiện update token theo định kì (chẳng hạn định kì vài phút)
- Thông tin tham khảo:
    - https://firebase.google.com/docs/auth/admin/manage-sessions

**Nhờ bên mình đưa ra suggest về cách thực hiện trước cho KH. Sau khi KH xem xét thì tiến hành xử lý sau**

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
当件について、下記の実現案を提案させて頂きますので、ご検討お願い致します。
Firebase認証セッションの維持ため、
- バックエンド側が`refresh`というAPIを作成します。このAPIでは、refresh_tokenを受け取り、新しいaccess_tokenを返します。
- access_tokenの有効期限が切れた時に、フロントエンド側が`refresh`APIを呼び出して、バックエンドから新しいaccess_tokenを取得します。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
回答ありがとうございます。
以下、質問を数点記載します。

- access_tokenの有効期限が切れたのち、refresh APIを呼び出すとのことですが、有効期限が切れた後の呼び出しでは、すでにfirebaseとの認証セッションが切れた状態ではありませんでしょうか？
- 「access_tokenの有効期限が切れた時」の判定は、どこで（frontend or backend）実施される想定でしょうか？

**Comment by Reactplus-Hao** [comment]
KH cảm ơn bên mình đã rep
Ngoài ra, họ muốn confirm thêm 2 phần dưới đây:
- Bên mình có nói là : "Client sẽ call refresh nếu token bị hết hạn"
Nếu call sau khi token bị hết hạn, thì chẳng phải là session authen với Firebase cũng đã bị hết hạn hay sao?
Vậy thì call ở thời điểm nào để session authen với Firebase chưa bị hết hạn ạ?
- Việc phán đoán xem "access_token đã bị hết hạn" sẽ được thực hiện ở FE hay BE vậy ạ?

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ご質問を下記にて回答させていただきます。

> access_tokenの有効期限が切れたのち、refresh APIを呼び出すとのことですが、有効期限が切れた後の呼び出しでは、すでにfirebaseとの認証セッションが切れた状態ではありませんでしょうか？

access_tokenの有効期限が切れた時に、ログアウトになってしまうことを考えていますでしょうか。
[弊社の実現案](https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/73#issuecomment-1535905384)では、access_tokenの有効期限が切れた時に、ログアウトへ遷移せず、access_tokenがすぐにリフレッシュされるため、firebaseとの認証セッションを維持できます。

> 「access_tokenの有効期限が切れた時」の判定は、どこで（frontend or backend）実施される想定でしょうか？

 「access_tokenの有効期限が切れた時」の判定は、backend（サーバー）の方で実施される想定です。

**Comment by itutu-tienday** [comment]
> https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/73#issuecomment-1535905384では、access_tokenの有効期限が切れた時に、ログアウトへ遷移せず、access_tokenがすぐにリフレッシュされるため、firebaseとの認証セッションを維持できます。

access_token の有効期限と、firebaseの認証セッションの有効期限は、別になっている、ということ であっていますでしょうか？
その様であれば、access_token の期限切れの後（直後）のtokenリフレッシュで、問題ないようですね。

> 「access_tokenの有効期限が切れた時」の判定は、backend（サーバー）の方で実施される想定です。

処理の流れとしては、以下の様なイメージとなりますでしょうか？
1. frontend→backendへAPIアクセス
2. token有効期限切れの場合、エラー（403など？）がfrontendへ返る
3. token有効期限切れエラーを検知した場合、frontendからbackendへ、token refresh APIを要求する。
4. backend は token をrefreshし、frontendへ返す。（1へ戻る）

なお issue #51 で、tokenの確認にfirebaseへアクセスしない方式をシェアいただいていますが、#51 の方式を利用した場合も、上記の処理フローは機能しますでしょうか？

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> access_token の有効期限と、firebaseの認証セッションの有効期限は、別になっている、ということ であっていますでしょうか？
> その様であれば、access_token の期限切れの後（直後）のtokenリフレッシュで、問題ないようですね。

はい、上記の認識が合っています。

> ※なお、上記の2つの有効期限にどの程度の時間差があるか、お分かりであれば情報共有お願いします。

- access_token の有効期限の時間は1時間となります。
- firebaseの認証セッションの有効期限の時間について、refresh_tokenの有効期限が切れた時にfirebaseの認証セッションの有効期限が切れることになります。
    - 下記の条件でrefresh_tokenの有効期限が切れます。
        - ユーザーが削除された時
        - ユーザーが無効になった時
        - ユーザーがパスワードとメールアドレスを更新した時
           - 参考資料： https://firebase.google.com/docs/auth/admin/manage-sessions#:~:text=Refresh%20tokens%20expire%20only%20when%20one%20of%20the%20following%20occurs

> 処理の流れとしては、以下の様なイメージとなりますでしょうか？

ご記載のような処理の流れが合っています。

> なお issue https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51 で、tokenの確認にfirebaseへアクセスしない方式をシェアいただいていますが、https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/51 の方式を利用した場合も、上記の処理フローは機能しますでしょうか？

#51の方式を利用した場合、上記の上記の処理フローもできると思います。
なお、access_token の有効期限の時間とfirebaseの認証セッションの有効期限の時間を適切に変更できると思います。

> 現在時点の実装では、ユーザーがアクティブに画面を操作していても、tokenの期限（1時間）を過ぎると、ログアウトされる実装となっているでしょうか？

はい、現時点の実装が上記の記載のとおりです。

> ユーザーがアクティブな場合はログアウトはされない動作を期待するため、ご提案の token refresh 機能は、必須ではないかと考えます。

ユーザーがアクティブな場合はログアウトはされないように、token refresh 機能が必須だと考えます。
token refresh 機能が実装すれば、自動的にaccess_tokenとFirebase認証セッションが維持されるため、ロフアウトされなくなります。

**Comment by itutu-tienday** [comment]
それぞれ、回答ありがとうございます。
共有いただいた情報を踏まえて、認証セッション維持の仕様の要件を、このissueの説明欄に記載しています。
セッション維持機能の実装を、依頼したいと思います。

- 対応想定工数をお知らせください。
- 要件に課題がある場合は、ご相談ください。
  - firebaseのrefresh tokenには有効期限はないようですが、任意の有効期限（7日間）を設定することは可能でしょうか？
    - 参考
      - https://qiita.com/marumo3/items/d09f304f4b90cfd82e8b

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
認証セッションの維持に関して、issue説明欄に、以下の技術仕様の質問を記載しています。 確認とコメントを、お願いいたします。

> - 技術仕様確認
>   - 認証セッションの有効期限を、「ユーザーの最終操作時間から、XX時間後」という方式にすることは、（比較的簡易に）実現可能であるかどうか。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 認証セッションの有効期限を、「ユーザーの最終操作時間から、XX時間後」という方式にすることは、（比較的簡易に）実現可能であるかどうか。

上記の方式は、firebaseへの問い合わせを省略する場合だけ実現できます。
当件は、Firebaseへ問い合わせる方式なので、実現できないと思いますが、ご検討よろしくお願い致します。

なお、#51の機能を利用して、初回リリースの後に、このIssueの機能を取り込む想定でしょうね。
それでは、このIssueは初回リリースの後に対応するか、それとも先に対応して、別のPRを作成して、初回リリースの後にPRをマージして頂くのでしょうか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> 上記の方式は、firebaseへの問い合わせを省略する場合だけ実現できます。
> 当件は、Firebaseへ問い合わせる方式なので、実現できないと思いますが、ご検討よろしくお願い致します。

#51 の対応後で結構ですので、実装方法の詳細について、また情報提供をお願いします。

> なお、#51の機能を利用して、初回リリースの後に、このIssueの機能を取り込む想定でしょうね。
> それでは、このIssueは初回リリースの後に対応するか、それとも先に対応して、別のPRを作成して、初回リリースの後にPRをマージして頂くのでしょうか。

#51は、milestone を設定していますが、5/23 目標でお願いします。
当件 #73 は、#51 をリリースの後、進行する予定です。

**Comment by itutu-tienday** [comment]
説明欄の要件に記載しています、ログインセッションの有効期限 の対応パターン（1, 2）について、動作の概要仕様、また予定工数について、情報提供をお願いします。

**Comment by Reactplus-Hao** [comment]
Về thời hạn hiệu lực của login session, KH dự định sẽ xử lý theo hướng 1. hoặc 2. dưới đây (Nhờ bên mình share cho họ biết về spec cơ bản về thao tác + effort xử lý của từng phần 1. và 2. để họ tham khảo và chốt)
    1. Sẽ duy trì thời hạn trong vòng X giờ kể từ lần thao tác cuối cùng của user (X có thể là 24 giờ đầu tiên, và có thể thay đổi sau)
    2. Sẽ duy trì thời hạn trong vòng X giờ kể từ lần login thành công đầu tiên (X có thể là 24 giờ đầu tiên, và có thể thay đổi sau)

**Comment by Reactplus-Hao** [comment]
> ご記載の内容によると、「（基本的に）無期限にログインしている状態」となると思いますが、認証には有効期限（FB tokenの1時間よりも長い時間で）を持たせることを想定しています。

- 先日のミーティングで相談した実装方法について、認証には有効期限を持たせる方法を下記のファイルにまとめました。
   - https://docs.google.com/presentation/d/1p72mppRQ3CzVyhzmTj_kFxGP5WHKJRwo/edit#slide=id.p1
- この方法の実装工数は2日かかる見込みです。
ご確認のほど、よろしくお願い致します。

なお、上記の方法は下記の２つの方法と異なっています。
ご検討よろしくお願いいたします。
> - ログインセッションの有効期限は、以下を想定 （1 or 2 のいずれかは、実装の複雑さ、対応工数、も参考に選定する）
>     ① ユーザーの最終画面操作から、X時間維持する（Xは当初24時間、変更可能とする）
>     ② 初回ログイン成功から、X時間維持する（Xは当初24時間、変更可能とする）
>         - ユーザー操作中であっても、上記の期限超過時は、ログアウトとなる

**Comment by itutu-tienday** [comment]
> - 先日のミーティングで相談した実装方法について、認証には有効期限を持たせる方法を下記のファイルにまとめました。
>  - https://docs.google.com/presentation/d/1p72mppRQ3CzVyhzmTj_kFxGP5WHKJRwo/edit#slide=id.p1

上記資料への質問事項を、記載します。
ご確認をお願いします。

- > なお、上記の方法は下記の２つの方法と異なっています。
  - ご提案内容は、要件の ② に該当しているように見受けましたが、どの点が異なっていましたでしょうか。
- ご提案内容を、要件の ① に対応させるには、以下の様な手順になるのかと想像しますが、この方式の懸念事項や対応工数を、お知らせください。
  - [想定手順]
    - token内の有効期限の情報を、APIリクエストの都度 更新（最終アクセス時間の更新）する。
- 資料 2. APIリクエスト について
  - token expired のステータスコードは、401が適切ではありませんでしょうか？
    - 例) https://cloud.google.com/apigee/docs/api-platform/reference/policies/oauth-http-status-code-reference?hl=en#verifyaccesstoken-accesstokenexpired
- 資料 3. Refresh API について
  - "セッションの有効期限が切れた場合、エラーを返す" とある箇所について、 エラーのステータスコードは何を想定されているでしょうか？

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> ご提案内容は、要件の ② に該当しているように見受けましたが、どの点が異なっていましたでしょうか。

すみません、再度確認したところ、提案内容は要件の ② に該当していることですね。

> - 資料 2. APIリクエスト について
>     - token expired のステータスコードは、401が適切ではありませんでしょうか？

ご指示ありがとうございます。
確かにtoken expired のステータスコードは、401が適切ですね。

> - 資料 3. Refresh API について
>     - "セッションの有効期限が切れた場合、エラーを返す" とある箇所について、 エラーのステータスコードは何を想定されているでしょうか？

- なお、refresh tokenの有効期限が切れた時のステータスコードを400 (Bad Request)とします。
    - 例）https://cloud.google.com/apigee/docs/api-platform/reference/policies/oauth-http-status-code-reference?hl=en#refreshtoken

> - ご提案内容を、要件の ① に対応させるには、以下の様な手順になるのかと想像しますが、この方式の懸念事項や対応工数を、お知らせください。
>     - [想定手順]
>        - token内の有効期限の情報を、APIリクエストの都度 更新（最終アクセス時間の更新）する。

- 上記の手順では、APIリクエスト都度、BE側でTokenデータを更新して、FEへ返します。その後、FE側がその新しいTokenを保存する必要です。
そのため、実装が複雑になって、パフォーマンスが遅くなるかもしれません。
APIリクエスト都度にTokenを返すのは適切ではないかと思います。
- この手順の対応工数は3人日かかる見込みです。
ご検討よろしくお願い致します。

**Comment by itutu-tienday** [comment]
@itutu-tienday 
了解いたしました。

いただいた内容を踏まえ、ご提案の ② のパターンで、進行いただければと思います。
> 2. 初回ログイン成功から、X時間維持する（Xは当初24時間、変更可能とする）

よろしくお願いいたします。

**Comment by reactplus-thom** [comment]
PR: https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/91
動作確認のエビデンス：https://drive.google.com/drive/folders/1FB6SPutqG3hCu3bFzXH5wUouBEHwZPSJ
