### ISSUE TITLE
SignIn画面、Account関連画面指摘

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#76]
- 指摘・要望
  - [x] Reset password 画面 に、TOP（SignIn画面）へ戻るリンクを配置してください。
  - [x] SingIn画面のパスワード欄では、フォーマットチェックを外しておいてください。
    - [x]  画面設計書へも反映する
  - [x] パスワードの利用可能記号は、以下としてください。
    - `!#$%&()*+,-./@_|` 
    - [x] 画面設計書へも反映する

- 不具合
  - [x] SignIn画面で、SignInに失敗したあと、SIGN INのボタンをクリックしても、反応しない。（もう一度（2回目）クリックすると、動作している模様）
  - [x] Reset password 画面で、「reset passwordボタン」操作時、入力エラーが発生すると、ローディングアイコンが表示されたままフリーズする。

- 質問
  - [x] Accountパスワードのフォーマットルールを確認させてください。
    - 現在、例えば 末尾が数字で終わるパスワードは、入力エラーと判定されている模様。

**Comment by Reactplus-Hao** [comment]
Chỉnh sửa màn Sign In và các màn hình liên quan đến Account
- Yêu cầu
   - Hãy set thêm link vào màn hình Reset password để có thể back về màn TOP (Màn Sign In)
- Bug:
   - Khi Sign In thất bại trong màn hình Sign In, thì cho dù nhấn vào button SIGN IN thì đang không có phản ứng gì（Khi nhấn lại lần nữa (Nhấn lần thứ 2) thì button này mới hoạt động）
   - Trong màn hình Reset password, khi nhấn button 「reset password」mà có lỗi input xảy ra, thì Icon loading đang bị freeze, cứ hiển thị mãi
- Cần confirm:
   - Kh muốn confirm về rule format của phần Password Account
       - Hiện tại, đối với các pasword có đuôi kết thúc là số thì đang bị báo lỗi input. Nhờ bên mình check giúp đây là spec về format à? Hay đây là bug?

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ご質問を回答させて頂きます。

> Accountパスワードのフォーマットルールを確認させてください。

- Accountパスワードのフォーマットルールは、下記のようになっています。
   - 必須の桁タイプ：文字＋数字＋特殊文字
   - 最小文字数：6
   - 最大文字数: 255

> 現在、例えば 末尾が数字で終わるパスワードは、入力エラーと判定されている模様。

上記の事象を再現できていないため、確認したパスワードと再現手順を教えて頂けますでしょうか

**Comment by itutu-tienday** [comment]
> 上記の事象を再現できていないため、確認したパスワードと再現手順を教えて頂けますでしょうか

現在（5/11）のバージョンで、以下の動作を確認しています。

- SignIn画面で入力したパスワード … A_08888880
- login APIからの応答
  > (422 Unprocessable Entity)
  > {"detail":[{"loc":["body","password"],"msg":"string does not match regex \"^(?=.*\\d)(?=.*[@$!%*#?&])(?=.*[a-zA-Z]).{6,255}$\"","type":"value_error.str.regex","ctx":{"pattern":"^(?=.*\\d)(?=.*[@$!%*#?&])(?=.*[a-zA-Z]).{6,255}$"}}]}

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
現在のAccountパスワードのフォーマットルールは、下記のようになっていますので、A_08888880であれば、必須な特殊文字が含まないため、入力エラーと判定されています。

> 必須の桁タイプ：文字＋数字＋特殊文字（@$!%#?&）

Issueの説明欄に下記の要望が追加されているようですが、このように対応する必要でしょうね。

>  SingIn画面のパスワード欄では、フォーマットチェックを外しておいてください。
    パスワードの利用可能記号は、以下としてください。
　 !#$%&()*+,-./@_|

なお、現在、BE側がLogin APIでパスワードをバリデーションチェックしていますが、このパスワードのチェックも外しますか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> 現在のAccountパスワードのフォーマットルールは、下記のようになっていますので、A_08888880であれば、必須な特殊文字が含まないため、入力エラーと判定されています。

上記以外に、おそらく現在のチェックでは、「数字で終わるパスワード」自体が、拒否されていると思われます。
→ 文字/数字/記号 の出現位置には依存がないように、調整をお願いします。

> Issueの説明欄に下記の要望が追加されているようですが、このように対応する必要でしょうね。

はい、仕様を明示しました。

> なお、現在、BE側がLogin APIでパスワードをバリデーションチェックしていますが、このパスワードのチェックも外しますか。

はい、BE側もお願いします。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
>  SingIn画面のパスワード欄では、フォーマットチェックを外しておいてください。

上記の指摘は、SingIn画面のパスワード欄の以外、Change PasswordとAdd Accountの画面でも対応する必要でしょうか。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このIssueの対応とテスト実施が完了しました。
お手数ですが、ご確認お願い致します。
https://drive.google.com/file/d/1p-6en_PcT6QS8acXC7vLOx8PGQGYL7oW/view?usp=sharing

**Comment by itutu-tienday** [comment]
動作確認を行いましたが、以下が対応されていないようです。

> 上記以外に、おそらく現在のチェックでは、「数字で終わるパスワード」自体が、拒否されていると思われます。
> → 文字/数字/記号 の出現位置には依存がないように、調整をお願いします。

※フォーマットチェックの正規表現で、文字/数字/記号 の出現の順番が、固定されているのではないでしょうか。
再確認を、お願いします。

**Comment by Reactplus-Hao** [comment]
Bên KH check thì thấy phần dưới đây đang chưa được fix

> Họ check thì thấy có vẻ như mật khẩu kết thúc bằng số đang bị từ chối.
> Nhờ bên mình xử lý để không có phụ thuộc nào liên quan đến vị trí xuất hiện của chữ/ số/ kí tự.

Bên KH check thì thấy có vẻ như trong biểu thức chính quy của phần check format, trình tự xuất hiện của chữ/ số/ kí tự đang bị để cố định. Nhờ bên mình check lại giúp họ.

**Comment by Reactplus-Hao** [comment]
> Họ check thì thấy có vẻ như mật khẩu kết thúc bằng số đang bị từ chối.
> Nhờ bên mình xử lý để không có phụ thuộc nào liên quan đến vị trí xuất hiện của chữ/ số/ kí tự.

KH xin lỗi do họ check bị nhầm (Có vẻ là do không khớp với password cũ nên bị vậy)

Tuy nhiên, họ thấy có vẻ như issue dưới đây là bug
・Hiện tại đang có thể đăng ký cả những ký tự không cho phép (ví dụ như  { }) vào trong phần password.
　※Họ đã check ở những ô input mà đang check format cho password
　※Ngoài ra, nhờ bên Tester có thể chuẩn bị cho họ các pattern để test password có được không ạ?

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> ・利用不可の記号（例えば { }）も、パスワードに登録できてしまう。

上記の不具合の修正とテスト実施が完了しました。
パスワードのテストパターンも下記のように作成しましたので、ご確認お願い致します。
https://docs.google.com/spreadsheets/d/1zFJconGRo_zhmxUEHNX9oTABCHUHhsXR13DjFMfWJFc/edit#gid=0

**Comment by itutu-tienday** [comment]
修正を確認しました。

なお一点ソースコード上の指摘ですが、
パスワード書式ルール（記号）の定義は、なるべく1箇所で定数で定義しておくように、お願いします。
（現在のコードでは、6箇所ほど？に同じ文字列が記載されている）

**Comment by Reactplus-Hao** [comment]
> Hiện tại đang có thể đăng ký cả những ký tự không cho phép (ví dụ như { }) vào trong phần password.

KH đã check được phần chỉnh sửa trên của bên mình rồi.
Ngoài ra, họ nhờ mình chỉnh sửa phần dưới đây trong source code giúp họ.
Nhờ bên mình hãy định nghĩa phần rule của format password bằng hằng số ở 1 chỗ càng tốt.
（Hiện tại, có vẻ như đang là dạng string giống nhau ở khoảng 6 chỗ)

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> パスワード書式ルール（記号）の定義は、なるべく1箇所で定数で定義しておくように、お願いします。
（現在のコードでは、6箇所ほど？に同じ文字列が記載されている）

上記の指摘内容を対応して、最新ソースコードをfeature/dashboardブランチへPushしていますので、
ご確認お願い致します。

**Comment by Reactplus-Hao** [comment]
> 細かい点ですが、「const regexIgnoreS」が同じ内容で2箇所のファイルに定義されているのは、編集漏れでしょうか。

すみませんが、編集漏れでした。
修正して、最新ソースコードをfeature/dashboardブランチへPushしましたので、ご確認お願い致します。
