### ISSUE TITLE
Projects画面調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#77]
- 指摘
  - [x] Projects画面から、Workflow, Results へ遷移する際、Edit Project への遷移の様に、プロジェクトIDをURLへ指定するようにしてください。 （Workflow, Results画面の実装に必要）

- 希望期日: 5/12

**Comment by Reactplus-Hao** [comment]
Chỉnh sửa màn Projects
- Yêu cầu:
   - Khi từ màn Projects di chuyển đến màn Workflow, Results thì cũng hãy chỉ định Project ID vào URL giúp họ (Giống với khi di chuyển từ màn Projects đến màn Edit Projects bên mình đang chỉ định Project ID rồi)  （Cần implement cho màn Workflow, Results）
- Deadline: 5/12

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このIssueの対応とテスト実施が完了しました。
エビデンスは下記の通りとなりますので、ご確認お願い致します。
https://drive.google.com/file/d/1CgyqUl3AHpvVB7fOdXlG1bh_LYQn9aH7/view

**Comment by itutu-tienday** [comment]
ありがとうございます、修正を確認しました。
