### ISSUE TITLE
Result画面での処理エラーの詳細表示

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#78]
現在、Result画面では、処理結果のエラーの詳細を表示させることができない。
※Workflow画面上では、各ノードのエラーアイコンから、エラー詳細を確認可能。
※Recordsのデータ保存時（experiments.yaml）、エラー詳細情報が記録されていないため。

上記に対して、Result画面にて、処理エラーの詳細を確認できるようにする。

**Comment by ReiHashimoto** [comment]
https://github.com/oist/optinist/issues/492

**Comment by itutu-tienday** [comment]
バックグラウンド側は対応済み。
エラー情報の表示は関連チケット #104 で対応のため、クローズとする.
