### ISSUE TITLE
（質問）異なるホストへのAPIリクエストについて

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#80]
当システムのAPIについて、1. database API と 2. workspace API の2グループのAPIが用意されますが、
1. と 2. は、異なるホストまたは異なるポートで別プロセスとして起動することが想定されます。（最終的には、統合も想定される）

上記について、FEから 1. と 2. の異なるホストへのアクセスに際して、想定される課題を、お知らせいただきたく思います。

**Comment by Reactplus-Hao** [comment]
KH muốn confirm về việc request API đến các host khác nhau.

Hiện tại, API của hệ thống này đang được chuẩn bị thành 2 group API đó là: 1. database API và  2. workspace API 
Họ dự định group API 1. và 2. ở trên sẽ được khởi động dưới dạng process riêng biệt trong host khác nhau hoặc trong port khác nhau （Dự định về sau cùng cũng sẽ tích hợp）

Vì vậy, khi từ FE access đến host khác nhau của group API 1. và 2. ở trên, thì liệu có issue hay vấn đề gì xảy ra không?

**Comment by sanglevinh** [comment]
@Reactplus-Hao sẽ k có vấn đề gì nhé. Miễn có định nghĩa riêng biệt của từng api là được.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 上記について、FEから 1. と 2. の異なるホストへのアクセスに際して、想定される課題を、お知らせいただきたく思います。

FEから 1. と 2. の異なるホストへアクセスする時、現時点では特に想定される課題がありませんが、
前提条件としては、各APIに別の定義がある必要だと思います。
