### ISSUE TITLE
Workflow関連の表示項目調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#83]
- 資料
  - 画面設計_v11.pptx

#### 修正点

- 5-1. Workflow
  - "NWB SETTING" は非表示
  - 画面右上のgithub,ドキュメントページへのリンクを非表示
- 5-2. Result
  - RESULTS→RESULTへ名称変更
    - \4. Projects 画面内のリンクも更新
  - ヘッダ欄に "Start time" と "Finish time" を表示

**Comment by Reactplus-Hao** [comment]
- Tài liệu: 
   [LATEST_Screen design_v11 (16/5).pptx](https://docs.google.com/presentation/d/1FtOSEzRD7s2iEpQdrA024Psk48px2o_1/edit#slide=id.p1)
- Điểm cần chỉnh sửa:
   - 5-1. Workflow
       - Để ẩn bỏ text "NWB SETTING" 
       - Để ẩn bỏ link đến page Github và document ở phía trên bên phải màn hình
   - 5-2. Result
       - Thay đổi name RESULTS→RESULT
            - Cả link trong màn hình \4. Projects cũng cần update theo
       - Hiển thị  "Start time" và "Finish time" lên trên header

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このIssueの対応とテスト実施が完了致しました。
エビデンスは下記の通りですので、ご確認お願い致します。
https://drive.google.com/file/d/11CCS1Vbatd5rDw3Mcw9uNno1hVGn_VEq/view?usp=sharing

**Comment by itutu-tienday** [comment]
ありがとうございます。修正を確認しました。
