### ISSUE TITLE
Visualize画面のフォーム入力値の保存

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#92]
5-3. Visualize 画面のフォームの入力値（threshold, cut_coords）は、ユーザーが入力した情報を、保存できるようにする。

- 処理の概要
  - フォームの入力値は、ユーザーデータ領域（Firebase Custom Claims）へ格納する。
  - 入力値の保存/復元は、ユーザーの操作（Save/Load ボタンクリック）で行う。

- 資料
  - 画面設計_v11.1

### 修正点

- 6/14版
  - [x] "cut_coords" の書式が ` [int, int, int, int, int]` で固定されているが、想定仕様は「任意個数のint配列」となる。

- 6/16版
  - [x] （仕様変更）入力項目（threshold, cut_coords）の書式の変更
    - threshold … 「単一のfloat項目」とする
    - cut_coords …「任意個数のfloat配列」とする

**Comment by Reactplus-Hao** [comment]
**Lưu giá trị input form trong màn hình Visualize**
Xử lý để có thể lưu thông tin user đã input vào thành giá trị input trong form （threshold, cut_coords: coronal、sagittal、horizontal）trong màn hình 5-3. Visualize 

- Khái quát xử lý:
   - Giá trị input trong form sẽ được lưu trữ vào trong area data user (Firebase Custom Claims）
   - Việc lưu/ khôi phục giá trị input sẽ được tiến hành bằng cách click vào button Save/ Load

- Tài liệu:
https://docs.google.com/presentation/d/1FtOSEzRD7s2iEpQdrA024Psk48px2o_1/edit#slide=id.g224180341bc_0_1461

**Comment by reactplus-thom** [comment]
・PR：なし（以前からfeature/dashboardで直接作業していた）
・動作確認：https://drive.google.com/file/d/1RBYaMPl3itEP7ZpuimOlOCyMfgjXRSpE/view

**Comment by itutu-tienday** [comment]
@reactplus-thom 
以下、指摘を追加していますので、確認・対応をお願いします。

> - "cut_coords" の書式が ` [int, int, int, int, int]` で固定されているが、想定仕様は「任意個数のint配列」となる。

※画面設計書（v12）上では以下の様に記載していますが、これは任意個数の繰り返しを意味していました。
> ・書式は「整数, ..(繰り返し)」

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> また "threshold" については現在の仕様 [float, float] でOKです。
これは承知しました。

> "cut_coords" の書式が  [int, int, int, int, int] で固定されているが、想定仕様は「任意個数のint配列」となる。
> なお画面設計書（v12）上では以下の様に記載していますが、これは任意個数の繰り返しを意味していました。

なるほどです。すみませんが、念のため1点だけ確認させてください。
「任意個数」ということですが、個数が0でも可能という認識でよろしいでしょうか。

**Comment by itutu-tienday** [comment]
> 「任意個数」ということですが、個数が0でも可能という認識でよろしいでしょうか。

指摘ありがとうございます。
こちらは、個数は1個以上（必須入力とする）の設定で、お願いいたします。

**Comment by reactplus-thom** [comment]
Cần sửa lại điểm dưới đây:

3 ô nhập mục "cut_coords" chưa đúng với expect của khách.

- Hiện tại: giá trị đang truyền lên dạng [int, int, int, int, int]
- Expect: truyền giá trị dạng "mảng int với số lượng giá trị bất kỳ từ 1 trở lên"

Tức là hiện tại đang cố định bắt buộc phải nhập 5 giá trị nhưng đúng ra là cho nhập số lượng giá trị bất kỳ từ 1 trở lên (tức là vẫn là mục required)

**Comment by reactplus-thom** [comment]
@itutu-tienday 
以下のご指摘は対応終わりました。

> "cut_coords" の書式が [int, int, int, int, int] で固定されているが、想定仕様は「任意個数のint配列」となる。
> なお画面設計書（v12）上では以下の様に記載していますが、これは任意個数の繰り返しを意味していました。

ご確認よろしくお願い致します。
・PR：https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/160
・動作確認：https://drive.google.com/file/d/1koY0pZ1U5Z2FeKLf75Iv951tNFz3FNU1/view

**Comment by itutu-tienday** [comment]
@reactplus-thom 
こちらは、QA No.91 の質問（設定値の保存形式に関する質問）へ対応が行われましたら、確認・クローズを進めます。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
No.91 について、了解しました。
→ 動作確認OKと思いますので、クローズします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
当画面の入力項目仕様の再確認を行ったところ、以下が想定仕様であるという情報を得ています。

- （仕様変更）入力項目（threshold, cut_coords）の書式の変更
  - threshold … 「単一のfloat項目」とする
  - cut_coords …「任意個数のfloat配列」とする

申し訳ありませんが、上記への対応をいただきたいと思います。
※milestone を ver_20230621 へ更新しています。

**Comment by reactplus-thom** [comment]
Phía khách hàng muốn sửa lại kiểu dữ liệu của mục nhập như sau đây:

threshold: Sửa thành kiểu mục "single float"
cut_coords: Sửa thành kiểu mục "mảng float với số lượng giá trị bất kỳ"

**Comment by reactplus-thom** [comment]
@itutu-tienday 
念のため確認ですが、

> threshold … 「単一のfloat項目」とする

というのは、現状のような2値入力の仕様ではなく、1値のみ入力の仕様になるのでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 
はい、ご記載の様に 1値のみの入力 となりました。

よろしくお願いいたします。
