### ISSUE TITLE
Database API組み込みQA

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#98]
### 資料

- 環境構築手順等（Docker）
  - https://drive.google.com/drive/folders/1J29pi8FDTvBFh3wsnBdWlX0UHDzM6WjQ

### QA

- [x] 開発時はDatabase APIのportは8001（docker-compose.yaml設定）とする。 → FE側では問題はないか？
- [x] 「GET /rawdb/search」のResponse Dataの1階層目（projects）のIDは、設計では数値型だが、API開発者より文字列型としたいとの依頼あり。 → FE側では問題はないか？
- [x] 5/19提供版APIでは、「GET /rawdb/{id}」の応答はattribute(JSONファイル)のみの応答となっている。 → FE側では問題はないか？

**Comment by Reactplus-Hao** [comment]
Q&A liên quan đến phần tích hợp API Database
- Tài liệu:
    - Trình tự build môi trường
        - https://docs.google.com/document/d/1msk0zfugd8ptk13wPImN1KYu--BJtJii1ziL2i41qAc/edit
- QA:
   - Port của API Database khi phát triển để là 8001（Setting docker-compose.yaml） → Phía bên FE có vấn đề gì không?
   - ID của tầng thứ nhất (projects) trong Response Data của API「GET /rawdb/search」thì trong spec là dạng number, nhưng bên cty API muốn nhờ để dạng string → Phía bên FE có vấn đề gì không?
   - Trong [API đợt cung cấp ngày 19/5](https://drive.google.com/file/d/1R8T2J-IlT6CNG-r_4w3rBTXNscT-wELX/view?usp=share_link), thì response của API 「GET /rawdb/{id}」đang chỉ có attribute (File JSON) → Phía bên FE có vấn đề gì không?

**Comment by itutu-tienday** [comment]
以下、回答を記載します。

> 「GET /rawdb/search」のResponse Dataの1階層目（projects）のIDは、文字列型でも良いですが、IDは一意となる必要があります。

上記は、最新版（5/29版）では一意のIDとなっていると思われます。

> attribute(JSONファイル)とは、下記の画像の赤枠部分に該当するという認識で合っていますでしょうか。
> そうであれば、FE側では問題がございません。

はい、上記の内容となります。
問題ないということで、了解しました。

> ① GET /rawdb/searchについて
> 5/19提供の内容では、上記のAPIがデータを返るが、tree形式となっていない（開発途中）です。
> 現時点では、tree形式で返されていますでしょうか。
> IDは一意となる必要がありますが、現在のResponse Dataを確認してみると、一意となっていない様です。

最新版（5/29版）では、tree形式になっており、IDは一意と思われます。ご確認ください。

> ② GET /workdb/dataset/searchについて
> Add/Edit Project画面の右ペインに使用するという認識で合っていますでしょうか。

上記は、左ペインのデータ用です。
※右ペインは、RawDB（GET /rawdb/search）のデータになります。

> ③ GET /workdb/image/{project_id}/{image_id}
> Add Project画面にimage_idの取得が不要のため、この画面に使用する必要がないと思いますが、ご確認お願い致します。
> このAPIは追加新規のAPIのため、使用目的や仕様などがまだ不明になっています。
> お手数ですが、ご説明お願い出来ますでしょうか。

上記のURLは、GET /workdb/dataset/search の応答の image_url に格納されています。 そちらのURLをそのまま Viewerに設定します。
またAPIの利用箇所は、Add/Edit Project 画面の左ペインのViewerと、 5. Workspace の Alignment Dialogの画像表示です。

> ④ POST /workdb/datasetについて
> このAPIの使用目的や使用がまだ不明のため、ご説明お願いできますでしょうか。

※上記のAPI仕様は、ドキュメント v0.1.1 （2023/3）時点で、お伝えしています。 未確認であったということでしょうか？

上記は、Add/Edit Project 画面で左ペインで設定したデータを、バックエンドへ登録するAPIです。

**Comment by Reactplus-Hao** [comment]
> Trong [API đợt cung cấp ngày 19/5](https://drive.google.com/file/d/1R8T2J-IlT6CNG-r_4w3rBTXNscT-wELX/view?usp=share_link), thì response của API 「GET /rawdb/{id}」đang chỉ có attribute (File JSON).
Nếu attribute (File JSON) chính là phần khung đỏ trong ảnh dưới đây, thì FE bên mình không có vấn đề gì.

Đúng. Phần attribute (File JSON) chính là chỗ khung đỏ trong ảnh dưới đây.
<img width="760" alt="Screen Shot 2023-05-30 at 16 11 09" src="https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/87292605/197685a6-2ee1-4cd8-8040-cf56a3a96f76">

> Bên mình confirm: 
> ① Về API GET /rawdb/search
> ・Trong nội dung cung cấp ngày 19/5 thì họ có ghi là response của API này chưa trả về dạng Tree.
> Vậy thì hiện tại đã trả về dạng Tree chưa?
> ・Bên mình check Response Data hiện tại thì thấy ID đang bị trùng nhau

Trong [version KH cung cấp ngày 29/5](https://react-plus.slack.com/archives/C04GCUE5KSB/p1685327656020539), thì response đã ở dạng tree và ID cũng đã là unique rồi ạ. 
Nhờ bên mình check kỹ lại giúp họ.

> ② Về API GET /workdb/dataset/search
> Có phải API này tương ứng với khung bên phải trong màn hình Add/Edit Project có phải không?

API này dùng cho data trong khung bên trái của màn hình Add/ Edit Project
※Khung bên phải chính là data của API RawDB（GET /rawdb/search）

> ③ Về API GET /workdb/image/{project_id}/{image_id}
> Trong màn hình Add Project không cần get image_id, nên bên mình nghĩ không cần dùng API này trong màn hình Add Project
> Vì API này mới được thêm, nên nhờ KH có thể chỉ cho mình biết mục đích và spec của API này được không?

URL của API trên sẽ được lưu trữ trong image_url trong response của API GET /workdb/dataset/search. Và sẽ giữ nguyên URL đó và set vào Viewer
Ngoài ra, chỗ sử dụng API này thì gồm có: Viewer trong khung bên trái của màn Add/Edit Project và chỗ hiển thị ảnh trong Dialog Alignment

> ④ Về API POST /workdb/dataset
> Nhờ KH chỉ cho mình biết mục đích dùng API này được không?

※Spec của API trên đã được note trong docs API version v0.1.1 （2023/3）rồi. Bên mình chưa check docs này ạ?
Đây là API đăng ký data đã set trong khung bên trái của màn Add/Edit Project đến phía BE

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ご回答ありがとうございます。
なお、幾つかの確認事項がありますが、ご確認お願い致します。
① GET /workdb/dataset/searchについて、このAPIはproject_idが必須となっていますが、Add Project画面を表示する時に、まだProject IDがないです。
それでは、project_idをどのように設定する想定でしょうか。

② Add Project画面では、GET /rawdb/searchのAPI (右ペイン用）とPOST /workdb/datasetのAPI（左ペイン用）を使用する認識しています。
・Add Project画面の初期表示にPOST /workdb/datasetのデータがどのようになる想定でしょうか。
・右ペインのレコードを左ペインへドラッグ＆ドロップした時に、POST /workdb/datasetのデータがどのように変化されるか、教えて頂けますでしょうか。
（GET /rawdb/searchのデータはPOST /workdb/datasetのどのデータに該当するか、まだ理解できていないためです）

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
③ 下記のデータテストのファイルを使用して、セットアップしましたが、下記の課題があります。
- 確認手順：
   - 下記の2件のZipファイルを解凍し、フォルダ形式で ./vbm_front/test_mri_data へ配置する。
       - 20221030_145004_Keio_Abeyoshifumi_20221030_SU022_MAP_task_TG_1_281
       - 20211012_171333_Yagishita_Yagishita_20211012_H330_Chimerin_1_15
   - 下記の２つのコマンドを実行する
       - cd /var/vbm/script/converter
       - $ python3 /var/vbm/script/converter/pvconverter.py
  - GET /rawdb/search/list のResponse Dataを確認してみると、IDが重複になっている様です。
  - 1件のZipファイルを削除して、再度実行しましたが、IDがまだ重複になっている状態です。

<img width="1004" alt="Screen Shot 2023-05-31 at 15 52 38" src="https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/87292605/074ab109-c3a2-47cb-b205-a245e5f6cd44">

- 確認事項：
上記の場合では、DBをリセットするためのコマンドがありますでしょうか。
それとも、Dockerを削除して、再度ビルドする必要がありますか。

**Comment by itutu-tienday** [comment]
> ①  GET /workdb/dataset/searchについて、

（昨日も回答していますが、）まず ` GET /workdb/dataset/search` は、左ペインのデータ取得用のAPIとなります。
Add Project（新規登録）では、左ペインのデータは空であるため、利用対象外となります。
※APIドキュメントの説明が、やや曖昧だったのかもしれません。 → APIドキュメントへ、上記の説明を追記しておきます。

> ② Add Project画面では、

- まず、`GET /workdb/dataset/search`（左ペイン用）と、`POST /workdb/dataset` は、対のもの となっています。
  - `POST /workdb/dataset` で左ペインのデータを登録（IN）
  - `GET /workdb/dataset/search` で左ペインのデータを取得（OUT）
  - 上記の想定です。
- 当初の設計では、右→左ペインへ移動する都度、POST APIでデータを登録するフローを想定していましたが、設計の複雑化が想定されたため、現在の設計では「画面のOKボタンを押したタイミングで 左ペインのデータを一括登録（`POST /workdb/dataset` ）する」としています。
※上記の内容は、設計資料（画面設計orAPI設計）へ掲載していた認識でしたが、最新版を確認したところ記載がなかったため、記載しておきます。

**Comment by Reactplus-Hao** [comment]
① 
> Em hỏi khách api này: http://localhost/workdb/dataset/search chỉ dùng lúc edit đúng không vì anh thấy api này đang required project_id
> mà lúc add project thì k có id.

Hôm qua KH cũng đã trả lời mình rồi, `GET /workdb/dataset/search` là API dùng để get data của khung bên trái 
Trong màn Add Project（đăng ký mới）thì data của khung bên trái trống, nên trong màn hình này không cần dùng API `GET /workdb/dataset/search`
※ Có lẽ do họ giải thích chưa rõ ràng trong docs API, nên họ sẽ sửa lại phần giải thích trên vào docs API

② 

> Trong màn Add Project sẽ dùng API `GET /rawdb/search` (khung bên phải) và `POST /workdb/dataset` (khung bên trái)
> ・Vậy thì khi hiển thị ban đầu màn hình Add Project, data của `POST /workdb/dataset` sẽ như thế nào?
> ・Khi drag&drop record từ khung bên phải sang trái, thì data của `POST /workdb/dataset` sẽ thay đổi như thế nào?

- GET /workdb/dataset/search（khung bên trái) và POST /workdb/dataset là 1 cặp
    - Sẽ tiến hành đăng ký data trong khung bên trái bằng `POST /workdb/dataset` （IN）
    - Sẽ lấy data của khung bên trái bằng `GET /workdb/dataset/search` （OUT）

- Trong spec ban đầu họ dự định là mỗi lần drag&drop từ bên phải sang trái, thì sẽ đăng ký data bằng POST API. 
Tuy nhiên có vẻ phức tạp, nên họ đã quyết định spec: "Thời điểm nhất vào button OK trên màn hình, thì sẽ đăng ký hàng loạt data của khung bên trái bằng `POST /workdb/dataset` "
※ Họ sẽ mô tả thêm thông tin trên vào trong spec sau.

③ 
> Vụ bên mình check với 2 file data test, thì bị trùng ID của API GET /rawdb/search/list 

KH hiểu rồi ạ. Bên họ check với file data khác thì cũng đang thấy bị trình ID, nên họ sẽ check lại với cty API.
Tạm thời, bên mình cứ pending lại vụ trùng ID và tích hợp API giúp họ ạ. 
(Nếu như việc trùng ID có ảnh hưởng đến phần tích hợp API, thì hãy báo họ biết)

> Bên mình hỏi có command nào để reset DB không

Bên họ cũng đã hỏi cty API rồi, tuy nhiên hiện tại đang không có function reset data. KH sẽ check thêm với cty API về vụ reset xem sao.
Vì vậy, tạm thời cần phải build lại môi trường Docker ạ.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> - まず、GET /workdb/dataset/search（左ペイン用）と、POST /workdb/dataset は、対のもの となっています。
>    - POST /workdb/dataset で左ペインのデータを登録（IN）
>    - GET /workdb/dataset/search で左ペインのデータを取得（OUT）
> - 当初の設計では、右→左ペインへ移動する都度、POST APIでデータを登録するフローを想定していましたが、設計の複雑化が想定されたため、現在の設計では「画面のOKボタンを押したタイミングで 左ペインのデータを一括登録（POST /workdb/dataset ）する」としています。

右ペインのレコードのデータは下記の画像のようになりますね。
<img width="406" alt="Screen Shot 2023-05-31 at 17 49 58" src="https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/87292605/4340d92d-27de-489a-b56b-a76ca57ae42d">

右ペインのレコードを左ペインへ移動して、「OK」ボタンを押した時に、POST /workdb/datasetの下記画像の各キーはDatabaseレコード（右ペインのレコード）のどのキーから取得するのでしょうか。
（POST /workdb/datasetのデータ構造を作成する方式が理解していないため）
<img width="316" alt="Screen Shot 2023-05-31 at 17 44 46" src="https://github.com/arayabrain/MRIAnalysisStudioforMouse/assets/87292605/511b49c7-9bc3-4b2b-9b01-27e2e0af8b44">

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
> 右ペインのレコードを左ペインへ移動して、「OK」ボタンを押した時に、POST /workdb/datasetの下記画像の各キーはDatabaseレコード（右ペインのレコード）のどのキーから取得するのでしょうか。

改めて、`POST /workdb/dataset` の POSTデータは、**左ペインのデータ表示内容と同様** となります。
以下、ご確認ください。

### 項目説明

  - folders … 1階層目のフォルダ（Between factor）の一覧
  - folder_name … 各フォルダのラベル
  - sub_folders … 2階層目のフォルダ（Between factor-within factor）の一覧 （Optional、「Between factor」の場合は未使用）
  - source_image_ids … 右ペインから登録した画像レコードのID （Optional）
  
### Examples

- Example 1 (Between factor)
  - View (Left Pane)
    ```
    Between factor name 1
      image #1
      image #2
    Between factor name 2
      image #3
      image #4
    ```
  - POST Data
    ```json
    {
      "folders": [
        {
          "folder_name": "Between factor name 1",
          "source_image_ids": [
            1, 2
          ]
        },
        {
          "folder_name": "Between factor name 2",
          "source_image_ids": [
            3, 4
          ]
        }
      ]
    }
    ```

- Example 2 (Between factor-within factor)
  - View (Left Pane)
    ```
    Between factor name 1
      Within factor name 1
        image #1
        image #2
    Between factor name 2
      image #3
      image #4
    ```
  - POST Data
    ```json
    {
      "folders": [
        {
          "folder_name": "Between factor name 1",
          "sub_folders": [
            {
              "folder_name": "Within factor name 1",
              "source_image_ids": [
                1, 2
              ]
            }
          ],
          "source_image_ids": [
            3, 4
          ]
        },
        {
          "folder_name": "Between factor name 2",
          "source_image_ids": [
            3, 4
          ]
        }
      ]
    }
    ```

----

以上ですが、説明にミーティングが必要であれば、お知らせください。

**Comment by Reactplus-Hao** [comment]
> Khi di chuyển record từ khung bên phải sang bên trái, thì sau khi nhấn button OK, các key ​của `POST /workdb/dataset` được lấy từ đâu?

Tóm lại, data POST của API `POST /workdb/dataset ` giống nội dung hiển thị data của khung bên trái

**Giải thích các mục**
- folders …  List folder ở tầng 1（Chính là tầng Between factor）
- folder_name … Label của các folder
- sub_folders … List folder của tầng 2（Chính là tầng Between factor-within factor）（Trường hợp Optional là「Between factor」thì sẽ không dùng mục này）
- source_image_ids … ID của record ảnh đã đăng ký từ khung bên phải sang （Optional）

**Examples**
- Example 1 (Between factor)

   - View (Left Pane)
```
Between factor name 1
  image #1
  image #2
Between factor name 2
  image #3
  image #4
POST Data
[
  {
    "folder_name": "Between factor name 1",
    "source_image_ids": [
      1, 2
    ]
  },
  {
    "folder_name": "Between factor name 2",
    "source_image_ids": [
      3, 4
    ]
  }
]
```

- Example 2 (Between factor-within factor)

    - View (Left Pane)
```
Between factor name 1
  Within factor name 1
    image #1
    image #2
Between factor name 2
  image #3
  image #4
POST Data
[
  {
    "folder_name": "Between factor name 1",
    "sub_folders": [
      {
        "folder_name": "Within factor name 1",
        "source_image_ids": [
          1, 2
        ]
      }
    ]
  },
  {
    "folder_name": "Between factor name 2",
    "source_image_ids": [
      3, 4
    ]
  }
]
```
------------
Hãy post data trong Sample ở trên, và thử check nội dung response của data trong API `GET /workdb/dataset/search` 
Nếu cần họ giải thích nữa, thì họ có thể MTG giải thích cho mình nên hãy báo họ ạ.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
「OK」ボタンを押した時に、下記の２つのAPIを呼び出すという認識で合っていますでしょうか。
・`POST /workdb/project`
・`POST /workdb/dataset`

**Comment by itutu-tienday** [comment]
以下の想定となります

- 4-1. Add Project の OKボタン押下時
  1. `POST /workdb/project` で Projectを新規作成
  2. 1. の応答のproject_id を用いて、`POST /workdb/dataset` で Datasetを登録

- 4-2. Edit Project の OKボタン押下時
  1. `PUT /workdb/project` で Projectを更新
  2. `POST /workdb/dataset` で Datasetを登録

**Comment by Reactplus-Hao** [comment]
Thao tác khi nhấn button OK (Khi xác nhận đăng ký) thì sẽ như dưới đây:

- Khi nhấn button OK trong màn 4-1. Add Project 
     - ① Sẽ tạo mới Project bằng API `POST /workdb/project `
     - ② Sẽ dùng project_id trong response của phần ① ở trên và đăng ký Dataset bằng API `POST /workdb/dataset` 
     
- Khi nhấn button OK trong màn hình 4-2. Edit Project 
    - Sẽ update Project bằng API `PUT /workdb/project` 
    - Sẽ đăng ký Dataset bằng API `POST /workdb/dataset`
